# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
import encrypted_model_fields.fields
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_conf', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='GophishGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'Gophish Guide',
                'verbose_name_plural': 'Gophish Guides',
            },
        ),
        migrations.CreateModel(
            name='AccessGophish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=False, verbose_name='Has access to Gophish')),
                ('can_view_campaigns', models.BooleanField(default=False, verbose_name='Can view campaigns')),
                ('can_view_templates', models.BooleanField(default=False, verbose_name='Can view templates')),
                ('can_view_landing_pages', models.BooleanField(default=False, verbose_name='Can view landing pages')),
                ('can_view_sending_profiles', models.BooleanField(default=False, verbose_name='Can view sending profiles')),
                ('can_view_groups', models.BooleanField(default=False, verbose_name='Can view target groups')),
                ('can_manage_servers', models.BooleanField(default=False, verbose_name='Can manage servers')),
                ('can_sync', models.BooleanField(default=False, verbose_name='Can synchronize data')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('companies', models.ManyToManyField(blank=True, related_name='access_gophish', to='app_conf.company', verbose_name='Companies')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Access to Gophish',
                'verbose_name_plural': 'Access to Gophish',
            },
        ),
        migrations.CreateModel(
            name='GophishServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Server Name')),
                ('base_url', models.URLField(verbose_name='Base URL')),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField(verbose_name='API Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conf.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gophish_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gophish Server',
                'verbose_name_plural': 'Gophish Servers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GophishSendingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gophish_id', models.CharField(max_length=50, verbose_name='Gophish ID')),
                ('name', models.CharField(max_length=200, verbose_name='Profile Name')),
                ('from_address', models.EmailField(max_length=254, verbose_name='From Address')),
                ('from_name', models.CharField(max_length=200, verbose_name='From Name')),
                ('smtp_host', models.CharField(max_length=200, verbose_name='SMTP Host')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('smtp_username', models.CharField(max_length=200, verbose_name='SMTP Username')),
                ('smtp_password', encrypted_model_fields.fields.EncryptedCharField(verbose_name='SMTP Password')),
                ('ignore_cert_errors', models.BooleanField(default=False, verbose_name='Ignore Certificate Errors')),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_profiles', to='app_gophish.gophishserver')),
            ],
            options={
                'verbose_name': 'Gophish Sending Profile',
                'verbose_name_plural': 'Gophish Sending Profiles',
                'ordering': ['name'],
                'unique_together': {('server', 'gophish_id')},
            },
        ),
        migrations.CreateModel(
            name='GophishLandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gophish_id', models.CharField(max_length=50, verbose_name='Gophish ID')),
                ('name', models.CharField(max_length=200, verbose_name='Landing Page Name')),
                ('html_content', models.TextField(verbose_name='HTML Content')),
                ('capture_credentials', models.BooleanField(default=False, verbose_name='Capture Credentials')),
                ('capture_passwords', models.BooleanField(default=False, verbose_name='Capture Passwords')),
                ('redirect_url', models.URLField(blank=True, verbose_name='Redirect URL')),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='app_gophish.gophishserver')),
            ],
            options={
                'verbose_name': 'Gophish Landing Page',
                'verbose_name_plural': 'Gophish Landing Pages',
                'ordering': ['name'],
                'unique_together': {('server', 'gophish_id')},
            },
        ),
        migrations.CreateModel(
            name='GophishGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gophish_id', models.CharField(max_length=50, verbose_name='Gophish ID')),
                ('name', models.CharField(max_length=200, verbose_name='Group Name')),
                ('targets_data', models.JSONField(default=dict, verbose_name='Targets Data')),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='app_gophish.gophishserver')),
            ],
            options={
                'verbose_name': 'Gophish Group',
                'verbose_name_plural': 'Gophish Groups',
                'ordering': ['name'],
                'unique_together': {('server', 'gophish_id')},
            },
        ),
        migrations.CreateModel(
            name='GophishSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('campaigns', 'Campaigns Only'), ('groups', 'Groups Only'), ('templates', 'Templates Only'), ('landing_pages', 'Landing Pages Only'), ('sending_profiles', 'Sending Profiles Only'), ('results', 'Results Only')], max_length=20, verbose_name='Sync Type')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('records_processed', models.IntegerField(default=0, verbose_name='Records Processed')),
                ('records_created', models.IntegerField(default=0, verbose_name='Records Created')),
                ('records_updated', models.IntegerField(default=0, verbose_name='Records Updated')),
                ('records_failed', models.IntegerField(default=0, verbose_name='Records Failed')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('details', models.JSONField(default=dict, verbose_name='Sync Details')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='app_gophish.gophishserver')),
            ],
            options={
                'verbose_name': 'Gophish Sync Log',
                'verbose_name_plural': 'Gophish Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GophishTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gophish_id', models.CharField(max_length=50, verbose_name='Gophish ID')),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('subject', models.CharField(max_length=500, verbose_name='Subject')),
                ('html_content', models.TextField(verbose_name='HTML Content')),
                ('text_content', models.TextField(blank=True, verbose_name='Text Content')),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='app_gophish.gophishserver')),
            ],
            options={
                'verbose_name': 'Gophish Template',
                'verbose_name_plural': 'Gophish Templates',
                'ordering': ['name'],
                'unique_together': {('server', 'gophish_id')},
            },
        ),
        migrations.CreateModel(
            name='GophishCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gophish_id', models.CharField(max_length=50, verbose_name='Gophish ID')),
                ('name', models.CharField(max_length=200, verbose_name='Campaign Name')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('paused', 'Paused'), ('error', 'Error')], default='draft', max_length=20, verbose_name='Status')),
                ('launch_date', models.DateTimeField(blank=True, null=True, verbose_name='Launch Date')),
                ('send_by_date', models.DateTimeField(blank=True, null=True, verbose_name='Send By Date')),
                ('url', models.URLField(blank=True, verbose_name='Campaign URL')),
                ('results_data', models.JSONField(default=dict, verbose_name='Results Data')),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gophish_campaigns', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(related_name='campaigns', to='app_gophish.gophishgroup', verbose_name='Target Groups')),
                ('landing_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='app_gophish.gophishlandingpage')),
                ('sending_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='app_gophish.gophishsendingprofile')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='app_gophish.gophishserver')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='app_gophish.gophishtemplate')),
            ],
            options={
                'verbose_name': 'Gophish Campaign',
                'verbose_name_plural': 'Gophish Campaigns',
                'ordering': ['-created_at'],
                'unique_together': {('server', 'gophish_id')},
            },
        ),
        migrations.CreateModel(
            name='GophishEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('email_sent', 'Email Sent'), ('email_opened', 'Email Opened'), ('link_clicked', 'Link Clicked'), ('credentials_submitted', 'Credentials Submitted'), ('data_submitted', 'Data Submitted'), ('error', 'Error')], max_length=50, verbose_name='Event Type')),
                ('target_email', models.EmailField(max_length=254, verbose_name='Target Email')),
                ('target_name', models.CharField(blank=True, max_length=200, verbose_name='Target Name')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('details', models.JSONField(default=dict, verbose_name='Event Details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app_gophish.gophishcampaign')),
            ],
            options={
                'verbose_name': 'Gophish Event',
                'verbose_name_plural': 'Gophish Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['campaign', 'event_type'], name='app_gophish_campaig_7f818c_idx'), models.Index(fields=['target_email'], name='app_gophish_target__17372f_idx'), models.Index(fields=['timestamp'], name='app_gophish_timesta_73be2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='GophishGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gophish_guide_translations', to='app_conf.country', verbose_name='Country')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_gophish.gophishguide', verbose_name='Guide')),
            ],
            options={
                'verbose_name': 'Gophish Guide Translation',
                'verbose_name_plural': 'Gophish Guide Translations',
                'ordering': ['country__name'],
                'unique_together': {('guide', 'country')},
            },
        ),
    ]
