# Generated by Django 5.2.8 on 2026-06-10 10:40

import app_doc.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_conf', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name, default: English (En). E.g. Confidential, Public. For other languages use Translations inline.', max_length=100, verbose_name='Classification Name')),
                ('name_local', models.CharField(blank=True, help_text='Name in local language (use Translations inline for per-country names)', max_length=100, verbose_name='Local Name')),
                ('code', models.CharField(blank=True, help_text='Unique code (e.g., confidential, public)', max_length=50, unique=True, verbose_name='Classification Code')),
                ('description', models.TextField(blank=True, help_text='Description, default: English (En). For other languages use Translations inline.', verbose_name='Description')),
                ('color', models.CharField(default='#6c757d', help_text='Color in HEX format, e.g. #FF0000', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(default='fa-lock', help_text='FontAwesome icon class, e.g. fa-lock, fa-shield-alt', max_length=50, verbose_name='Icon')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in sorting. 0 = highest security level', verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Access Classification',
                'verbose_name_plural': 'Access Classifications',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Status name, default: English (En). E.g. Draft, Approved. For other languages use Translations inline.', max_length=100, verbose_name='Status Name')),
                ('name_local', models.CharField(blank=True, help_text='Status name in local language (use Translations inline for per-country names)', max_length=100, verbose_name='Local Name')),
                ('code', models.CharField(blank=True, help_text='Unique code (e.g., draft, approved)', max_length=50, unique=True, verbose_name='Status Code')),
                ('description', models.TextField(blank=True, help_text='Description of this status, default: English (En). For other languages use Translations inline.', verbose_name='Description')),
                ('color', models.CharField(default='#000000', help_text='Color in HEX format, e.g. #FF0000', max_length=7, verbose_name='Color')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in sorting. 0 = highest priority', verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Document Status',
                'verbose_name_plural': 'Document Status',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Type name, default: English (En). E.g. Policy, Procedure. For other languages use Translations inline.', max_length=100, verbose_name='Type Name')),
                ('name_local', models.CharField(blank=True, help_text='Type name in local language (use Translations inline for per-country names)', max_length=100, verbose_name='Local Name')),
                ('code', models.CharField(blank=True, help_text='Unique code (e.g., policy, procedure)', max_length=50, unique=True, verbose_name='Type Code')),
                ('description', models.TextField(blank=True, help_text='Description of this type, default: English (En). For other languages use Translations inline.', verbose_name='Description')),
                ('color', models.CharField(default='#000000', help_text='Color in HEX format, e.g. #FF0000', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
            },
        ),
        migrations.CreateModel(
            name='LegislativeDocsGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'Legislative Docs Guide',
                'verbose_name_plural': 'Legislative Docs Guides',
            },
        ),
        migrations.CreateModel(
            name='RegDocsGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'Reg Docs Guide',
                'verbose_name_plural': 'Reg Docs Guides',
            },
        ),
        migrations.CreateModel(
            name='AccessDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=False, verbose_name='Has access to Docs')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Can edit Docs')),
                ('description', models.TextField(blank=True)),
                ('companies', models.ManyToManyField(blank=True, related_name='access_docs', to='app_conf.company', verbose_name='Companies')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Access to Docs',
                'verbose_name_plural': 'Access to Docs',
            },
        ),
        migrations.CreateModel(
            name='RegulatorName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Regulator Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Regulator Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website URL')),
                ('color', models.CharField(default='#e0f7fa', help_text='Color in HEX format for text color, e.g. #FF0000', max_length=7, verbose_name='Display Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Regulator',
                'verbose_name_plural': 'Regulators',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='app_doc_reg_name_a76708_idx'), models.Index(fields=['code'], name='app_doc_reg_code_e597c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='RelatedDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rel_doc', models.CharField(max_length=255, verbose_name='Related Document Name')),
                ('date_rel_doc', models.DateField(verbose_name='Related Document Date')),
                ('vers_rel_doc', models.CharField(max_length=50, verbose_name='Related Document Version')),
                ('vers_rel_doc_html', models.TextField(blank=True, null=True, verbose_name='Related Document HTML Version')),
                ('description_rel_doc', models.TextField(verbose_name='Related Document Description')),
                ('file_rel_doc', models.FileField(blank=True, null=True, upload_to='related_documents/', verbose_name='Related Document File')),
                ('access_classification', models.ForeignKey(blank=True, help_text='Security level / access restriction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_doc.accessclassification', verbose_name='Access Classification')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_conf.company', verbose_name='Company')),
                ('groups', models.ManyToManyField(blank=True, related_name='related_docs', to='auth.group', verbose_name='Groups')),
                ('status_rel_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_doc.docstatus', verbose_name='Related Document Status')),
            ],
            options={
                'verbose_name': 'Related Document',
                'verbose_name_plural': 'Related Documents',
                'ordering': ['status_rel_doc__sort_order', '-date_rel_doc', 'name_rel_doc'],
            },
        ),
        migrations.CreateModel(
            name='RegisterDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doc', models.CharField(db_index=True, help_text='Enter the name of the document', max_length=255, verbose_name='Document Name')),
                ('vers_doc', models.CharField(max_length=50, verbose_name='Document Version')),
                ('vers_doc_html', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Document HTML Version')),
                ('date_doc', models.DateField(default=django.utils.timezone.now, verbose_name='Document Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('version_history', models.TextField(blank=True, help_text='History of changes', null=True, verbose_name='Version history')),
                ('file_doc', models.FileField(blank=True, null=True, upload_to=app_doc.models.document_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt']), app_doc.models.validate_file_size], verbose_name='Document File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('document_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Document Hash')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved')),
                ('access_classification', models.ForeignKey(blank=True, help_text='Security level / access restriction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_doc.accessclassification', verbose_name='Access Classification')),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Additional users with access to this document (Cabinet users)', related_name='register_docs_allowed', to=settings.AUTH_USER_MODEL, verbose_name='Cabinet users (access)')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_conf.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('groups', models.ManyToManyField(blank=True, related_name='register_docs', to='auth.group', verbose_name='Groups')),
                ('previous_version', models.ForeignKey(blank=True, help_text='Previous Document Registry entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='app_doc.registerdocs', verbose_name='Previous Document')),
                ('status_doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_doc.docstatus', verbose_name='Document Status')),
                ('type_doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_doc.doctype', verbose_name='Document Type')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('related_docs', models.ManyToManyField(blank=True, to='app_doc.relateddocs', verbose_name='Related Documents')),
            ],
            options={
                'verbose_name': 'Register Document',
                'verbose_name_plural': 'Register Documents',
                'ordering': ['status_doc__sort_order', '-date_doc', 'name_doc'],
            },
        ),
        migrations.CreateModel(
            name='AccessClassificationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(help_text="Classification name in country's language", max_length=100, verbose_name='Local Name')),
                ('description', models.TextField(blank=True, help_text="Description in country's language", verbose_name='Description')),
                ('access_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_doc.accessclassification', verbose_name='Access Classification')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_classification_translations', to='app_conf.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Access Classification Translation',
                'verbose_name_plural': 'Access Classification Translations',
                'ordering': ['country__name'],
                'unique_together': {('access_classification', 'country')},
            },
        ),
        migrations.CreateModel(
            name='AccessLegislativeDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=False, verbose_name='Has access to Legislative Docs')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Can edit Legislative Docs')),
                ('show_link', models.BooleanField(default=False, verbose_name='Show Legislative Docs link')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Access to Legislative Docs',
                'verbose_name_plural': 'Access to Legislative Docs',
                'ordering': ['group__name'],
                'indexes': [models.Index(fields=['group'], name='app_doc_acc_group_i_7345cf_idx'), models.Index(fields=['has_access'], name='app_doc_acc_has_acc_c217b9_idx'), models.Index(fields=['can_edit'], name='app_doc_acc_can_edi_1ca19a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccessMandatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=False, verbose_name='Has access to Mandatory Processes Registry')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Can edit Mandatory Processes Registry')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('companies', models.ManyToManyField(blank=True, related_name='access_mandatory', to='app_conf.company', verbose_name='Companies')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Access to Mandatory Processes',
                'verbose_name_plural': 'Access to Mandatory Processes',
                'ordering': ['group__name'],
                'indexes': [models.Index(fields=['group'], name='app_doc_acc_group_i_8ad0b4_idx'), models.Index(fields=['has_access'], name='app_doc_acc_has_acc_faf58c_idx'), models.Index(fields=['can_edit'], name='app_doc_acc_can_edi_c8e1f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocStatusTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(help_text="Status name in country's language", max_length=100, verbose_name='Local Name')),
                ('description', models.TextField(blank=True, help_text="Description in country's language", verbose_name='Description')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_status_translations', to='app_conf.country', verbose_name='Country')),
                ('doc_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_doc.docstatus', verbose_name='Document Status')),
            ],
            options={
                'verbose_name': 'Document Status Translation',
                'verbose_name_plural': 'Document Status Translations',
                'ordering': ['country__name'],
                'unique_together': {('doc_status', 'country')},
            },
        ),
        migrations.CreateModel(
            name='DocTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(help_text="Type name in country's language", max_length=100, verbose_name='Local Name')),
                ('description', models.TextField(blank=True, help_text="Description in country's language", verbose_name='Description')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_type_translations', to='app_conf.country', verbose_name='Country')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_doc.doctype', verbose_name='Document Type')),
            ],
            options={
                'verbose_name': 'Document Type Translation',
                'verbose_name_plural': 'Document Type Translations',
                'ordering': ['country__name'],
                'unique_together': {('doc_type', 'country')},
            },
        ),
        migrations.CreateModel(
            name='LegislativeDocsGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legislative_docs_guide_translations', to='app_conf.country', verbose_name='Country')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_doc.legislativedocsguide', verbose_name='Guide')),
            ],
            options={
                'verbose_name': 'Legislative Docs Guide Translation',
                'verbose_name_plural': 'Legislative Docs Guide Translations',
                'ordering': ['country__name'],
                'unique_together': {('guide', 'country')},
            },
        ),
        migrations.CreateModel(
            name='RegDocsGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_docs_guide_translations', to='app_conf.country', verbose_name='Country')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_doc.regdocsguide', verbose_name='Guide')),
            ],
            options={
                'verbose_name': 'Reg Docs Guide Translation',
                'verbose_name_plural': 'Reg Docs Guide Translations',
                'ordering': ['country__name'],
                'unique_together': {('guide', 'country')},
            },
        ),
        migrations.CreateModel(
            name='DocumentFamiliarization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_hash', models.CharField(max_length=64, verbose_name='Document Hash')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, verbose_name='Acknowledged At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_familiarizations', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiarization_set', to='app_doc.registerdocs')),
            ],
            options={
                'verbose_name': 'Document Familiarization',
                'verbose_name_plural': 'Document Familiarizations',
                'ordering': ['-acknowledged_at'],
                'unique_together': {('document', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('document_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_doc.registerdocs')),
            ],
            options={
                'unique_together': {('document', 'approver')},
            },
        ),
        migrations.CreateModel(
            name='LegislativeDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('doc_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Document Number')),
                ('issuing_authority', models.CharField(blank=True, max_length=255, null=True, verbose_name='Issuing Authority')),
                ('original_url', models.URLField(blank=True, help_text='URL to the original document source', max_length=1000, null=True, verbose_name='Original Document URL')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Effective Date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='legislative_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), app_doc.models.validate_file_size], verbose_name='PDF Document')),
                ('html_content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='HTML Content')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ManyToManyField(blank=True, related_name='legislative_docs', to='app_conf.company', verbose_name='Companies')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_legislative_docs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('doc_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legislative_docs', to='app_doc.doctype', verbose_name='Document Type')),
                ('groups', models.ManyToManyField(blank=True, related_name='legislative_docs', to='auth.group', verbose_name='Groups')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_legislative_docs', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('regulator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legislative_docs', to='app_doc.regulatorname', verbose_name='Regulator')),
            ],
            options={
                'verbose_name': 'Legislative Document',
                'verbose_name_plural': 'Legislative Documents',
                'ordering': ['-effective_date', 'title'],
                'indexes': [models.Index(fields=['title'], name='app_doc_leg_title_3809c7_idx'), models.Index(fields=['doc_type'], name='app_doc_leg_doc_typ_ad5e18_idx'), models.Index(fields=['issue_date'], name='app_doc_leg_issue_d_832522_idx'), models.Index(fields=['effective_date'], name='app_doc_leg_effecti_504d91_idx'), models.Index(fields=['is_active'], name='app_doc_leg_is_acti_782168_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='registerdocs',
            index=models.Index(fields=['name_doc'], name='app_doc_reg_name_do_ec6bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='registerdocs',
            index=models.Index(fields=['date_doc'], name='app_doc_reg_date_do_0ea039_idx'),
        ),
        migrations.AddIndex(
            model_name='registerdocs',
            index=models.Index(fields=['is_active'], name='app_doc_reg_is_acti_a671fa_idx'),
        ),
        migrations.AddIndex(
            model_name='registerdocs',
            index=models.Index(fields=['document_hash'], name='app_doc_reg_documen_922551_idx'),
        ),
        migrations.AddIndex(
            model_name='registerdocs',
            index=models.Index(fields=['is_approved'], name='app_doc_reg_is_appr_231bc1_idx'),
        ),
    ]
