# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdocs',
            name='previous_version',
            field=models.ForeignKey(blank=True, help_text='Previous Document Registry entry (version)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='app_doc.registerdocs', verbose_name='Previous version'),
        ),
    ]
