# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0002_add_registerdocs_previous_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdocs',
            name='version_history',
            field=models.TextField(blank=True, help_text='History of changes', null=True, verbose_name='Version history'),
        ),
    ]
