# SecBoard/settings.py — Django project configuration
"""
Django settings for SecBoard project.
Generated by 'django-admin startproject' using Django 5.0.8.

EN: Central configuration; many sensitive and environment-specific values come from credential.py.
UK: Центральні налаштування; секрети та параметри середовища зазвичай у credential.py.
"""
import os
from django.utils.translation import gettext_lazy as _
# EN: Deployment secrets (DB, keys, CORS/CSRF lists, Redis) — see bilingual comments in credential.py.
# UK: Секрети та списки з credential.py — див. коментарі EN/UK у тому файлі.
from .credential import (
    secret_key, database, recaptcha_public_key, recaptcha_private_key,
    webhook_encryption_key, debug,
    allowed_hosts, csrf_trusted_origins,
    cors_allowed_origins, cors_allowed_origin_regexes,
    redis_host, redis_port, redis_db,
    timezone, public_base_url, default_from_email,
    site_domain, site_protocol,
    default_admin_username,
)
from logging.handlers import RotatingFileHandler
from concurrent_log_handler import ConcurrentRotatingFileHandler
import base64

# EN: Runtime integrity guard for compiled / tamper-resistant builds (.so present).
# UK: Перевірка цілісності для зібраних білдів (наявність .so).
def verify_settings_integrity():
    """
    EN: Validates settings binaries in compiled builds; blocks obvious tampering.
    UK: Перевірка цілісності settings у компільованих білдах; захист від підміни.

    Individual .so hash verification is handled by the RSA-signed code manifest
    (checked at runtime in SecureLicenseMiddleware._verify_code_manifest).
    This function performs the fast, import-time sanity checks only.
    """
    try:
        settings_file = __file__
        settings_dir = os.path.dirname(os.path.abspath(settings_file))

        settings_so_files = []
        if os.path.exists(settings_dir):
            for file in os.listdir(settings_dir):
                if file.startswith('settings.cpython-') and file.endswith('.so'):
                    settings_so_files.append(file)

        # If .so exists but Python loaded .py instead — someone dropped a .py shim
        if settings_file.endswith('.py') and settings_so_files:
            raise RuntimeError(
                f"SECURITY ALERT: settings.py loaded as .py, but .so exists! "
                f"Possible tampering: settings.so was bypassed. "
                f"Found .so files: {settings_so_files}"
            )

        # In compiled builds, verify code manifest is present
        if settings_so_files:
            manifest_path = os.path.join(os.path.dirname(settings_dir), '.secboard_code_manifest.json')
            if not os.path.exists(manifest_path):
                import logging
                logging.getLogger(__name__).warning(
                    "Compiled build detected but .secboard_code_manifest.json not found — "
                    "integrity will be enforced by middleware on first request"
                )

        # Basic sanity for .py development builds
        if settings_file.endswith('.py'):
            if not os.path.exists(settings_file):
                raise RuntimeError("Settings file not found — possible tampering")
            if os.path.getsize(settings_file) < 1000:
                raise RuntimeError("Settings file suspiciously small — possible tampering")

        return True
    except RuntimeError:
        raise
    except Exception as e:
        import logging
        logging.getLogger(__name__).critical(f"Settings integrity check failed: {str(e)}")
        raise RuntimeError(f"Settings integrity check failed: {str(e)}") from e

# EN: Run integrity check on import (no-op in pure .py dev if rules pass).
# UK: Запуск перевірки при імпорті.
_ = verify_settings_integrity()


# EN: Default admin username hint used by some setup flows (not Django's AUTH_USER_MODEL default).
# UK: Підказка логіна адміна для деяких сценаріїв налаштування — з credential.py / .env (DEFAULT_ADMIN_USERNAME).
DEFAULT_ADMIN_USERNAME = default_admin_username

# EN: Absolute path to the SecBoard package directory (parent of this settings module).
# UK: Абсолютний шлях до каталогу пакета SecBoard (батьківський для цього settings).
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# EN: Directory for rotating / file log handlers; created if missing.
# UK: Каталог для файлів логів; створюється, якщо немає.
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

# Security Settings
SECRET_KEY = secret_key
DEBUG = debug
PRODUCTION = not DEBUG

ALLOWED_HOSTS = allowed_hosts

# Application definition
# SecBoard Community Edition — Open Core (AGPL v3) + Dual License model.
# See LICENSING.md. A valid community or enterprise license key is required.
SECBOARD_COMMUNITY_EDITION = True
COMMUNITY_MAX_USERS_DEFAULT = 100

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',  # Added for sitemap generation
    'django_bootstrap5',
    'widget_tweaks',
    'tinymce',  # Replaced froala_editor with tinymce
    'colorfield',
    'django_datatables_view',
    'rest_framework',
    'app_conf',
    'app_study',
    'app_ai',
    'app_cabinet',
    'app_doc',
    'app_risk',
    'app_asset',
    'app_keycert',
    'django_celery_beat',
    'django_celery_results',
    'app_incident',
    'app_std',
    'app_access',
    'app_soc',
    'app_gophish',
    'app_gdpr',
    'app_compliance',
    'app_tprm',
    'app_cif',
    'app_integration',
    'mptt',
    'encrypted_model_fields',
    'corsheaders',
]

# Field encryption settings
FIELD_ENCRYPTION_KEY = os.environ.get(
    'FIELD_ENCRYPTION_KEY', 
    base64.urlsafe_b64encode(SECRET_KEY[:32].encode()).decode()
)

MIDDLEWARE = [
    'SecBoard.middleware.StatusCheckMiddleware',  # This must be first to intercept status check requests
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware - must be early
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'app_conf.license_middleware.SecureLicenseMiddleware',  # License validation middleware - CRITICAL: DO NOT REMOVE
    'SecBoard.middleware.SessionSecurityMiddleware',  # Enhanced session security
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'SecBoard.middleware.LoginSecurityMiddleware',  # Enhanced login security
    'SecBoard.middleware.AdminLoginRateLimitMiddleware',
    'app_cabinet.middleware.UserSessionMiddleware',
    'app_incident.middleware.MultipartFixMiddleware',
    'app_risk.logging_utils.AuditMiddleware',  # Risk Assessment audit logging
    'SecBoard.middleware.SecurityHeadersMiddleware',  # Fix JavaScript permissions policy
]

# EN: Ensures license middleware is present (anti-tamper).
# UK: Перевірка наявності license middleware у стеку.
def verify_license_middleware():
    """EN: Assert SecureLicenseMiddleware is in MIDDLEWARE. UK: Перевірка license middleware у MIDDLEWARE."""
    license_middleware = 'app_conf.license_middleware.SecureLicenseMiddleware'
    if license_middleware not in MIDDLEWARE:
        raise RuntimeError(
            "CRITICAL SECURITY ERROR: License middleware is missing from MIDDLEWARE! Possible tampering detected."
        )
    return True

# EN: Run middleware guard on import.
# UK: Запуск перевірки middleware.
_ = verify_license_middleware()

ROOT_URLCONF = 'SecBoard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            # Add app-specific template directories
            os.path.join(BASE_DIR, 'app_cabinet', 'templates'),
            os.path.join(BASE_DIR, 'app_risk', 'templates'),
            os.path.join(BASE_DIR, 'app_asset', 'templates'),
            os.path.join(BASE_DIR, 'app_access', 'templates'),
            os.path.join(BASE_DIR, 'app_incident', 'templates'),
            os.path.join(BASE_DIR, 'app_doc', 'templates'),
            os.path.join(BASE_DIR, 'app_keycert', 'templates'),
            os.path.join(BASE_DIR, 'app_std', 'templates'),
            os.path.join(BASE_DIR, 'app_study', 'templates'),
            os.path.join(BASE_DIR, 'app_conf', 'templates'),
            os.path.join(BASE_DIR, 'app_gophish', 'templates'),
            os.path.join(BASE_DIR, 'app_gdpr', 'templates'),
            os.path.join(BASE_DIR, 'app_tprm', 'templates'),
            os.path.join(BASE_DIR, 'app_cif', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'SecBoard.context_processors.menu_visibility',
                'app_cabinet.context_processors.cabinet_permissions',
                'app_cabinet.context_processors.header_tasks_count',
                'app_gophish.context_processors.gophish_permissions',
                'app_tprm.context_processors.tprm_permissions',
                'app_conf.context_processors.google_tags',
                'app_conf.context_processors.contact_settings',
                'app_conf.context_processors.site_settings',
                'app_integration.context_processors.footer_telegram_bot',
                'app_risk.context_processors.vulnerability_form_languages',
            ],
            'debug': DEBUG,
        },
    },
]

WSGI_APPLICATION = 'SecBoard.wsgi.application'

# Database configuration
DATABASES = database

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGES = [
    ('en', 'English'),
    ('uk', 'Українська'),
    ('ru', 'Русский'),
    ('de', 'Deutsch'),
]

LANGUAGE_CODE = 'en'
TIME_ZONE = timezone
USE_I18N = True
USE_L10N = True
USE_TZ = True
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = ' '
DECIMAL_SEPARATOR = ','

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Static files configuration
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# TinyMCE Configuration
TINYMCE_DEFAULT_CONFIG = {
    'height': 300,
    'width': '100%',
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'theme': 'silver',  # Updated theme name
    'plugins': '''
        advlist autolink lists link image charmap preview anchor
        searchreplace visualblocks code fullscreen
        insertdatetime media table paste code help wordcount
        visualchars nonbreaking template emoticons hr pagebreak
        directionality textpattern
    ''',
    'toolbar': '''
        undo redo | formatselect | fontselect fontsizeselect |
        bold italic underline strikethrough | forecolor backcolor |
        alignleft aligncenter alignright alignjustify |
        bullist numlist | outdent indent | blockquote |
        link unlink anchor | image media table | insertdatetime |
        charmap emoticons hr pagebreak | visualblocks visualchars |
        searchreplace | code fullscreen | preview | help
    ''',
    'toolbar_mode': 'sliding',
    'contextmenu': 'formats | link image table',
    'menubar': 'file edit view insert format tools table help',
    'menu': {
        'file': {'title': 'File', 'items': 'newdocument'},
        'edit': {'title': 'Edit', 'items': 'undo redo | cut copy paste | selectall | searchreplace'},
        'view': {'title': 'View', 'items': 'code | visualaid visualchars visualblocks | fullscreen preview'},
        'insert': {'title': 'Insert', 'items': 'image link media template | charmap emoticons hr | pagebreak nonbreaking anchor | insertdatetime'},
        'format': {'title': 'Format', 'items': 'bold italic underline strikethrough superscript subscript | formats blockformats fontformats fontsizes align | forecolor backcolor | removeformat'},
        'tools': {'title': 'Tools', 'items': 'wordcount'},
        'table': {'title': 'Table', 'items': 'inserttable | cell row column | tableprops deletetable'},
        'help': {'title': 'Help', 'items': 'help'}
    },
    'statusbar': True,
    'language': 'uk',
    'branding': False,
    'elementpath': True,
    'resize': True,
    'image_advtab': True,
    'table_toolbar': 'tableprops tabledelete | tableinsertrowbefore tableinsertrowafter tabledeleterow | tableinsertcolbefore tableinsertcolafter tabledeletecol',
    'table_appearance_options': False,
    'table_grid': False,
    'table_class_list': [
        {'title': 'None', 'value': ''},
        {'title': 'Table with borders', 'value': 'table table-bordered'},
        {'title': 'Striped table', 'value': 'table table-striped'}
    ],
    'content_style': """
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; font-size: 14px }
        .mce-content-body { padding: 10px; }
    """,
    'block_formats': 'Paragraph=p; Heading 1=h1; Heading 2=h2; Heading 3=h3; Heading 4=h4; Heading 5=h5; Heading 6=h6; Preformatted=pre; Blockquote=blockquote',
    'font_formats': 'Arial=arial,helvetica,sans-serif; Georgia=georgia,palatino; Times New Roman=times new roman,times; Courier New=courier new,courier',
    'fontsize_formats': '8pt 10pt 12pt 14pt 16pt 18pt 24pt 36pt 48pt',
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security Settings
ADMIN_LOGIN_ATTEMPT_LIMIT = 5
ADMIN_LOGIN_ATTEMPT_TIMEOUT = 300  # 5 minutes

# Enhanced Login Security Settings
IP_LOGIN_ATTEMPT_LIMIT = 10  # Max attempts per IP before lockout
IP_LOGIN_LOCKOUT_DURATION = 3600  # 1 hour IP lockout
USER_LOGIN_ATTEMPT_LIMIT = 5  # Max attempts per user before lockout
USER_LOGIN_LOCKOUT_DURATION = 1800  # 30 minutes user lockout
LOGIN_ATTEMPT_WINDOW = 3600  # 1 hour window for counting attempts
LOGIN_CAPTCHA_THRESHOLD = 3  # Show CAPTCHA after this many failed attempts
LOGIN_PROGRESSIVE_DELAY = True  # Enable progressive delays

# Password Security
PASSWORD_RESET_TIMEOUT_DAYS = 1  # Password reset links expire in 1 day
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',  # Default Django hasher
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    # 'django.contrib.auth.hashers.Argon2PasswordHasher',  # Requires: pip install argon2-cffi
]

# Session Security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = True

# Enhanced Session Security Settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Database-backed sessions
SESSION_COOKIE_NAME = 'secboard_sessionid'  # Custom cookie name to obscure framework
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_DOMAIN = None  # Let Django handle domain automatically
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'

# Session timeout and regeneration settings
SESSION_COOKIE_AGE = 3600  # 1 hour session timeout
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Session expires when browser closes
SESSION_SAVE_EVERY_REQUEST = True  # Update session on every request
SESSION_COOKIE_HTTPONLY = True  # Prevent XSS access to session cookies
SESSION_COOKIE_SAMESITE = 'Strict'  # Enhanced CSRF protection

# Session security enhancements
SESSION_REGENERATE_ON_LOGIN = True  # Custom setting to regenerate session ID on login
SESSION_INVALIDATE_ON_PASSWORD_CHANGE = True  # Invalidate all sessions on password change
SESSION_TRACK_IP_CHANGES = True  # Track IP address changes within sessions
SESSION_MAX_CONCURRENT_SESSIONS = 3  # Maximum concurrent sessions per user

# Google reCAPTCHA v3 settings
RECAPTCHA_PUBLIC_KEY = recaptcha_public_key
RECAPTCHA_PRIVATE_KEY = recaptcha_private_key
RECAPTCHA_USE_SSL = True
RECAPTCHA_REQUIRED_SCORE = 0.5  # Minimum score for v3 (0.0 to 1.0, higher is more human-like)

# Development Settings
if DEBUG:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_PROXY_SSL_HEADER = None  # Disable SSL header check in development
    SECURE_HSTS_SECONDS = 0  # Disable HSTS in development
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Production Security Settings
if PRODUCTION:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True  # HTTPS-only cookies
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Production Session Settings
    SESSION_COOKIE_SECURE = True  # HTTPS-only session cookies
    SESSION_COOKIE_AGE = 2700  # 45 minutes for production (shorter)
    SESSION_COOKIE_SAMESITE = 'Strict'  # Strict SameSite in production
else:
    # Development Settings
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False  # Allow HTTP in development
    CSRF_COOKIE_SECURE = False
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    
    # Development Session Settings (more lenient)
    SESSION_COOKIE_AGE = 7200  # 2 hours for development
    SESSION_COOKIE_SAMESITE = 'Lax'  # Lax SameSite for development ease

# SSL and Security Headers
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_REFERRER_POLICY = 'same-origin'

# CSRF — platform defaults; trusted origins from credential.py / .env
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = True
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_TRUSTED_ORIGINS = csrf_trusted_origins

# Public base URL for generating absolute URLs in emails
PUBLIC_BASE_URL = public_base_url

# CORS — platform defaults; allowed origins/patterns from credential.py / .env
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOWED_ORIGINS = cors_allowed_origins
CORS_ALLOWED_ORIGIN_REGEXES = cors_allowed_origin_regexes

# Celery Configuration
# Redis Settings
REDIS_HOST = redis_host
REDIS_PORT = redis_port
REDIS_DB = redis_db


# Ensure logs directory exists
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

GEOIP_PATH = os.path.join(BASE_DIR, 'geoip')
GEOIP_CITY = os.path.join(GEOIP_PATH, 'GeoLite2-City.mmdb')

# Create directory if it doesn't exist
if not os.path.exists(GEOIP_PATH):
    os.makedirs(GEOIP_PATH)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '[{asctime}] {levelname} {name} {module}.{funcName}:{lineno} | {message}',
            'style': '{',
        },
        'risk_assessment': {
            'format': '[{asctime}] RISK_ASSESSMENT {levelname} | {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'console_warnings_only': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'level': 'WARNING',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'debug.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'risk_assessment_file': {
            'class': 'concurrent_log_handler.ConcurrentRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'risk_assessment.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 10,
            'formatter': 'risk_assessment',
            'encoding': 'utf-8',
        },
        'risk_assessment_actions': {
            'class': 'concurrent_log_handler.ConcurrentRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'risk_assessment_actions.log'),
            'maxBytes': 50 * 1024 * 1024,  # 50MB
            'backupCount': 20,
            'formatter': 'detailed',
            'encoding': 'utf-8',
        },
        'risk_assessment_errors': {
            'class': 'concurrent_log_handler.ConcurrentRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'risk_assessment_errors.log'),
            'maxBytes': 20 * 1024 * 1024,  # 20MB
            'backupCount': 15,
            'formatter': 'detailed',
            'encoding': 'utf-8',
        },

    },
    'loggers': {
        'app_access': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'app_risk': {
            'handlers': ['console', 'risk_assessment_file', 'risk_assessment_actions'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'app_risk.user_actions': {
            'handlers': ['risk_assessment_actions'],
            'level': 'INFO',
            'propagate': False,
        },
        'app_risk.errors': {
            'handlers': ['console', 'risk_assessment_errors'],
            'level': 'ERROR',
            'propagate': False,
        },
        'app_risk.security': {
            'handlers': ['console', 'risk_assessment_errors'],
            'level': 'WARNING',
            'propagate': False,
        },
        'app_gophish': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


def setup_logging():
    import atexit
    import logging
    from logging.handlers import TimedRotatingFileHandler

    def cleanup_logs():
        """Clean up and close all log handlers properly"""
        for handler in logging.getLogger().handlers:
            if isinstance(handler, TimedRotatingFileHandler):
                handler.close()

    # Register cleanup function
    atexit.register(cleanup_logs)


# Function to clean up old log files
def cleanup_old_logs(max_days=30):
    """Remove log files older than max_days"""
    import glob
    import os
    from datetime import datetime, timedelta

    now = datetime.now()
    max_age = timedelta(days=max_days)

    # Get all log files
    log_patterns = [
        os.path.join(LOGS_DIR, '*.log'),
        os.path.join(LOGS_DIR, '*.log.*')
    ]

    for pattern in log_patterns:
        for log_file in glob.glob(pattern):
            try:
                file_modified = datetime.fromtimestamp(os.path.getmtime(log_file))
                if now - file_modified > max_age:
                    os.remove(log_file)
            except OSError as e:
                print(f"Error removing old log file {log_file}: {e}")


# Call setup functions
setup_logging()
if not DEBUG:
    cleanup_old_logs()

MPTT_ADMIN_LEVEL_INDENT = 20

# Додамо налаштування для MPTT
MPTT_APPS = {
    'app_access': {
        'AccessFunctionIS': {
            'level_indicator': '---',
        },
    },
}

# Email Configuration
# Email settings are managed through Django Admin:
# - Home › config › Mail Servers (configure SMTP servers)
# - Home › config › Mail Accounts (configure email accounts)
# 
# The system will automatically use the active MailAccount for sending emails
# in functions like first_login, password reset, etc.

# Minimal Django email settings (required for Django to work)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Use SMTP backend
DEFAULT_FROM_EMAIL = default_from_email

# Site settings for email notifications
SITE_DOMAIN = site_domain
SITE_PROTOCOL = site_protocol

# Authentication settings
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Try Django password first, then AD/LDAP per company (first successful bind = auto provisioning)
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'app_cabinet.backends.CabinetADBackend',
]

# Webhook Encryption Settings
WEBHOOK_ENCRYPTION_KEY = webhook_encryption_key

# Development settings to reduce console warnings
if DEBUG:
    # Allow insecure origins for development
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None
    SECURE_REFERRER_POLICY = None

# ============================================================================
# License Management Settings
# Налаштування системи ліцензування
# ============================================================================

# URL центрального сервера ліцензій
LICENSE_SERVER_URL = 'https://license.secboard.online/api/v1/'

# Timeout для запитів до сервера ліцензій (секунди)
LICENSE_SERVER_TIMEOUT = 10

# Інтервал перевірки ліцензії (секунди)
# Middleware кешує результат валідації на цей період
LICENSE_CHECK_INTERVAL = 300  # 5 хвилин

# Offline grace period (дні)
# Скільки днів платформа може працювати без зв'язку з сервером ліцензій
LICENSE_OFFLINE_GRACE_PERIOD = 7  # 7 днів

# Інтервал heartbeat запитів до сервера (секунди)
LICENSE_HEARTBEAT_INTERVAL = 3600  # 1 година

# Максимальна кількість невдалих валідацій перед блокуванням ліцензії
LICENSE_MAX_FAILED_VALIDATIONS = 10




