# Generated by Django 5.2.8 on 2026-06-24 09:44

import app_asset.models
import django.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=False, verbose_name='Has access to Information Assets')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Can edit Information Assets')),
                ('manage_adm_own', models.BooleanField(default=False, verbose_name='Can edit Administrator and Owner Assets')),
                ('manage_types', models.BooleanField(default=False, verbose_name='Can edit Types Assets')),
                ('can_view_software_register', models.BooleanField(default=False, help_text='Can open and view the Software Register page', verbose_name='Can view Software Register')),
                ('can_edit_software_register', models.BooleanField(default=False, help_text='Can add, edit and delete entries in Software Register', verbose_name='Can edit Software Register')),
                ('can_view_external_media_register', models.BooleanField(default=False, help_text='Can open and view the External Media Register page', verbose_name='Can view External Media Register')),
                ('can_edit_external_media_register', models.BooleanField(default=False, help_text='Can add, edit and delete entries in External Media Register', verbose_name='Can edit External Media Register')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Access to Assets',
                'verbose_name_plural': 'Access to Assets',
            },
        ),
        migrations.CreateModel(
            name='AssetAdministrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Asset Administrator',
                'verbose_name_plural': 'Asset Administrators',
            },
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Asset group name, default: English (En). E.g. Information Systems, Databases. For other languages use Translations inline.', max_length=100, verbose_name='Group Name')),
                ('name_local', models.CharField(blank=True, help_text='Group name in local language (use Translations inline for per-country names)', max_length=100, verbose_name='Local Name')),
                ('code', models.CharField(help_text='Unique code (e.g., info_systems, databases)', max_length=50, unique=True, verbose_name='Group Code')),
                ('abbreviation', models.CharField(help_text='Short abbreviation for the group', max_length=10, unique=True, verbose_name='Abbreviation')),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for display', max_length=7, verbose_name='Color')),
                ('display_order', models.IntegerField(default=0, help_text='Order for display in lists (lower numbers first)', verbose_name='Display Order')),
                ('description', models.TextField(blank=True, help_text='Description of this asset group, default: English (En). For other languages use Translations inline.', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('show_in_software_register', models.BooleanField(default=True, help_text='If checked, this group will be available in the Group/Type selector of the Software Register.', verbose_name='Show in Software Register')),
                ('show_in_external_media_register', models.BooleanField(default=True, help_text='If checked, this group will be available in the Group/Type selector of the External Media Register.', verbose_name='Show in External Media Register')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Asset Group',
                'verbose_name_plural': 'Asset Groups',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetGroupTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(help_text="Group name in country's language", max_length=100, verbose_name='Local Name')),
                ('description', models.TextField(blank=True, help_text="Description in country's language", verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Asset Group Translation',
                'verbose_name_plural': 'Asset Group Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='AssetGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'Asset Guide',
                'verbose_name_plural': 'Asset Guides',
            },
        ),
        migrations.CreateModel(
            name='AssetGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Asset Guide Translation',
                'verbose_name_plural': 'Asset Guide Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('action', models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('deleted', 'Deleted'), ('owners_changed', 'Owners Changed'), ('administrators_changed', 'Administrators Changed'), ('cia_changed', 'CIA Changed'), ('confidentiality_changed', 'Confidentiality Changed'), ('integrity_changed', 'Integrity Changed'), ('availability_changed', 'Availability Changed')], max_length=50, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Changes')),
            ],
            options={
                'verbose_name': 'Asset History',
                'verbose_name_plural': 'Asset History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AssetOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Asset Owner',
                'verbose_name_plural': 'Asset Owners',
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Asset type name, default: English (En). E.g. Server, Database, Document. For other languages use Translations inline.', max_length=100, verbose_name='Type Name')),
                ('name_local', models.CharField(blank=True, help_text='Type name in local language (use Translations inline for per-country names)', max_length=100, verbose_name='Local Name')),
                ('code', models.CharField(help_text='Unique code (e.g., server, database, document)', max_length=50, verbose_name='Type Code')),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for display', max_length=7, verbose_name='Color')),
                ('display_order', models.IntegerField(default=0, help_text='Order for display in lists (lower numbers first)', verbose_name='Display Order')),
                ('description', models.TextField(blank=True, help_text='Description of this asset type, default: English (En). For other languages use Translations inline.', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Asset Type',
                'verbose_name_plural': 'Asset Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(help_text="Type name in country's language", max_length=100, verbose_name='Local Name')),
                ('description', models.TextField(blank=True, help_text="Description in country's language", verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Asset Type Translation',
                'verbose_name_plural': 'Asset Type Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='CriticalityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Criticality level name, default: English (En). E.g. Low, Medium, High. For other languages use Translations inline.', max_length=50, verbose_name='Level Name')),
                ('name_local', models.CharField(blank=True, help_text='Level name in local language (use Translations inline for per-country names)', max_length=50, verbose_name='Local Name')),
                ('code', models.CharField(help_text='Code unique per company (e.g., low, medium, high)', max_length=50, verbose_name='Level Code')),
                ('cost', models.IntegerField(help_text='Value from 0 to 10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Cost')),
                ('color', models.CharField(default='#000000', help_text='Color in HEX format, e.g. #FF0000', max_length=7, verbose_name='Color')),
                ('display_order', models.IntegerField(default=0, help_text='Order for display in lists (lower numbers first)', verbose_name='Display Order')),
                ('description_confid', models.TextField(blank=True, help_text='Confidentiality description, default: English (En). For other languages use Translations inline.', verbose_name='Confidentiality Description')),
                ('description_integ', models.TextField(blank=True, help_text='Integrity description, default: English (En). For other languages use Translations inline.', verbose_name='Integrity Description')),
                ('description_avail', models.TextField(blank=True, help_text='Availability description, default: English (En). For other languages use Translations inline.', verbose_name='Availability Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Criticality Level',
                'verbose_name_plural': 'Criticality Levels',
                'ordering': ['display_order', 'cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CriticalityLevelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(help_text="Level name in country's language", max_length=50, verbose_name='Local Name')),
                ('description_confid', models.TextField(blank=True, help_text="Confidentiality description in country's language", verbose_name='Confidentiality Description')),
                ('description_integ', models.TextField(blank=True, help_text="Integrity description in country's language", verbose_name='Integrity Description')),
                ('description_avail', models.TextField(blank=True, help_text="Availability description in country's language", verbose_name='Availability Description')),
            ],
            options={
                'verbose_name': 'Criticality Level Translation',
                'verbose_name_plural': 'Criticality Level Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalMediaGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'External Media Guide',
                'verbose_name_plural': 'External Media Guides',
            },
        ),
        migrations.CreateModel(
            name='ExternalMediaGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
            ],
            options={
                'verbose_name': 'External Media Guide Translation',
                'verbose_name_plural': 'External Media Guide Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalMediaRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or description of the media', max_length=255, verbose_name='Name')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Serial number')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('actualization_date', models.DateTimeField(blank=True, help_text='Date when the entry was last actualized by owner', null=True, verbose_name='Actualization date')),
                ('marked_no_longer_actual_at', models.DateTimeField(blank=True, help_text='Date when the entry was marked as no longer actual by owner', null=True, verbose_name='Marked no longer actual at')),
                ('marked_no_longer_comment', models.TextField(blank=True, default='', help_text='Optional comment when the entry was marked as no longer actual', verbose_name='Marked no longer actual comment')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'External Media Register Entry',
                'verbose_name_plural': 'External Media Register',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalMediaRegisterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=app_asset.models.external_media_file_upload_to, verbose_name='File')),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Hash (SHA256)')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Label')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalMediaRegisterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(blank=True, max_length=255, verbose_name='Entry name')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('action', models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('deleted', 'Deleted')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExternalMediaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Status Name')),
                ('name_local', models.CharField(blank=True, max_length=100, verbose_name='Local Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Color')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'External Media Status',
                'verbose_name_plural': 'External Media Statuses',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalMediaStatusTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(max_length=100, verbose_name='Local Name')),
            ],
        ),
        migrations.CreateModel(
            name='InformationAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Asset ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Registration Date')),
                ('deletion_date', models.DateField(blank=True, null=True, verbose_name='Deletion Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('access_manage', models.BooleanField(default=False, help_text='Indicates if this asset can be used in access management', verbose_name='Access Manage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('actualization_date', models.DateTimeField(blank=True, help_text='Date when the asset was last actualized by owner', null=True, verbose_name='Actualization Date')),
                ('marked_no_longer_actual_at', models.DateTimeField(blank=True, help_text='Date when the asset was marked as no longer actual by owner', null=True, verbose_name='Marked no longer actual at')),
                ('marked_no_longer_comment', models.TextField(blank=True, help_text='Optional comment when the asset was marked as no longer actual', verbose_name='Marked no longer actual comment')),
            ],
            options={
                'verbose_name': 'Information Asset',
                'verbose_name_plural': 'Information Assets',
                'ordering': ['asset_id'],
            },
        ),
        migrations.CreateModel(
            name='InformationAssetSoftwareSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_version', models.CharField(blank=True, default='', max_length=100, verbose_name='Selected Version')),
                ('selected_license_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Selected License Quantity')),
            ],
            options={
                'verbose_name': 'Information Asset Software Selection',
                'verbose_name_plural': 'Information Asset Software Selections',
            },
        ),
        migrations.CreateModel(
            name='SoftwareGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'Software Guide',
                'verbose_name_plural': 'Software Guides',
            },
        ),
        migrations.CreateModel(
            name='SoftwareGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Software Guide Translation',
                'verbose_name_plural': 'Software Guide Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Default: English (En). E.g. Subscription, Perpetual.', max_length=100, verbose_name='License Type Name')),
                ('name_local', models.CharField(blank=True, max_length=100, verbose_name='Local Name')),
                ('code', models.CharField(help_text='Unique code (e.g., subscription, perpetual)', max_length=50, unique=True, verbose_name='Code')),
                ('color', models.CharField(default='#6c757d', help_text='Hex color for display', max_length=7, verbose_name='Color')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Software License Type',
                'verbose_name_plural': 'Software License Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicenseTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(max_length=100, verbose_name='Local Name')),
            ],
            options={
                'verbose_name': 'Software License Type Translation',
                'verbose_name_plural': 'Software License Type Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the software product', max_length=255, verbose_name='Software Name')),
                ('description', models.TextField(blank=True, help_text='Optional description or justification', verbose_name='Description')),
                ('version_pattern', models.CharField(blank=True, help_text='Optional version pattern (e.g. 1.2.*, any)', max_length=100, verbose_name='Version Pattern')),
                ('manufacturer', models.CharField(blank=True, help_text='Vendor / manufacturer', max_length=255, verbose_name='Manufacturer')),
                ('url', models.URLField(blank=True, help_text='Product or vendor URL', max_length=500, verbose_name='URL')),
                ('license_type', models.CharField(blank=True, help_text='Type of license', max_length=100, verbose_name='License Type')),
                ('license_quantity', models.PositiveIntegerField(blank=True, help_text='Number of licenses', null=True, verbose_name='License Quantity')),
                ('license_valid_until', models.DateField(blank=True, help_text='License expiry date', null=True, verbose_name='License Valid Until')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('display_order', models.IntegerField(default=0, help_text='Order for display (lower numbers first)', verbose_name='Display Order')),
                ('actualization_date', models.DateTimeField(blank=True, help_text='Date when the entry was last actualized by owner', null=True, verbose_name='Actualization date')),
                ('marked_no_longer_actual_at', models.DateTimeField(blank=True, help_text='Date when the entry was marked as no longer actual by owner', null=True, verbose_name='Marked no longer actual at')),
                ('marked_no_longer_comment', models.TextField(blank=True, default='', help_text='Optional comment when the entry was marked as no longer actual', verbose_name='Marked no longer actual comment')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Software Register Entry',
                'verbose_name_plural': 'Software Register (Allowed/Forbidden)',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareRegisterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload one or more files (e.g. installers, licenses)', max_length=500, upload_to=app_asset.models.software_register_file_upload_to, verbose_name='File')),
                ('file_hash', models.CharField(blank=True, editable=False, help_text='SHA256 hash of the file content', max_length=64, verbose_name='Hash (SHA256)')),
                ('label', models.CharField(blank=True, help_text='Optional display name for the file', max_length=255, verbose_name='Label')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
            ],
            options={
                'verbose_name': 'Software Register File',
                'verbose_name_plural': 'Software Register Files',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareRegisterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(blank=True, help_text='Stored when entry is deleted', max_length=255, verbose_name='Entry name')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('action', models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('deleted', 'Deleted')], max_length=50, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Changes')),
            ],
            options={
                'verbose_name': 'Software Register History',
                'verbose_name_plural': 'Software Register History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Default: English (En). E.g. Allowed, Forbidden.', max_length=100, verbose_name='Status Name')),
                ('name_local', models.CharField(blank=True, max_length=100, verbose_name='Local Name')),
                ('code', models.CharField(help_text='Unique code (e.g., allowed, forbidden)', max_length=50, unique=True, verbose_name='Code')),
                ('color', models.CharField(default='#6c757d', help_text='Hex color for display', max_length=7, verbose_name='Color')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Software Status',
                'verbose_name_plural': 'Software Statuses',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareStatusTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(max_length=100, verbose_name='Local Name')),
            ],
            options={
                'verbose_name': 'Software Status Translation',
                'verbose_name_plural': 'Software Status Translations',
                'ordering': ['country__name'],
            },
        ),
    ]
