# Generated by Django 5.2.8 on 2026-06-24 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_asset', '0001_initial'),
        ('app_cabinet', '0001_initial'),
        ('app_conf', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessassets',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='access_assets', to='app_conf.company', verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='accessassets',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='assetadministrator',
            name='cabinet_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cabinet.cabinetuser', verbose_name='Cabinet User'),
        ),
        migrations.AddField(
            model_name='assetadministrator',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='assetgrouptranslation',
            name='asset_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_asset.assetgroup', verbose_name='Asset Group'),
        ),
        migrations.AddField(
            model_name='assetgrouptranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_group_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='assetguidetranslation',
            name='asset_guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_asset.assetguide', verbose_name='Asset Guide'),
        ),
        migrations.AddField(
            model_name='assetguidetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_guide_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='assethistory',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Action By'),
        ),
        migrations.AddField(
            model_name='assetowner',
            name='cabinet_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cabinet.cabinetuser', verbose_name='Cabinet User'),
        ),
        migrations.AddField(
            model_name='assetowner',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_types', to='app_asset.assetgroup', verbose_name='Asset Group'),
        ),
        migrations.AddField(
            model_name='assettypetranslation',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_asset.assettype', verbose_name='Asset Type'),
        ),
        migrations.AddField(
            model_name='assettypetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_type_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='criticalitylevel',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Leave empty for organization-wide level', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criticality_levels', to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='criticalityleveltranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criticality_level_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='criticalityleveltranslation',
            name='criticality_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_asset.criticalitylevel', verbose_name='Criticality Level'),
        ),
        migrations.AddField(
            model_name='externalmediaguidetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_media_guide_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='externalmediaguidetranslation',
            name='external_media_guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_asset.externalmediaguide', verbose_name='External Media Guide'),
        ),
        migrations.AddField(
            model_name='externalmediaregister',
            name='actualized_by',
            field=models.ForeignKey(blank=True, help_text='User who actualized this external media entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualized_external_media_entries', to=settings.AUTH_USER_MODEL, verbose_name='Actualized by'),
        ),
        migrations.AddField(
            model_name='externalmediaregister',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_media_register_entries', to='app_asset.assettype', verbose_name='Asset Type'),
        ),
        migrations.AddField(
            model_name='externalmediaregister',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_external_media', to='app_asset.criticalitylevel', verbose_name='Availability'),
        ),
        migrations.AddField(
            model_name='externalmediaregister',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_media_register_entries', to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='externalmediaregister',
            name='confidentiality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confidentiality_external_media', to='app_asset.criticalitylevel', verbose_name='Confidentiality'),
        ),
        migrations.AddField(
            model_name='externalmediaregister',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_media_register_entries', to='app_asset.assetgroup', verbose_name='Asset Group'),
        ),
        migrations.AddField(
            model_name='externalmediaregister',
            name='integrity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrity_external_media', to='app_asset.criticalitylevel', verbose_name='Integrity'),
        ),
        migrations.AddField(
            model_name='externalmediaregister',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text='Owners from Cabinet users (same as Assets Register)', related_name='external_media_register_entries', to='app_asset.assetowner', verbose_name='Owners'),
        ),
        migrations.AddField(
            model_name='externalmediaregisterfile',
            name='external_media_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app_asset.externalmediaregister'),
        ),
        migrations.AddField(
            model_name='externalmediaregisterhistory',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalmediaregisterhistory',
            name='external_media_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='app_asset.externalmediaregister'),
        ),
        migrations.AddField(
            model_name='externalmediaregister',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_media_entries', to='app_asset.externalmediastatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='externalmediastatustranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_media_status_translations', to='app_conf.country'),
        ),
        migrations.AddField(
            model_name='externalmediastatustranslation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_asset.externalmediastatus'),
        ),
        migrations.AddField(
            model_name='informationasset',
            name='actualized_by',
            field=models.ForeignKey(blank=True, help_text='User who actualized this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualized_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informationasset',
            name='administrators',
            field=models.ManyToManyField(related_name='administered_assets', to='app_asset.assetadministrator', verbose_name='Administrators'),
        ),
        migrations.AddField(
            model_name='informationasset',
            name='asset_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_asset.assettype', verbose_name='Asset Type'),
        ),
        migrations.AddField(
            model_name='informationasset',
            name='availability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_assets', to='app_asset.criticalitylevel', verbose_name='Availability'),
        ),
        migrations.AddField(
            model_name='informationasset',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='informationasset',
            name='confidentiality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confidentiality_assets', to='app_asset.criticalitylevel', verbose_name='Confidentiality'),
        ),
        migrations.AddField(
            model_name='informationasset',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_asset.assetgroup', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='informationasset',
            name='integrity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrity_assets', to='app_asset.criticalitylevel', verbose_name='Integrity'),
        ),
        migrations.AddField(
            model_name='informationasset',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informationasset',
            name='owners',
            field=models.ManyToManyField(related_name='owned_assets', to='app_asset.assetowner', verbose_name='Owners'),
        ),
        migrations.AddField(
            model_name='assethistory',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app_asset.informationasset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='informationassetsoftwareselection',
            name='information_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_selections', to='app_asset.informationasset', verbose_name='Information Asset'),
        ),
        migrations.AddField(
            model_name='softwareguidetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_guide_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='softwareguidetranslation',
            name='software_guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_asset.softwareguide', verbose_name='Software Guide'),
        ),
        migrations.AddField(
            model_name='softwarelicensetypetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_license_type_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='softwarelicensetypetranslation',
            name='software_license_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_asset.softwarelicensetype', verbose_name='Software License Type'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='actualized_by',
            field=models.ForeignKey(blank=True, help_text='User who actualized this software entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualized_software_entries', to=settings.AUTH_USER_MODEL, verbose_name='Actualized by'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_entries', to='app_asset.assettype', verbose_name='Asset Type'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_software', to='app_asset.criticalitylevel', verbose_name='Availability'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Leave empty for organization-wide rule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='software_register_entries', to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='confidentiality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confidentiality_software', to='app_asset.criticalitylevel', verbose_name='Confidentiality'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_entries', to='app_asset.assetgroup', verbose_name='Asset Group'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='integrity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrity_software', to='app_asset.criticalitylevel', verbose_name='Integrity'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text='Owners from Cabinet users (same as Assets Register)', related_name='software_register_entries', to='app_asset.assetowner', verbose_name='Owners'),
        ),
        migrations.AddField(
            model_name='informationassetsoftwareselection',
            name='software_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_selections', to='app_asset.softwareregister', verbose_name='Software Register Entry'),
        ),
        migrations.AddField(
            model_name='informationasset',
            name='software_entries',
            field=models.ManyToManyField(blank=True, help_text='Software from Software Register linked to this asset', related_name='information_assets', to='app_asset.softwareregister', verbose_name='Software Register Entries'),
        ),
        migrations.AddField(
            model_name='softwareregisterfile',
            name='software_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app_asset.softwareregister', verbose_name='Software Register Entry'),
        ),
        migrations.AddField(
            model_name='softwareregisterhistory',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Action By'),
        ),
        migrations.AddField(
            model_name='softwareregisterhistory',
            name='software_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='app_asset.softwareregister', verbose_name='Software Register Entry'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='status',
            field=models.ForeignKey(help_text='Allowed, Forbidden, etc.', on_delete=django.db.models.deletion.PROTECT, related_name='software_entries', to='app_asset.softwarestatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='softwarestatustranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_status_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='softwarestatustranslation',
            name='software_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_asset.softwarestatus', verbose_name='Software Status'),
        ),
        migrations.AlterUniqueTogether(
            name='assetadministrator',
            unique_together={('cabinet_user', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='assetgrouptranslation',
            unique_together={('asset_group', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='assetguidetranslation',
            unique_together={('asset_guide', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='assetowner',
            unique_together={('cabinet_user', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='assettype',
            unique_together={('code', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='assettypetranslation',
            unique_together={('asset_type', 'country')},
        ),
        migrations.AddConstraint(
            model_name='criticalitylevel',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='app_asset_critlevel_company_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='criticalityleveltranslation',
            constraint=models.UniqueConstraint(fields=('criticality_level', 'country'), name='app_asset_critleveltrans_cl_country_uniq'),
        ),
        migrations.AlterUniqueTogether(
            name='externalmediaguidetranslation',
            unique_together={('external_media_guide', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='externalmediastatustranslation',
            unique_together={('status', 'country')},
        ),
        migrations.AddIndex(
            model_name='assethistory',
            index=models.Index(fields=['asset', '-timestamp'], name='app_asset_a_asset_i_042d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='assethistory',
            index=models.Index(fields=['action'], name='app_asset_a_action_9cc173_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='softwareguidetranslation',
            unique_together={('software_guide', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='softwarelicensetypetranslation',
            unique_together={('software_license_type', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='informationassetsoftwareselection',
            unique_together={('information_asset', 'software_register')},
        ),
        migrations.AlterUniqueTogether(
            name='softwarestatustranslation',
            unique_together={('software_status', 'country')},
        ),
    ]
