# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0002_initial'),
        ('app_conf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'Software Guide',
                'verbose_name_plural': 'Software Guides',
            },
        ),
        migrations.CreateModel(
            name='SoftwareGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_guide_translations', to='app_conf.country', verbose_name='Country')),
                ('software_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_asset.softwareguide', verbose_name='Software Guide')),
            ],
            options={
                'verbose_name': 'Software Guide Translation',
                'verbose_name_plural': 'Software Guide Translations',
                'ordering': ['country__name'],
                'unique_together': {('software_guide', 'country')},
            },
        ),
    ]
