# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalitylevel',
            name='description_avail',
            field=models.TextField(blank=True, help_text='Availability description, default: English (En). For other languages use Translations inline.', verbose_name='Availability Description'),
        ),
        migrations.AddField(
            model_name='criticalitylevel',
            name='description_confid',
            field=models.TextField(blank=True, help_text='Confidentiality description, default: English (En). For other languages use Translations inline.', verbose_name='Confidentiality Description'),
        ),
        migrations.AddField(
            model_name='criticalitylevel',
            name='description_integ',
            field=models.TextField(blank=True, help_text='Integrity description, default: English (En). For other languages use Translations inline.', verbose_name='Integrity Description'),
        ),
    ]
