# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0002_initial'),
        ('app_conf', '0002_add_demo_credentials_to_site_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the software product', max_length=255, verbose_name='Software Name')),
                ('status', models.CharField(choices=[('allowed', 'Allowed'), ('forbidden', 'Forbidden')], help_text='Allowed or forbidden', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, help_text='Optional description or justification', verbose_name='Description')),
                ('version_pattern', models.CharField(blank=True, help_text='Optional version pattern (e.g. 1.2.*, any)', max_length=100, verbose_name='Version Pattern')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('display_order', models.IntegerField(default=0, help_text='Order for display (lower numbers first)', verbose_name='Display Order')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('company', models.ForeignKey(blank=True, help_text='Leave empty for organization-wide rule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='software_register_entries', to='app_conf.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Software Register Entry',
                'verbose_name_plural': 'Software Register (Allowed/Forbidden)',
                'ordering': ['display_order', 'status', 'name'],
            },
        ),
    ]
