# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0003_informationasset_actualization_and_marked_no_longer'),
        ('auth', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationasset',
            name='actualized_by',
            field=models.ForeignKey(blank=True, help_text='User who actualized this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualized_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
