# Generated by Django 5.2.8 on 2026-03-16 15:01

import django.db.models.deletion
from django.db import migrations, models


def create_software_statuses_and_migrate(apps, schema_editor):
    SoftwareStatus = apps.get_model('app_asset', 'SoftwareStatus')
    SoftwareRegister = apps.get_model('app_asset', 'SoftwareRegister')
    allowed, _ = SoftwareStatus.objects.get_or_create(
        code='allowed',
        defaults={'name': 'Allowed', 'display_order': 0, 'color': '#198754'}
    )
    forbidden, _ = SoftwareStatus.objects.get_or_create(
        code='forbidden',
        defaults={'name': 'Forbidden', 'display_order': 1, 'color': '#dc3545'}
    )
    for row in SoftwareRegister.objects.all():
        if hasattr(row, 'status') and isinstance(getattr(row, 'status', None), str):
            row.status_new_id = forbidden.id if (row.status or '').lower() == 'forbidden' else allowed.id
            row.save(update_fields=['status_new'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0003_software_register'),
        ('app_conf', '0002_add_demo_credentials_to_site_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Default: English (En). E.g. Operating System, Office Suite, Antivirus.', max_length=100, verbose_name='Category Name')),
                ('name_local', models.CharField(blank=True, help_text='Use Translations inline for per-country names.', max_length=100, verbose_name='Local Name')),
                ('code', models.CharField(help_text='Unique code (e.g., os, office, antivirus)', max_length=50, unique=True, verbose_name='Code')),
                ('color', models.CharField(default='#007bff', help_text='Hex color for display', max_length=7, verbose_name='Color')),
                ('display_order', models.IntegerField(default=0, help_text='Order in lists (lower first)', verbose_name='Display Order')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Software Category',
                'verbose_name_plural': 'Software Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Default: English (En). E.g. Allowed, Forbidden.', max_length=100, verbose_name='Status Name')),
                ('name_local', models.CharField(blank=True, max_length=100, verbose_name='Local Name')),
                ('code', models.CharField(help_text='Unique code (e.g., allowed, forbidden)', max_length=50, unique=True, verbose_name='Code')),
                ('color', models.CharField(default='#6c757d', help_text='Hex color for display', max_length=7, verbose_name='Color')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Software Status',
                'verbose_name_plural': 'Software Statuses',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='softwareregister',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Software Register Entry', 'verbose_name_plural': 'Software Register (Allowed/Forbidden)'},
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='license_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Number of licenses', null=True, verbose_name='License Quantity'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='license_type',
            field=models.CharField(blank=True, help_text='Type of license', max_length=100, verbose_name='License Type'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='license_valid_until',
            field=models.DateField(blank=True, help_text='License expiry date', null=True, verbose_name='License Valid Until'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Vendor / manufacturer', max_length=255, verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='url',
            field=models.URLField(blank=True, help_text='Product or vendor URL', max_length=500, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='category',
            field=models.ForeignKey(blank=True, help_text='e.g. Operating System, Office Suite, Antivirus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_entries', to='app_asset.softwarecategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='status_new',
            field=models.ForeignKey(blank=True, help_text='Allowed, Forbidden, etc.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app_asset.softwarestatus', verbose_name='Status'),
        ),
        migrations.RunPython(create_software_statuses_and_migrate, noop),
        migrations.RemoveField(
            model_name='softwareregister',
            name='status',
        ),
        migrations.RenameField(
            model_name='softwareregister',
            old_name='status_new',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='softwareregister',
            name='status',
            field=models.ForeignKey(help_text='Allowed, Forbidden, etc.', on_delete=django.db.models.deletion.PROTECT, related_name='software_entries', to='app_asset.softwarestatus', verbose_name='Status', null=False),
        ),
        migrations.CreateModel(
            name='SoftwareCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(help_text="Category name in country's language", max_length=100, verbose_name='Local Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_category_translations', to='app_conf.country', verbose_name='Country')),
                ('software_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_asset.softwarecategory', verbose_name='Software Category')),
            ],
            options={
                'verbose_name': 'Software Category Translation',
                'verbose_name_plural': 'Software Category Translations',
                'ordering': ['country__name'],
                'unique_together': {('software_category', 'country')},
            },
        ),
        migrations.CreateModel(
            name='SoftwareStatusTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(max_length=100, verbose_name='Local Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_status_translations', to='app_conf.country', verbose_name='Country')),
                ('software_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_asset.softwarestatus', verbose_name='Software Status')),
            ],
            options={
                'verbose_name': 'Software Status Translation',
                'verbose_name_plural': 'Software Status Translations',
                'ordering': ['country__name'],
                'unique_together': {('software_status', 'country')},
            },
        ),
    ]
