# Generated by Django 5.2.8 on 2026-06-10 10:40

import app_asset.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0006_remove_accessassets_show_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareRegisterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload one or more files (e.g. installers, licenses)', max_length=500, upload_to=app_asset.models.software_register_file_upload_to, verbose_name='File')),
                ('file_hash', models.CharField(blank=True, editable=False, help_text='SHA256 hash of the file content', max_length=64, verbose_name='Hash (SHA256)')),
                ('label', models.CharField(blank=True, help_text='Optional display name for the file', max_length=255, verbose_name='Label')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('software_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app_asset.softwareregister', verbose_name='Software Register Entry')),
            ],
            options={
                'verbose_name': 'Software Register File',
                'verbose_name_plural': 'Software Register Files',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
