# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0007_software_register_files'),
        ('auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareRegisterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(blank=True, help_text='Stored when entry is deleted', max_length=255, verbose_name='Entry name')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('action', models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('deleted', 'Deleted')], max_length=50, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Changes')),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Action By')),
                ('software_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='app_asset.softwareregister', verbose_name='Software Register Entry')),
            ],
            options={
                'verbose_name': 'Software Register History',
                'verbose_name_plural': 'Software Register History',
                'ordering': ['-timestamp'],
            },
        ),
    ]
