# Generated by Django 5.2.8 on 2026-06-10 10:40

import app_asset.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0008_software_register_history'),
        ('app_conf', '0002_add_demo_credentials_to_site_settings'),
        ('auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalMediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('name_local', models.CharField(blank=True, max_length=100, verbose_name='Local Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('color', models.CharField(default='#17a2b8', max_length=7, verbose_name='Color')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'External Media Category',
                'verbose_name_plural': 'External Media Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalMediaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Status Name')),
                ('name_local', models.CharField(blank=True, max_length=100, verbose_name='Local Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Color')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'External Media Status',
                'verbose_name_plural': 'External Media Statuses',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='accessassets',
            name='can_edit_external_media_register',
            field=models.BooleanField(default=False, help_text='Can add, edit and delete entries in External Media Register', verbose_name='Can edit External Media Register'),
        ),
        migrations.AddField(
            model_name='accessassets',
            name='can_view_external_media_register',
            field=models.BooleanField(default=False, help_text='Can open and view the External Media Register page', verbose_name='Can view External Media Register'),
        ),
        migrations.CreateModel(
            name='ExternalMediaRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or description of the media', max_length=255, verbose_name='Name')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Serial number')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_media_entries', to='app_asset.externalmediacategory', verbose_name='Category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_media_register_entries', to='app_conf.company', verbose_name='Company')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_media_entries', to='app_asset.externalmediastatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'External Media Register Entry',
                'verbose_name_plural': 'External Media Register',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalMediaRegisterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=app_asset.models.external_media_file_upload_to, verbose_name='File')),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Hash (SHA256)')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Label')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('external_media_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app_asset.externalmediaregister')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalMediaRegisterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(blank=True, max_length=255, verbose_name='Entry name')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('action', models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('deleted', 'Deleted')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('external_media_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='app_asset.externalmediaregister')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExternalMediaCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(max_length=100, verbose_name='Local Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_asset.externalmediacategory')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_media_category_translations', to='app_conf.country')),
            ],
            options={
                'unique_together': {('category', 'country')},
            },
        ),
        migrations.CreateModel(
            name='ExternalMediaStatusTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(max_length=100, verbose_name='Local Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_media_status_translations', to='app_conf.country')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_asset.externalmediastatus')),
            ],
            options={
                'unique_together': {('status', 'country')},
            },
        ),
    ]
