# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0010_populate_software_and_external_media_lookups'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalmediaregister',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text='Owners from Cabinet users (same as Assets Register)', related_name='external_media_register_entries', to='app_asset.assetowner', verbose_name='Owners'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text='Owners from Cabinet users (same as Assets Register)', related_name='software_register_entries', to='app_asset.assetowner', verbose_name='Owners'),
        ),
    ]
