# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0012_externalmediaregister_actualization_date_and_more'),
        ('auth', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareregister',
            name='actualization_date',
            field=models.DateTimeField(blank=True, help_text='Date when the entry was last actualized by owner', null=True, verbose_name='Actualization date'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='actualized_by',
            field=models.ForeignKey(blank=True, help_text='User who actualized this software entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualized_software_entries', to=settings.AUTH_USER_MODEL, verbose_name='Actualized by'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='marked_no_longer_actual_at',
            field=models.DateTimeField(blank=True, help_text='Date when the entry was marked as no longer actual by owner', null=True, verbose_name='Marked no longer actual at'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='marked_no_longer_comment',
            field=models.TextField(blank=True, default='', help_text='Optional comment when the entry was marked as no longer actual', verbose_name='Marked no longer actual comment'),
        ),
    ]
