# Generated by Django 5.2.8 on 2026-03-26 00:00

import django.db.models.deletion
from django.db import migrations, models


def populate_software_license_types(apps, schema_editor):
    SoftwareLicenseType = apps.get_model('app_asset', 'SoftwareLicenseType')
    defaults = [
        {'code': 'subscription', 'name': 'Subscription', 'color': '#0d6efd', 'display_order': 10},
        {'code': 'perpetual', 'name': 'Perpetual', 'color': '#198754', 'display_order': 20},
        {'code': 'trial', 'name': 'Trial', 'color': '#ffc107', 'display_order': 30},
        {'code': 'freeware', 'name': 'Freeware', 'color': '#6f42c1', 'display_order': 40},
        {'code': 'open_source', 'name': 'Open Source', 'color': '#20c997', 'display_order': 50},
        {'code': 'other', 'name': 'Other', 'color': '#6c757d', 'display_order': 999},
    ]
    for item in defaults:
        SoftwareLicenseType.objects.get_or_create(
            code=item['code'],
            defaults={
                'name': item['name'],
                'color': item['color'],
                'display_order': item['display_order'],
                'is_active': True,
            }
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0013_softwareregister_actualization_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareLicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Default: English (En). E.g. Subscription, Perpetual.', max_length=100, verbose_name='License Type Name')),
                ('name_local', models.CharField(blank=True, max_length=100, verbose_name='Local Name')),
                ('code', models.CharField(help_text='Unique code (e.g., subscription, perpetual)', max_length=50, unique=True, verbose_name='Code')),
                ('color', models.CharField(default='#6c757d', help_text='Hex color for display', max_length=7, verbose_name='Color')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Software License Type',
                'verbose_name_plural': 'Software License Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicenseTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(max_length=100, verbose_name='Local Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_license_type_translations', to='app_conf.country', verbose_name='Country')),
                ('software_license_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_asset.softwarelicensetype', verbose_name='Software License Type')),
            ],
            options={
                'verbose_name': 'Software License Type Translation',
                'verbose_name_plural': 'Software License Type Translations',
                'ordering': ['country__name'],
                'unique_together': {('software_license_type', 'country')},
            },
        ),
        migrations.RunPython(populate_software_license_types, noop),
    ]
