# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0004_alter_informationasset_actualized_by'),
        ('app_asset', '0014_software_license_type'),
    ]

    operations = [
    ]
