# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0014_software_license_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationasset',
            name='software_entries',
            field=models.ManyToManyField(blank=True, help_text='Software from Software Register linked to this asset', related_name='information_assets', to='app_asset.softwareregister', verbose_name='Software Register Entries'),
        ),
    ]
