# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0015_informationasset_software_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationAssetSoftwareSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_version', models.CharField(blank=True, default='', max_length=100, verbose_name='Selected Version')),
                ('selected_license_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Selected License Quantity')),
                ('information_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_selections', to='app_asset.informationasset', verbose_name='Information Asset')),
                ('software_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_selections', to='app_asset.softwareregister', verbose_name='Software Register Entry')),
            ],
            options={
                'verbose_name': 'Information Asset Software Selection',
                'verbose_name_plural': 'Information Asset Software Selections',
                'unique_together': {('information_asset', 'software_register')},
            },
        ),
    ]
