# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0016_informationassetsoftwareselection'),
        ('app_conf', '0002_add_demo_credentials_to_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalitylevel',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Leave empty for organization-wide level', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criticality_levels', to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='criticalitylevel',
            name='code',
            field=models.CharField(help_text='Code unique per company (e.g., low, medium, high)', max_length=50, verbose_name='Level Code'),
        ),
        migrations.AddConstraint(
            model_name='criticalitylevel',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='app_asset_critlevel_company_code_uniq'),
        ),
    ]
