# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0015_merge_20260326_1012'),
        ('app_asset', '0017_criticalitylevel_company_alter_criticalitylevel_code_and_more'),
    ]

    operations = [
    ]
