# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0017_criticalitylevel_company_alter_criticalitylevel_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareregister',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_entries', to='app_asset.assettype', verbose_name='Asset Type'),
        ),
        migrations.AddField(
            model_name='softwareregister',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_entries', to='app_asset.assetgroup', verbose_name='Asset Group'),
        ),
    ]
