# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0019_software_register_cia'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetgroup',
            name='show_in_software_register',
            field=models.BooleanField(default=False, help_text='If checked, this group and its types are available for selection in Software Register entries.', verbose_name='Show in Software Register'),
        ),
    ]
