# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0020_assetgroup_show_in_software_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetgroup',
            name='show_in_software_register',
            field=models.BooleanField(default=True, help_text='If checked, this group will be available in the Group/Type selector of the Software Register.', verbose_name='Show in Software Register'),
        ),
    ]
