# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0021_assetgroup_show_in_software_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationasset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
            preserve_default=False,
        ),
    ]
