# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0022_informationasset_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalmediaregister',
            name='category',
        ),
        migrations.DeleteModel(
            name='ExternalMediaCategoryTranslation',
        ),
        migrations.DeleteModel(
            name='ExternalMediaCategory',
        ),
    ]
