# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0023_remove_external_media_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetgroup',
            name='show_in_external_media_register',
            field=models.BooleanField(default=True, help_text='If checked, this group will be available in the Group/Type selector of the External Media Register.', verbose_name='Show in External Media Register'),
        ),
        migrations.AddField(
            model_name='externalmediaregister',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_media_register_entries', to='app_asset.assettype', verbose_name='Asset Type'),
        ),
        migrations.AddField(
            model_name='externalmediaregister',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_media_register_entries', to='app_asset.assetgroup', verbose_name='Asset Group'),
        ),
    ]
