# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0024_external_media_group_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalmediaregister',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_external_media', to='app_asset.criticalitylevel', verbose_name='Availability'),
        ),
        migrations.AddField(
            model_name='externalmediaregister',
            name='confidentiality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confidentiality_external_media', to='app_asset.criticalitylevel', verbose_name='Confidentiality'),
        ),
        migrations.AddField(
            model_name='externalmediaregister',
            name='integrity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrity_external_media', to='app_asset.criticalitylevel', verbose_name='Integrity'),
        ),
    ]
