# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0025_external_media_cia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationasset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.RemoveField(
            model_name='softwareregister',
            name='category',
        ),
        migrations.DeleteModel(
            name='SoftwareCategory',
        ),
        migrations.DeleteModel(
            name='SoftwareCategoryTranslation',
        ),
    ]
