# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0026_remove_softwarecategorytranslation_software_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareregister',
            name='administrators',
            field=models.ManyToManyField(blank=True, help_text='Asset administrators responsible for this software (same as Assets Register)', related_name='software_register_entries', to='app_asset.assetadministrator', verbose_name='Administrators'),
        ),
    ]
