# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0004_externalmediaguide_externalmediaguidetranslation'),
        ('app_asset', '0027_softwareregister_administrators'),
    ]

    operations = [
    ]
