# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0028_merge_20260430_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwareregister',
            name='administrators',
        ),
    ]
