# Generated by Django 5.2.8 on 2026-06-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0003_add_criticality_level_cia_descriptions'),
        ('app_asset', '0018_merge_20260331_1359'),
        ('app_asset', '0029_remove_softwareregister_administrators'),
    ]

    operations = [
    ]
