# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tprm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='contract',
            field=models.TextField(blank=True, help_text='Summary or description of the agreement with this vendor', verbose_name='Contract'),
        ),
    ]
