# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0002_initial'),
        ('app_tprm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='criticality_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_criticality', to='app_asset.criticalitylevel', verbose_name='Criticality level for the company'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='nda_in_contract',
            field=models.BooleanField(default=False, help_text='Presence of non-disclosure provisions in the contract', verbose_name='NDA in contract'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='sanctions_verification_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_sanctions', to='app_asset.criticalitylevel', verbose_name='Sanctions list verification status'),
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='data_access_level',
        ),
        migrations.AddField(
            model_name='vendor',
            name='data_access_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_data_access', to='app_asset.criticalitylevel', verbose_name='Data Access Level'),
        ),
    ]
