# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tprm', '0002_vendor_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='Optional: explicit end date of the contract', null=True, verbose_name='Contract end date'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contract_validity',
            field=models.TextField(blank=True, help_text='Optional: how long the contract is valid (e.g. fixed term, renewal rules)', verbose_name='Contract validity period'),
        ),
    ]
