# Generated by hand for TPRM Level migration

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def create_default_tprm_levels(apps, schema_editor):
    TprmLevel = apps.get_model('app_tprm', 'TprmLevel')
    # Risk levels (were CharField choices)
    for code, name, color, order in [
        ('low', 'Low', '#28a745', 0),
        ('medium', 'Medium', '#17a2b8', 1),
        ('high', 'High', '#fd7e14', 2),
        ('critical', 'Critical', '#dc3545', 3),
    ]:
        TprmLevel.objects.get_or_create(type='risk_level', code=code, defaults={'name': name, 'color': color, 'display_order': order})
    # Status (were CharField choices)
    for code, name, color, order in [
        ('active', 'Active', '#28a745', 0),
        ('inactive', 'Inactive', '#6c757d', 1),
        ('pending', 'Pending Review', '#ffc107', 2),
        ('suspended', 'Suspended', '#dc3545', 3),
    ]:
        TprmLevel.objects.get_or_create(type='status', code=code, defaults={'name': name, 'color': color, 'display_order': order})
    # Copy from CriticalityLevel for criticality_level, sanctions_verification, data_access_level
    try:
        CriticalityLevel = apps.get_model('app_asset', 'CriticalityLevel')
        for cl in CriticalityLevel.objects.filter(is_active=True).order_by('display_order', 'cost', 'name'):
            for t in ('criticality_level', 'sanctions_verification', 'data_access_level'):
                TprmLevel.objects.get_or_create(
                    type=t, code=cl.code,
                    defaults={'name': cl.name, 'color': cl.color or '#6c757d', 'display_order': cl.display_order, 'cost': cl.cost}
                )
    except LookupError:
        # app_asset not available or no CriticalityLevel
        for t in ('criticality_level', 'sanctions_verification', 'data_access_level'):
            for code, name, color, order in [('low', 'Low', '#28a745', 0), ('medium', 'Medium', '#ffc107', 1), ('high', 'High', '#dc3545', 2)]:
                TprmLevel.objects.get_or_create(type=t, code=code, defaults={'name': name, 'color': color, 'display_order': order})


def migrate_vendor_to_tprm_levels(apps, schema_editor):
    TprmLevel = apps.get_model('app_tprm', 'TprmLevel')
    Vendor = apps.get_model('app_tprm', 'Vendor')
    for v in Vendor.objects.all():
        # risk_level: old CharField -> risk_level_new_id
        old_risk = getattr(v, 'risk_level', None)
        if old_risk and isinstance(old_risk, str):
            lvl = TprmLevel.objects.filter(type='risk_level', code=old_risk, is_active=True).first()
            if lvl:
                v.risk_level_new_id = lvl.id
        # status: old CharField -> status_new_id
        old_status = getattr(v, 'status', None)
        if old_status and isinstance(old_status, str):
            lvl = TprmLevel.objects.filter(type='status', code=old_status, is_active=True).first()
            if lvl:
                v.status_new_id = lvl.id
        # criticality_level: old FK CriticalityLevel -> criticality_level_new_id
        old_id = getattr(v, 'criticality_level_id', None)
        if old_id:
            try:
                CriticalityLevel = apps.get_model('app_asset', 'CriticalityLevel')
                cl = CriticalityLevel.objects.filter(pk=old_id).first()
                if cl:
                    lvl = TprmLevel.objects.filter(type='criticality_level', code=cl.code, is_active=True).first()
                    if lvl:
                        v.criticality_level_new_id = lvl.id
            except LookupError:
                pass
        old_id = getattr(v, 'sanctions_verification_status_id', None)
        if old_id:
            try:
                CriticalityLevel = apps.get_model('app_asset', 'CriticalityLevel')
                cl = CriticalityLevel.objects.filter(pk=old_id).first()
                if cl:
                    lvl = TprmLevel.objects.filter(type='sanctions_verification', code=cl.code, is_active=True).first()
                    if lvl:
                        v.sanctions_verification_status_new_id = lvl.id
            except LookupError:
                pass
        old_id = getattr(v, 'data_access_level_id', None)
        if old_id:
            try:
                CriticalityLevel = apps.get_model('app_asset', 'CriticalityLevel')
                cl = CriticalityLevel.objects.filter(pk=old_id).first()
                if cl:
                    lvl = TprmLevel.objects.filter(type='data_access_level', code=cl.code, is_active=True).first()
                    if lvl:
                        v.data_access_level_new_id = lvl.id
            except LookupError:
                pass
        v.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0002_initial'),
        ('app_tprm', '0002_vendor_nda_criticality_sanctions_data_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='TprmLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('risk_level', 'Risk Level'), ('status', 'Status'), ('criticality_level', 'Criticality level'), ('sanctions_verification', 'Sanctions verification'), ('data_access_level', 'Data Access Level')], db_index=True, max_length=32, verbose_name='Type')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Color')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display order')),
                ('cost', models.IntegerField(default=0, help_text='Numeric value 0–10 for ordering/calculations', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Cost')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'TPRM Level',
                'verbose_name_plural': 'TPRM Levels',
                'ordering': ['type', 'display_order', 'cost', 'name'],
                'unique_together': {('type', 'code')},
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='risk_level_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_risk_new', to='app_tprm.tprmlevel', verbose_name='Risk Level'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_status_new', to='app_tprm.tprmlevel', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='criticality_level_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_criticality_new', to='app_tprm.tprmlevel', verbose_name='Criticality level for the company'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='sanctions_verification_status_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_sanctions_new', to='app_tprm.tprmlevel', verbose_name='Sanctions list verification status'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='data_access_level_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_data_access_new', to='app_tprm.tprmlevel', verbose_name='Data Access Level'),
        ),
        migrations.RunPython(create_default_tprm_levels, noop),
        migrations.RunPython(migrate_vendor_to_tprm_levels, noop),
        migrations.RemoveField(model_name='vendor', name='risk_level'),
        migrations.RemoveField(model_name='vendor', name='status'),
        migrations.RemoveField(model_name='vendor', name='criticality_level'),
        migrations.RemoveField(model_name='vendor', name='sanctions_verification_status'),
        migrations.RemoveField(model_name='vendor', name='data_access_level'),
        migrations.RenameField(model_name='vendor', old_name='risk_level_new', new_name='risk_level'),
        migrations.RenameField(model_name='vendor', old_name='status_new', new_name='status'),
        migrations.RenameField(model_name='vendor', old_name='criticality_level_new', new_name='criticality_level'),
        migrations.RenameField(model_name='vendor', old_name='sanctions_verification_status_new', new_name='sanctions_verification_status'),
        migrations.RenameField(model_name='vendor', old_name='data_access_level_new', new_name='data_access_level'),
    ]
