# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tprm', '0003_tprmlevel_vendor_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='TprmCriticalityLevel',
            fields=[
            ],
            options={
                'verbose_name': 'Criticality level',
                'verbose_name_plural': 'Criticality levels',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_tprm.tprmlevel',),
        ),
        migrations.CreateModel(
            name='TprmDataAccessLevel',
            fields=[
            ],
            options={
                'verbose_name': 'Data Access Level',
                'verbose_name_plural': 'Data Access Levels',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_tprm.tprmlevel',),
        ),
        migrations.CreateModel(
            name='TprmDataAccessRights',
            fields=[
            ],
            options={
                'verbose_name': 'Data Access rights',
                'verbose_name_plural': 'Data Access rights',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_tprm.tprmlevel',),
        ),
        migrations.CreateModel(
            name='TprmRiskLevel',
            fields=[
            ],
            options={
                'verbose_name': 'Risk Level',
                'verbose_name_plural': 'Risk Levels',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_tprm.tprmlevel',),
        ),
        migrations.CreateModel(
            name='TprmSanctionsVerification',
            fields=[
            ],
            options={
                'verbose_name': 'Sanctions verification',
                'verbose_name_plural': 'Sanctions verification',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_tprm.tprmlevel',),
        ),
        migrations.CreateModel(
            name='TprmStatusLevel',
            fields=[
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_tprm.tprmlevel',),
        ),
        migrations.AddField(
            model_name='vendor',
            name='data_access_rights',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'type': 'data_access_rights'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_data_access_rights', to='app_tprm.tprmlevel', verbose_name='Data Access rights'),
        ),
        migrations.AlterField(
            model_name='tprmlevel',
            name='type',
            field=models.CharField(choices=[('risk_level', 'Risk Level'), ('status', 'Status'), ('criticality_level', 'Criticality level'), ('sanctions_verification', 'Sanctions verification'), ('data_access_level', 'Data Access Level'), ('data_access_rights', 'Data Access rights')], db_index=True, max_length=32, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='criticality_level',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'type': 'criticality_level'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_criticality', to='app_tprm.tprmlevel', verbose_name='Criticality level for the company'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='data_access_level',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'type': 'data_access_level'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_data_access', to='app_tprm.tprmlevel', verbose_name='Data Access Level'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='risk_level',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'type': 'risk_level'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_risk', to='app_tprm.tprmlevel', verbose_name='Risk Level'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='sanctions_verification_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'type': 'sanctions_verification'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_sanctions', to='app_tprm.tprmlevel', verbose_name='Sanctions list verification status'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'type': 'status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_status', to='app_tprm.tprmlevel', verbose_name='Status'),
        ),
    ]
