# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0004_externalmediaguide_externalmediaguidetranslation'),
        ('app_tprm', '0003_vendor_contract_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_vendors', to='app_asset.assetowner', verbose_name='Owners'),
        ),
    ]
