# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tprm', '0004_vendor_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to mark the vendor as inactive without deleting the record.', verbose_name='Active'),
        ),
    ]
