# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tprm', '0004_vendor_data_access_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='tprmlevel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
