# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tprm', '0005_vendor_is_active'),
        ('auth', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='actualization_date',
            field=models.DateTimeField(blank=True, help_text='When the vendor record was last confirmed as actual by an owner.', null=True, verbose_name='Actualization date'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='actualized_by',
            field=models.ForeignKey(blank=True, help_text='User who last actualized this vendor record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualized_vendors', to=settings.AUTH_USER_MODEL, verbose_name='Actualized by'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='marked_no_longer_actual_at',
            field=models.DateTimeField(blank=True, help_text='When the owner marked this record as no longer actual.', null=True, verbose_name='Marked no longer actual at'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='marked_no_longer_comment',
            field=models.TextField(blank=True, help_text='Optional comment when marked as no longer actual.', verbose_name='Marked no longer actual comment'),
        ),
    ]
