# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_conf', '0002_add_demo_credentials_to_site_settings'),
        ('app_tprm', '0005_tprmlevel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TprmLevelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(blank=True, max_length=100, verbose_name='Local name')),
                ('description_local', models.TextField(blank=True, verbose_name='Local description')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tprm_level_translations', to='app_conf.country', verbose_name='Country')),
                ('tprm_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_tprm.tprmlevel', verbose_name='TPRM Level')),
            ],
            options={
                'verbose_name': 'TPRM Level translation',
                'verbose_name_plural': 'TPRM Level translations',
                'ordering': ['country__name'],
                'unique_together': {('tprm_level', 'country')},
            },
        ),
    ]
