# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cabinet', '0008_cabinet_task_reminder_schedule'),
        ('app_conf', '0002_add_demo_credentials_to_site_settings'),
        ('app_tprm', '0006_tprmlevel_translations'),
        ('auth', '__first__'),
    ]

    operations = [
    ]
