# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tprm', '0007_tprm_owner'),
        ('auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('action', models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('owners_changed', 'Owners changed'), ('actualized', 'Actualized'), ('marked_not_actual', 'Marked as no longer actual')], max_length=50, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Changes')),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_history_actions', to=settings.AUTH_USER_MODEL, verbose_name='Action by')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app_tprm.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Vendor history',
                'verbose_name_plural': 'Vendor history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vendor', '-timestamp'], name='app_tprm_ve_vendor__f1e1e0_idx'), models.Index(fields=['action'], name='app_tprm_ve_action_e4ad5e_idx')],
            },
        ),
    ]
