# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tprm', '0007_vendor_tprm_owner_and_extra_fields'),
        ('app_tprm', '0008_vendor_history'),
    ]

    operations = [
    ]
