# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_conf', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name, default: English (En). For other languages use Translations inline.', max_length=100, verbose_name='Classification Name')),
                ('name_local', models.CharField(blank=True, help_text='Name in local language (use Translations inline for per-country names)', max_length=100, verbose_name='Local Name')),
                ('code', models.CharField(blank=True, help_text='Unique code (e.g., security-breach, data-leak)', max_length=50, unique=True, verbose_name='Classification Code')),
                ('description', models.TextField(blank=True, help_text='Description, default: English (En). For other languages use Translations inline.', verbose_name='Description')),
                ('color', models.CharField(default='#000000', help_text='Color in HEX format, e.g. #FF0000', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
            },
        ),
        migrations.CreateModel(
            name='Currentstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='State name, default: English (En). E.g. Open, In Progress, Closed. For other languages use Translations inline.', max_length=100, verbose_name='State Name')),
                ('name_local', models.CharField(blank=True, help_text='State name in local language (use Translations inline for per-country names)', max_length=100, verbose_name='Local Name')),
                ('code', models.CharField(blank=True, help_text='Unique code (e.g., open, in-progress, closed)', max_length=50, unique=True, verbose_name='State Code')),
                ('description', models.TextField(blank=True, help_text='Description, default: English (En). For other languages use Translations inline.', verbose_name='Description')),
                ('color', models.CharField(default='#000000', help_text='Color in HEX format, e.g. #FF0000', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Current State',
                'verbose_name_plural': 'Current States',
            },
        ),
        migrations.CreateModel(
            name='IncidentRegisterGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'Incident Register Guide',
                'verbose_name_plural': 'Incident Register Guides',
            },
        ),
        migrations.CreateModel(
            name='Incidenttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Type name, default: English (En). E.g. Security breach, Data leak. For other languages use Translations inline.', max_length=100, verbose_name='Type Name')),
                ('name_local', models.CharField(blank=True, help_text='Type name in local language (use Translations inline for per-country names)', max_length=100, verbose_name='Local Name')),
                ('code', models.CharField(blank=True, help_text='Unique code (e.g., security-breach, data-leak)', max_length=50, unique=True, verbose_name='Type Code')),
                ('description', models.TextField(blank=True, help_text='Description, default: English (En). For other languages use Translations inline.', verbose_name='Description')),
                ('color', models.CharField(default='#000000', help_text='Color in HEX format, e.g. #FF0000', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Incident Type',
                'verbose_name_plural': 'Incident Types',
            },
        ),
        migrations.CreateModel(
            name='AccessIncidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=False, verbose_name='Has access to Information Incidents')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Can edit Information Incidents')),
                ('can_add', models.BooleanField(default=False, verbose_name='Can add new Information Incidents')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Can delete Information Incidents')),
                ('can_mail', models.BooleanField(default=False, verbose_name='Can send emails for Information Incidents')),
                ('show_link', models.BooleanField(default=False, verbose_name='Show link on index page')),
                ('description', models.TextField(blank=True)),
                ('companies', models.ManyToManyField(blank=True, related_name='access_incidents', to='app_conf.company', verbose_name='Companies')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Access to Incidents',
                'verbose_name_plural': 'Access to Incidents',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Date and Time of Occurrence')),
                ('place', models.CharField(max_length=255, verbose_name='Place of Occurrence')),
                ('description', models.TextField(verbose_name='Description')),
                ('features', models.TextField(blank=True, verbose_name='Features and Signs')),
                ('responsible', models.CharField(max_length=255, verbose_name='Responsible for Resolution')),
                ('reported_by', models.CharField(max_length=255, verbose_name='Reported by')),
                ('reported_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Date and Time')),
                ('registered_by', models.CharField(max_length=255, verbose_name='Registered by')),
                ('registered_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Date and Time')),
                ('reports_and_records', models.TextField(blank=True, verbose_name='Reports and Records')),
                ('impact', models.TextField(blank=True, verbose_name='Impact')),
                ('measures_taken', models.TextField(blank=True, verbose_name='Measures Taken')),
                ('additional_measures', models.TextField(blank=True, verbose_name='Additional Measures to Prevent Recurrence')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('file_incident', models.FileField(blank=True, max_length=255, null=True, upload_to='incident_reports/', verbose_name='Incident report files')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_incident.classification')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conf.company', verbose_name='Company')),
                ('current_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_incident.currentstate')),
                ('incident_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_incident.incidenttype')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-occurrence_datetime'],
            },
        ),
        migrations.CreateModel(
            name='IncidentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='incident_reports/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app_incident.incident')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(help_text="Classification name in country's language", max_length=100, verbose_name='Local Name')),
                ('description', models.TextField(blank=True, help_text="Description in country's language", verbose_name='Description')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_incident.classification', verbose_name='Classification')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_translations', to='app_conf.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Classification Translation',
                'verbose_name_plural': 'Classification Translations',
                'ordering': ['country__name'],
                'unique_together': {('classification', 'country')},
            },
        ),
        migrations.CreateModel(
            name='CurrentstateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(help_text="State name in country's language", max_length=100, verbose_name='Local Name')),
                ('description', models.TextField(blank=True, help_text="Description in country's language", verbose_name='Description')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentstate_translations', to='app_conf.country', verbose_name='Country')),
                ('currentstate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_incident.currentstate', verbose_name='Current State')),
            ],
            options={
                'verbose_name': 'Current State Translation',
                'verbose_name_plural': 'Current State Translations',
                'ordering': ['country__name'],
                'unique_together': {('currentstate', 'country')},
            },
        ),
        migrations.CreateModel(
            name='IncidentRegisterGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_register_guide_translations', to='app_conf.country', verbose_name='Country')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_incident.incidentregisterguide', verbose_name='Guide')),
            ],
            options={
                'verbose_name': 'Incident Register Guide Translation',
                'verbose_name_plural': 'Incident Register Guide Translations',
                'ordering': ['country__name'],
                'unique_together': {('guide', 'country')},
            },
        ),
        migrations.CreateModel(
            name='IncidenttypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(help_text="Type name in country's language", max_length=100, verbose_name='Local Name')),
                ('description', models.TextField(blank=True, help_text="Description in country's language", verbose_name='Description')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidenttype_translations', to='app_conf.country', verbose_name='Country')),
                ('incidenttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_incident.incidenttype', verbose_name='Incident Type')),
            ],
            options={
                'verbose_name': 'Incident Type Translation',
                'verbose_name_plural': 'Incident Type Translations',
                'ordering': ['country__name'],
                'unique_together': {('incidenttype', 'country')},
            },
        ),
    ]
