# Generated by Django 5.2.8 on 2026-06-10 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cif', '0001_initial'),
        ('app_incident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='cif_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='app_cif.cifobject', verbose_name='CIF object'),
        ),
    ]
