# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_conf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securelicense',
            name='record_hmac',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Record HMAC'),
        ),
    ]
