# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_conf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='demo_login',
            field=models.CharField(blank=True, help_text='Login (email) to display on the login page for copying when Project Type is DEMO.', max_length=255, verbose_name='DEMO Login'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='demo_password',
            field=models.CharField(blank=True, help_text='Password to display on the login page for copying when Project Type is DEMO.', max_length=255, verbose_name='DEMO Password'),
        ),
    ]
