# Generated by Django 5.2.8 on 2026-06-10 10:40

import app_ai.models
import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('model_id', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Model Choices',
                'unique_together': {('provider', 'model_id')},
            },
        ),
        migrations.CreateModel(
            name='APISettingsOllama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField()),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=100)),
                ('top_p', models.FloatField(default=1.0)),
                ('frequency_penalty', models.FloatField(default=0.0)),
                ('presence_penalty', models.FloatField(default=0.0)),
                ('model_name', models.ForeignKey(limit_choices_to={'is_active': True, 'provider': 'ollama'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ai.modelchoice')),
            ],
            options={
                'verbose_name_plural': 'API Settings Ollama',
            },
        ),
        migrations.CreateModel(
            name='APISettingsGroq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField()),
                ('model_name', models.ForeignKey(limit_choices_to={'is_active': True, 'provider': 'groq'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ai.modelchoice')),
            ],
            options={
                'verbose_name_plural': 'API Settings Groq',
            },
        ),
        migrations.CreateModel(
            name='APISettingsGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField()),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploaded_files/')),
                ('model_name', models.ForeignKey(limit_choices_to={'is_active': True, 'provider': 'google'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ai.modelchoice')),
            ],
            options={
                'verbose_name_plural': 'API Settings Google',
            },
        ),
        migrations.CreateModel(
            name='APISettingsDeepSeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField(validators=[app_ai.models.validate_deepseek_api_key])),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('top_p', models.FloatField(default=1.0)),
                ('frequency_penalty', models.FloatField(default=0.0)),
                ('presence_penalty', models.FloatField(default=0.0)),
                ('model_name', models.ForeignKey(limit_choices_to={'is_active': True, 'provider': 'deepseek'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ai.modelchoice')),
            ],
            options={
                'verbose_name_plural': 'API Settings DeepSeek',
            },
        ),
        migrations.CreateModel(
            name='APISettingsClaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField(validators=[app_ai.models.validate_claude_api_key])),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('model_name', models.ForeignKey(limit_choices_to={'is_active': True, 'provider': 'claude'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ai.modelchoice')),
            ],
            options={
                'verbose_name_plural': 'API Settings Claude',
            },
        ),
        migrations.CreateModel(
            name='AIAgentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Чи активований AI помічник')),
                ('enabled_for_all_pages', models.BooleanField(default=True, help_text='Чи показувати помічника на всіх сторінках')),
                ('user', models.OneToOneField(blank=True, help_text='Якщо не вказано, то це глобальні налаштування за замовчуванням', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('model_choice', models.ForeignKey(blank=True, help_text='Модель AI для використання агентом', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ai.modelchoice')),
            ],
            options={
                'verbose_name': 'AI Agent Settings',
                'verbose_name_plural': 'AI Agent Settings',
            },
        ),
        migrations.CreateModel(
            name='AIAssistantHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(help_text='Повідомлення користувача')),
                ('ai_response', models.TextField(blank=True, help_text='Відповідь AI', null=True)),
                ('page_url', models.URLField(blank=True, help_text='URL сторінки, на якій був зроблений запит', max_length=500, null=True)),
                ('page_type', models.CharField(blank=True, help_text='Тип сторінки (compliance, risk, incident, etc.)', max_length=100, null=True)),
                ('page_description', models.CharField(blank=True, help_text='Опис сторінки', max_length=500, null=True)),
                ('is_success', models.BooleanField(default=True, help_text='Чи був запит успішним')),
                ('error_message', models.TextField(blank=True, help_text='Повідомлення про помилку, якщо запит не вдався', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Час створення запиту')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Час відповіді в мілісекундах', null=True)),
                ('input_tokens', models.IntegerField(blank=True, help_text='Кількість токенів у запиті (input tokens)', null=True)),
                ('output_tokens', models.IntegerField(blank=True, help_text='Кількість токенів у відповіді (output tokens)', null=True)),
                ('total_tokens', models.IntegerField(blank=True, help_text='Загальна кількість токенів', null=True)),
                ('user', models.ForeignKey(help_text='Користувач, який зробив запит', on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistant_queries', to=settings.AUTH_USER_MODEL)),
                ('model_choice', models.ForeignKey(blank=True, help_text='Модель AI, яка була використана', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ai.modelchoice')),
            ],
            options={
                'verbose_name': 'AI Assistant History',
                'verbose_name_plural': 'AI Assistant History',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='app_ai_aias_created_b0e90a_idx'), models.Index(fields=['user', '-created_at'], name='app_ai_aias_user_id_072a56_idx'), models.Index(fields=['page_type'], name='app_ai_aias_page_ty_2ffc99_idx')],
            },
        ),
    ]
