# Generated by Django 5.2.8 on 2026-06-11 11:30

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_conf', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=False, verbose_name='Has access')),
                ('can_view_integrations', models.BooleanField(default=True, verbose_name='Can view integrations')),
                ('can_manage_integrations', models.BooleanField(default=False, verbose_name='Can manage integrations')),
                ('can_test_connections', models.BooleanField(default=True, verbose_name='Can test connections')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('companies', models.ManyToManyField(blank=True, help_text='Leave empty for access to all companies.', related_name='access_integration', to='app_conf.company', verbose_name='Companies')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_integration', to='auth.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Access to Integrations',
                'verbose_name_plural': 'Access to Integrations',
            },
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('bot_token', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Bot token')),
                ('bot_username', models.CharField(blank=True, help_text='Filled automatically after a successful connection test.', max_length=100, verbose_name='Bot username')),
                ('bot_id', models.BigIntegerField(blank=True, null=True, verbose_name='Bot ID')),
                ('default_chat_id', models.CharField(blank=True, help_text='Chat or channel ID for outbound notifications (optional).', max_length=64, verbose_name='Default chat ID')),
                ('use_webhook', models.BooleanField(default=False, help_text='Receive updates via webhook instead of long polling.', verbose_name='Use webhook')),
                ('webhook_secret', models.CharField(blank=True, help_text='Optional secret token for incoming webhook validation.', max_length=128, verbose_name='Webhook secret')),
                ('respond_to_start', models.BooleanField(default=True, help_text='Send a welcome message when a user sends /start to the bot.', verbose_name='Respond to /start')),
                ('start_message', models.TextField(blank=True, help_text='Custom reply for /start. Leave empty to use the default welcome message.', verbose_name='Start message')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_connection_check', models.DateTimeField(blank=True, null=True, verbose_name='Last connection check')),
                ('last_connection_ok', models.BooleanField(default=False, verbose_name='Last connection OK')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_bots', to='app_conf.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_bots', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Telegram bot',
                'verbose_name_plural': 'Telegram bots',
                'ordering': ['name'],
            },
        ),
    ]
