# Generated by Django 5.2.8 on 2026-06-24 09:44

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cabinet', '0002_initial'),
        ('app_conf', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyCertGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'Key/Cert Guide',
                'verbose_name_plural': 'Key/Cert Guides',
            },
        ),
        migrations.CreateModel(
            name='KeycertOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('department', models.CharField(max_length=100, verbose_name='Department/Position')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Key/Certificate Owner',
                'verbose_name_plural': 'Key/Certificate Owners',
            },
        ),
        migrations.CreateModel(
            name='Revocationstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Status name, default: English (En). E.g. Active, Revoked. For other languages use Translations inline.', max_length=100, verbose_name='Status Name')),
                ('name_local', models.CharField(blank=True, help_text='Status name in local language (use Translations inline for per-country names)', max_length=100, verbose_name='Local Name')),
                ('code', models.CharField(blank=True, help_text='Unique code (e.g., active, revoked)', max_length=50, unique=True, verbose_name='Status Code')),
                ('description', models.TextField(blank=True, help_text='Description, default: English (En). For other languages use Translations inline.', verbose_name='Description')),
                ('color', models.CharField(default='#000000', help_text='Color in HEX format, e.g. #FF0000', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Revocation Status',
                'verbose_name_plural': 'Revocation Status',
            },
        ),
        migrations.CreateModel(
            name='Typekeycert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Type name, default: English (En). For other languages use Translations inline.', max_length=100, verbose_name='Type Name')),
                ('name_local', models.CharField(blank=True, help_text='Type name in local language (use Translations inline for per-country names)', max_length=100, verbose_name='Local Name')),
                ('code', models.CharField(blank=True, help_text='Unique code (e.g., encryption-key, ssl-cert)', max_length=50, unique=True, verbose_name='Type Code')),
                ('description', models.TextField(blank=True, help_text='Description, default: English (En). For other languages use Translations inline.', verbose_name='Description')),
                ('color', models.CharField(default='#000000', help_text='Color in HEX format, e.g. #FF0000', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Key/Certificate Type',
                'verbose_name_plural': 'Key/Certificate Types',
            },
        ),
        migrations.CreateModel(
            name='AccessKeyCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=False, verbose_name='Has access to KeyCert')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Can edit KeyCert')),
                ('show_link', models.BooleanField(default=False, verbose_name='Show link on index page')),
                ('description', models.TextField(blank=True)),
                ('companies', models.ManyToManyField(blank=True, related_name='access_keycert', to='app_conf.company', verbose_name='Companies')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Access to KeyCert',
                'verbose_name_plural': 'Access to KeyCert',
            },
        ),
        migrations.CreateModel(
            name='KeyCertificates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key_cert_num', models.CharField(max_length=50, verbose_name='Key/Cert Number')),
                ('cert_hash', models.CharField(blank=True, max_length=128, verbose_name='Certificate/Key Hash')),
                ('purpose', models.TextField(verbose_name='Purpose')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('access_control', models.TextField(verbose_name='Access Control')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('enable_reminder', models.BooleanField(default=False, verbose_name='Enable Reminder')),
                ('actualization_date', models.DateTimeField(blank=True, null=True, verbose_name='Actualization Date')),
                ('actualized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualized_key_certs', to=settings.AUTH_USER_MODEL, verbose_name='Actualized By')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_key_certs', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conf.company', verbose_name='Company')),
                ('owner_cabinet_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_key_certs', to='app_cabinet.cabinetuser', verbose_name='Owner (Cabinet user)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_key_certs', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_keycert.keycertowner', verbose_name='Owner')),
                ('revocation_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_keycert.revocationstatus')),
                ('type_key_sert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_keycert.typekeycert')),
            ],
            options={
                'verbose_name': 'Key/Certificate',
                'verbose_name_plural': 'Keys and Certificates',
            },
        ),
        migrations.CreateModel(
            name='KeyCertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('deleted', 'Deleted'), ('reminder_attempt', 'Reminder Attempt'), ('reminder_sent', 'Reminder Sent'), ('reminder_failed', 'Reminder Failed'), ('manual_reminder_requested', 'Manual Reminder Requested'), ('manual_reminder_sent', 'Manual Reminder Sent'), ('manual_reminder_failed', 'Manual Reminder Failed')], max_length=50)),
                ('details', models.TextField()),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('key_certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app_keycert.keycertificates')),
            ],
            options={
                'verbose_name': 'Key/Certificate History',
                'verbose_name_plural': 'Key/Certificate History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GenKeycertInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('date_created', models.DateTimeField(verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Last Updated')),
                ('version', models.CharField(max_length=50, verbose_name='Version')),
                ('maintainer_name', models.CharField(max_length=255, verbose_name='Maintainer Name')),
                ('maintainer_contact', models.CharField(max_length=255, verbose_name='Maintainer Contact')),
                ('key_certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_info', to='app_keycert.keycertificates')),
            ],
            options={
                'verbose_name': 'General Key/Certificate Info',
                'verbose_name_plural': 'General Key/Certificate Info',
            },
        ),
        migrations.CreateModel(
            name='KeyCertGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keycert_guide_translations', to='app_conf.country', verbose_name='Country')),
                ('keycert_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_keycert.keycertguide', verbose_name='Key/Cert Guide')),
            ],
            options={
                'verbose_name': 'Key/Cert Guide Translation',
                'verbose_name_plural': 'Key/Cert Guide Translations',
                'ordering': ['country__name'],
                'unique_together': {('keycert_guide', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('days', 'Days before expiry'), ('date', 'Specific date')], max_length=10, verbose_name='Reminder Type')),
                ('reminder_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Days before expiry')),
                ('reminder_date', models.DateTimeField(blank=True, null=True, verbose_name='Reminder Date')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Is Sent')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Is Cancelled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('celery_task_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celery Task ID')),
                ('key_certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='app_keycert.keycertificates', verbose_name='Key/Certificate')),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key_certificate', 'is_sent', 'is_cancelled'], name='app_keycert_key_cer_e815a8_idx'), models.Index(fields=['created_at'], name='app_keycert_created_69d597_idx'), models.Index(fields=['sent_at'], name='app_keycert_sent_at_bf954f_idx')],
            },
        ),
        migrations.CreateModel(
            name='RevocationstatusTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(help_text="Status name in country's language", max_length=100, verbose_name='Local Name')),
                ('description', models.TextField(blank=True, help_text="Description in country's language", verbose_name='Description')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revocationstatus_translations', to='app_conf.country', verbose_name='Country')),
                ('revocationstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_keycert.revocationstatus', verbose_name='Revocation Status')),
            ],
            options={
                'verbose_name': 'Revocation Status Translation',
                'verbose_name_plural': 'Revocation Status Translations',
                'ordering': ['country__name'],
                'unique_together': {('revocationstatus', 'country')},
            },
        ),
        migrations.CreateModel(
            name='TypekeycertTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(help_text="Type name in country's language", max_length=100, verbose_name='Local Name')),
                ('description', models.TextField(blank=True, help_text="Description in country's language", verbose_name='Description')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typekeycert_translations', to='app_conf.country', verbose_name='Country')),
                ('typekeycert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_keycert.typekeycert', verbose_name='Key/Certificate Type')),
            ],
            options={
                'verbose_name': 'Key/Certificate Type Translation',
                'verbose_name_plural': 'Key/Certificate Type Translations',
                'ordering': ['country__name'],
                'unique_together': {('typekeycert', 'country')},
            },
        ),
    ]
