# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cabinet', '0002_initial'),
        ('app_conf', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageManagerGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'Page Manager Guide',
                'verbose_name_plural': 'Page Manager Guides',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='QuizManagerGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'Quiz Manager Guide',
                'verbose_name_plural': 'Quiz Manager Guides',
            },
        ),
        migrations.CreateModel(
            name='AccessPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=False, verbose_name='Has access to Page Manager')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Can edit Pages')),
                ('show_link', models.BooleanField(default=False, verbose_name='Show link on index page')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('companies', models.ManyToManyField(blank=True, related_name='access_page', to='app_conf.company', verbose_name='Companies')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Access to Page Manager',
                'verbose_name_plural': 'Access to Page Manager',
            },
        ),
        migrations.CreateModel(
            name='AccessQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=False, verbose_name='Has access to Quiz')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Can edit Quiz')),
                ('show_link', models.BooleanField(default=False, verbose_name='Show link on index page')),
                ('has_access_to_results', models.BooleanField(default=False, verbose_name='Has access to Quiz Results')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('companies', models.ManyToManyField(blank=True, related_name='access_quiz', to='app_conf.company', verbose_name='Companies')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Access to Quiz',
                'verbose_name_plural': 'Access to Quiz',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content (Rich Text)')),
                ('html_content', models.TextField(blank=True, null=True, verbose_name='Content (HTML)')),
                ('use_html', models.BooleanField(default=False, verbose_name='Use HTML')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='External Link')),
                ('youtube_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='YouTube Video ID')),
                ('video_file', models.FileField(blank=True, help_text='Upload video file (MP4, WebM, OGV)', null=True, upload_to='pages/videos/', verbose_name='Video File')),
                ('audio_file', models.FileField(blank=True, help_text='Upload audio file (MP3, WAV, OGG)', null=True, upload_to='pages/audio/', verbose_name='Audio File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('cabinet_groups', models.ManyToManyField(blank=True, related_name='pages', to='app_cabinet.cabinetgroup', verbose_name='Cabinet Groups')),
                ('cabinet_users', models.ManyToManyField(blank=True, related_name='pages', to='app_cabinet.cabinetuser', verbose_name='Cabinet Users')),
                ('companies', models.ManyToManyField(blank=True, related_name='accessible_pages', to='app_conf.company', verbose_name='Companies')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PageAudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for this audio file', max_length=200, verbose_name='Audio Title')),
                ('audio_file', models.FileField(help_text='Upload audio file (MP3, WAV, OGG, M4A, AAC)', upload_to='pages/audio/', verbose_name='Audio File')),
                ('description', models.TextField(blank=True, help_text='Optional description for this audio', null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers first)', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='app_study.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Page Audio File',
                'verbose_name_plural': 'Page Audio Files',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for this document file', max_length=200, verbose_name='Document Title')),
                ('document_file', models.FileField(help_text='Upload document file (PDF, DOCX, XLSX, PPTX, TXT, RTF)', upload_to='pages/documents/', verbose_name='Document File')),
                ('description', models.TextField(blank=True, help_text='Optional description for this document', null=True, verbose_name='Description')),
                ('file_type', models.CharField(blank=True, help_text='Automatically detected file type', max_length=10, verbose_name='File Type')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True, verbose_name='File Size')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers first)', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_files', to='app_study.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Page Document File',
                'verbose_name_plural': 'Page Document Files',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display title for this link', max_length=200, verbose_name='Link Title')),
                ('url', models.URLField(help_text='Full URL including http:// or https://', verbose_name='URL')),
                ('description', models.TextField(blank=True, help_text='Optional description for this link', null=True, verbose_name='Description')),
                ('open_in_new_tab', models.BooleanField(default=True, help_text='Whether to open this link in a new tab', verbose_name='Open in New Tab')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers first)', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_urls', to='app_study.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Page URL',
                'verbose_name_plural': 'Page URLs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageVideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for this video file', max_length=200, verbose_name='Video Title')),
                ('video_file', models.FileField(help_text='Upload video file (MP4, WebM, OGV, AVI, MOV)', upload_to='pages/videos/', verbose_name='Video File')),
                ('description', models.TextField(blank=True, help_text='Optional description for this video', null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers first)', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to='app_study.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Page Video File',
                'verbose_name_plural': 'Page Video Files',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageYouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for this YouTube video', max_length=200, verbose_name='Video Title')),
                ('youtube_id', models.CharField(help_text='YouTube video ID (e.g., dQw4w9WgXcQ)', max_length=20, verbose_name='YouTube Video ID')),
                ('description', models.TextField(blank=True, help_text='Optional description for this video', null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers first)', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_videos', to='app_study.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Page YouTube Video',
                'verbose_name_plural': 'Page YouTube Videos',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct Answer')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app_study.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='Shuffle Questions')),
                ('shuffle_answers', models.BooleanField(default=False, verbose_name='Shuffle Answers')),
                ('passing_score', models.IntegerField(default=0, verbose_name='Passing Score')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('youtube_video_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='YouTube Video ID')),
                ('pdf_material', models.FileField(blank=True, null=True, upload_to='quiz_pdfs/', verbose_name='PDF Material')),
                ('pdf_filename', models.CharField(blank=True, max_length=255, verbose_name='PDF Filename')),
                ('cabinet_groups', models.ManyToManyField(blank=True, related_name='quizzes', to='app_cabinet.cabinetgroup', verbose_name='Cabinet Groups')),
                ('cabinet_users', models.ManyToManyField(blank=True, related_name='quizzes', to='app_cabinet.cabinetuser', verbose_name='Cabinet Users')),
                ('companies', models.ManyToManyField(blank=True, related_name='quizzes', to='app_conf.company', verbose_name='Companies')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='app_study.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_study.quiz', verbose_name='Quiz'),
        ),
        migrations.CreateModel(
            name='ImmediateEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('email_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_conf.mailaccount')),
                ('recipients', models.ManyToManyField(blank=True, related_name='received_quiz_emails', to=settings.AUTH_USER_MODEL, verbose_name='Recipients')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_immediate_emails', to=settings.AUTH_USER_MODEL, verbose_name='Sent By')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immediate_email_logs', to='app_study.quiz')),
            ],
            options={
                'verbose_name': 'Immediate Email Log',
                'verbose_name_plural': 'Immediate Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_study.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct Answer')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_study.answer', verbose_name='Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_study.question', verbose_name='Question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app_study.quizattempt', verbose_name='Attempt')),
            ],
            options={
                'verbose_name': 'Quiz Question Answer',
                'verbose_name_plural': 'Quiz Question Answers',
            },
        ),
        migrations.CreateModel(
            name='ScheduledReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_template', models.CharField(max_length=255)),
                ('body_template', models.TextField()),
                ('interval', models.CharField(choices=[('once', 'Once'), ('week', 'Weekly'), ('month', 'Monthly'), ('quarter', 'Quarterly'), ('half_year', 'Half Yearly')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('next_send', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_all_users', models.BooleanField(default=False)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conf.mailaccount')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reminders', to='app_study.quiz')),
                ('target_groups', models.ManyToManyField(blank=True, related_name='scheduled_reminders', to='auth.group')),
                ('target_users', models.ManyToManyField(blank=True, related_name='scheduled_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduled Reminder',
                'verbose_name_plural': 'Scheduled Reminders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('recipients', models.ManyToManyField(blank=True, related_name='received_scheduled_quiz_emails', to=settings.AUTH_USER_MODEL, verbose_name='Recipients')),
                ('scheduled_reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app_study.scheduledreminder')),
            ],
            options={
                'verbose_name': 'Reminder Log',
                'verbose_name_plural': 'Reminder Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PageManagerGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_manager_guide_translations', to='app_conf.country', verbose_name='Country')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_study.pagemanagerguide', verbose_name='Guide')),
            ],
            options={
                'verbose_name': 'Page Manager Guide Translation',
                'verbose_name_plural': 'Page Manager Guide Translations',
                'ordering': ['country__name'],
                'unique_together': {('guide', 'country')},
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Template')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='app_study.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'unique_together': {('quiz', 'is_default')},
            },
        ),
        migrations.CreateModel(
            name='QuizManagerGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_manager_guide_translations', to='app_conf.country', verbose_name='Country')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_study.quizmanagerguide', verbose_name='Guide')),
            ],
            options={
                'verbose_name': 'Quiz Manager Guide Translation',
                'verbose_name_plural': 'Quiz Manager Guide Translations',
                'ordering': ['country__name'],
                'unique_together': {('guide', 'country')},
            },
        ),
        migrations.CreateModel(
            name='QuizResultsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results_settings', to='app_conf.company', verbose_name='Company')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results_settings', to='auth.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Quiz Results Settings',
                'verbose_name_plural': 'Quiz Results Settings',
                'unique_together': {('group', 'company')},
            },
        ),
    ]
