# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_conf', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISO27002Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('people', 'People'), ('physical', 'Physical'), ('technological', 'Technological'), ('organizational', 'Organizational')], max_length=50, verbose_name='Theme Name')),
                ('description', models.TextField(blank=True, default='', help_text='Default (e.g. English). Use Translations for other languages.', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'ISO 27002 Theme',
                'verbose_name_plural': 'ISO 27002 Themes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PCIDSSCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=100, unique=True, verbose_name='Category ID')),
                ('name', models.CharField(blank=True, help_text='Category name, default: English. For other languages use Translations inline.', max_length=255, verbose_name='Name')),
                ('name_local', models.CharField(blank=True, help_text='Category name in local language (use Translations inline for per-country names)', max_length=255, verbose_name='Local Name')),
                ('code', models.CharField(blank=True, help_text='Unique code (auto-generated from name if empty)', max_length=80, verbose_name='Code')),
                ('description', models.TextField(blank=True, help_text='Description. For other languages use Translations inline.', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'PCI DSS Standard',
                'verbose_name_plural': 'PCI DSS Standard',
                'ordering': ['category_id', 'name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PCIDSSDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='pcidss_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessISO27002',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=False, verbose_name='Has access to ISO 27002')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Can edit ISO 27002 information')),
                ('show_link', models.BooleanField(default=False, verbose_name='Show link on index page to ISO 27002')),
                ('description', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Access to ISO 27002',
                'verbose_name_plural': 'Access to ISO 27002',
            },
        ),
        migrations.CreateModel(
            name='AccessPCIDSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=False, verbose_name='Has access to PCIDSS')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Can edit Information PCIDSS')),
                ('show_link', models.BooleanField(default=False, verbose_name='Show link on index page to pcidss')),
                ('description', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Access to PCIDSS',
                'verbose_name_plural': 'Access to PCIDSS',
            },
        ),
        migrations.CreateModel(
            name='ISO27002Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=10, verbose_name='Control Number')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('control_description', models.TextField(blank=True, default='', verbose_name='Control Description')),
                ('purpose', models.TextField(blank=True, default='', verbose_name='Purpose')),
                ('guidance', models.TextField(blank=True, default='', verbose_name='Guidance')),
                ('other_information', models.TextField(blank=True, default='', verbose_name='Other Information')),
                ('control_type', models.CharField(choices=[('preventive', 'Preventive'), ('detective', 'Detective'), ('corrective', 'Corrective')], max_length=20, verbose_name='Control Type')),
                ('information_security_properties', models.JSONField(help_text='List of applicable security properties (confidentiality, integrity, availability)', verbose_name='Information Security Properties')),
                ('cybersecurity_concepts', models.JSONField(help_text='List of applicable cybersecurity concepts', verbose_name='Cybersecurity Concepts')),
                ('operational_capabilities', models.JSONField(help_text='List of applicable operational capabilities', verbose_name='Operational Capabilities')),
                ('security_domain', models.CharField(choices=[('governance_and_ecosystem', 'Governance and Ecosystem'), ('protection', 'Protection'), ('defence', 'Defence'), ('resilience', 'Resilience')], max_length=50, verbose_name='Security Domain')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='app_std.iso27002theme')),
            ],
            options={
                'verbose_name': 'ISO 27002 Control',
                'verbose_name_plural': 'ISO 27002 Controls',
                'ordering': ['control_number'],
            },
        ),
        migrations.CreateModel(
            name='PCIDSSRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_number', models.CharField(max_length=10, verbose_name='Requirement Number')),
                ('title', models.TextField(blank=True, default='', verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('definitions', models.TextField(blank=True, default='', verbose_name='Definitions')),
                ('purpose', models.TextField(blank=True, default='', verbose_name='Purpose')),
                ('good_practice', models.TextField(blank=True, default='', verbose_name='Good Practice')),
                ('examples', models.TextField(blank=True, default='', verbose_name='Examples')),
                ('testing_procedures', models.TextField(blank=True, default='', verbose_name='Testing Procedures')),
                ('customized_approach_objective', models.TextField(blank=True, default='', verbose_name='Customized Approach Objective')),
                ('applicability_notes', models.TextField(blank=True, default='', verbose_name='Applicability Notes')),
                ('further_information', models.TextField(blank=True, default='', verbose_name='Further Information')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='app_std.pcidsscategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'PCI DSS Requirement',
                'verbose_name_plural': 'PCI DSS Requirements',
                'ordering': ['requirement_number'],
            },
        ),
        migrations.CreateModel(
            name='ISO27002ControlTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('control_description', models.TextField(blank=True, default='', verbose_name='Control Description')),
                ('purpose', models.TextField(blank=True, default='', verbose_name='Purpose')),
                ('guidance', models.TextField(blank=True, default='', verbose_name='Guidance')),
                ('other_information', models.TextField(blank=True, default='', verbose_name='Other Information')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_std.iso27002control', verbose_name='Control')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iso27002_control_translations', to='app_conf.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'ISO 27002 Control Translation',
                'verbose_name_plural': 'ISO 27002 Control Translations',
                'ordering': ['country__name'],
                'unique_together': {('control', 'country')},
            },
        ),
        migrations.CreateModel(
            name='ISO27002ThemeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iso27002_theme_translations', to='app_conf.country', verbose_name='Country')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_std.iso27002theme', verbose_name='Theme')),
            ],
            options={
                'verbose_name': 'ISO 27002 Theme Translation',
                'verbose_name_plural': 'ISO 27002 Theme Translations',
                'ordering': ['country__name'],
                'unique_together': {('theme', 'country')},
            },
        ),
        migrations.CreateModel(
            name='PCIDSSCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(help_text="Category name in country's language", max_length=255, verbose_name='Local Name')),
                ('description', models.TextField(blank=True, help_text="Description in country's language", verbose_name='Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_std.pcidsscategory', verbose_name='PCI DSS Standard')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcidss_category_translations', to='app_conf.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'PCI DSS Standard Translation',
                'verbose_name_plural': 'PCI DSS Standard Translations',
                'ordering': ['country__name'],
                'unique_together': {('category', 'country')},
            },
        ),
        migrations.CreateModel(
            name='PCIDSSRequirementTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('definitions', models.TextField(blank=True, default='', verbose_name='Definitions')),
                ('purpose', models.TextField(blank=True, default='', verbose_name='Purpose')),
                ('good_practice', models.TextField(blank=True, default='', verbose_name='Good Practice')),
                ('examples', models.TextField(blank=True, default='', verbose_name='Examples')),
                ('testing_procedures', models.TextField(blank=True, default='', verbose_name='Testing Procedures')),
                ('customized_approach_objective', models.TextField(blank=True, default='', verbose_name='Customized Approach Objective')),
                ('applicability_notes', models.TextField(blank=True, default='', verbose_name='Applicability Notes')),
                ('further_information', models.TextField(blank=True, default='', verbose_name='Further Information')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcidss_requirement_translations', to='app_conf.country', verbose_name='Country')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_std.pcidssrequirement', verbose_name='Requirement')),
            ],
            options={
                'verbose_name': 'PCI DSS Requirement Translation',
                'verbose_name_plural': 'PCI DSS Requirement Translations',
                'ordering': ['country__name'],
                'unique_together': {('requirement', 'country')},
            },
        ),
    ]
