# Generated by Django 5.2.8 on 2026-06-24 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_asset', '0002_initial'),
        ('app_cif', '0001_initial'),
        ('app_conf', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscif',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='Companies this group can access. Leave empty for all companies.', related_name='access_cif', to='app_conf.company', verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='accesscif',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='cifcriticalfunction',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_cif_functions', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='cifcriticalfunction',
            name='related_assets',
            field=models.ManyToManyField(blank=True, related_name='cif_critical_functions', to='app_asset.informationasset', verbose_name='Related assets'),
        ),
        migrations.AddField(
            model_name='cifobject',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cif_objects', to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='cifobject',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_cif_objects', to=settings.AUTH_USER_MODEL, verbose_name='Responsible person'),
        ),
        migrations.AddField(
            model_name='cifcriticalfunction',
            name='cif_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_functions', to='app_cif.cifobject', verbose_name='CIF object'),
        ),
        migrations.AddField(
            model_name='cifpassport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cif_passports', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AddField(
            model_name='cifpassport',
            name='cif_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='app_cif.cifobject', verbose_name='CIF object'),
        ),
        migrations.AddField(
            model_name='cifpassport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cif_passports', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
