# Generated by Django 5.2.8 on 2026-06-24 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cabinet', '0002_initial'),
        ('app_cif', '0002_initial'),
        ('app_compliance', '0002_initial'),
        ('app_conf', '0001_initial'),
        ('app_doc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cifprotectionmeasure',
            name='evidence_files',
            field=models.ManyToManyField(blank=True, related_name='cif_measures', to='app_doc.registerdocs', verbose_name='Evidence files'),
        ),
        migrations.AddField(
            model_name='cifprotectionmeasure',
            name='related_compliance_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cif_measures', to='app_compliance.control', verbose_name='Related compliance control'),
        ),
        migrations.AddField(
            model_name='cifprotectionmeasure',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cif_responsible_measures', to=settings.AUTH_USER_MODEL, verbose_name='Responsible'),
        ),
        migrations.AddField(
            model_name='cifprotectionmeasure',
            name='responsible_cabinet_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cif_responsible_measures', to='app_cabinet.cabinetuser', verbose_name='Responsible cabinet user'),
        ),
        migrations.AddField(
            model_name='cifprotectionplan',
            name='cif_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protection_plan', to='app_cif.cifobject', verbose_name='CIF object'),
        ),
        migrations.AddField(
            model_name='cifprotectionplan',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_cif_plans', to=settings.AUTH_USER_MODEL, verbose_name='Responsible person'),
        ),
        migrations.AddField(
            model_name='cifprotectionmeasure',
            name='protection_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='app_cif.cifprotectionplan', verbose_name='Protection plan'),
        ),
        migrations.AddField(
            model_name='cifobject',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cif_objects', to='app_cif.cifsector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='cifsectortranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cif_sector_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='cifsectortranslation',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_cif.cifsector', verbose_name='Sector'),
        ),
        migrations.AlterUniqueTogether(
            name='accesscif',
            unique_together={('group',)},
        ),
        migrations.AddConstraint(
            model_name='cifprotectionmeasure',
            constraint=models.UniqueConstraint(fields=('protection_plan', 'class_code', 'measure_number'), name='cif_measure_unique_number_per_plan'),
        ),
        migrations.AlterUniqueTogether(
            name='cifsectortranslation',
            unique_together={('sector', 'country')},
        ),
    ]
