# Generated by Django 5.2.8 on 2026-06-24 09:44

import app_cabinet.models
import datetime
import django.core.validators
import encrypted_model_fields.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access_users', models.BooleanField(default=False, verbose_name='Has access to Users Management')),
                ('can_add_users', models.BooleanField(default=False, verbose_name='Can add Users')),
                ('can_edit_users', models.BooleanField(default=False, verbose_name='Can edit Users')),
                ('can_delete_users', models.BooleanField(default=False, verbose_name='Can delete Users')),
                ('can_export_users', models.BooleanField(default=False, verbose_name='Can export Users')),
                ('has_access_roles', models.BooleanField(default=False, verbose_name='Has access to Manage Roles')),
                ('can_add_roles', models.BooleanField(default=False, verbose_name='Can add Roles')),
                ('can_edit_roles', models.BooleanField(default=False, verbose_name='Can edit Roles')),
                ('can_delete_roles', models.BooleanField(default=False, verbose_name='Can delete Roles')),
                ('has_access_groups', models.BooleanField(default=False, verbose_name='Has access to Groups Management')),
                ('can_add_groups', models.BooleanField(default=False, verbose_name='Can add Groups')),
                ('can_edit_groups', models.BooleanField(default=False, verbose_name='Can edit Groups')),
                ('can_delete_groups', models.BooleanField(default=False, verbose_name='Can delete Groups')),
                ('has_access_org_structure', models.BooleanField(default=False, verbose_name='Has access to Organization Structure')),
                ('has_access_org_chart', models.BooleanField(default=False, verbose_name='Has access to org_chart')),
                ('can_add_companies', models.BooleanField(default=False, verbose_name='Can add Companies')),
                ('can_edit_companies', models.BooleanField(default=False, verbose_name='Can edit Companies')),
                ('can_delete_companies', models.BooleanField(default=False, verbose_name='Can delete Companies')),
                ('can_add_departments', models.BooleanField(default=False, verbose_name='Can add Departments')),
                ('can_edit_departments', models.BooleanField(default=False, verbose_name='Can edit Departments')),
                ('can_delete_departments', models.BooleanField(default=False, verbose_name='Can delete Departments')),
                ('can_add_positions', models.BooleanField(default=False, verbose_name='Can add Positions')),
                ('can_edit_positions', models.BooleanField(default=False, verbose_name='Can edit Positions')),
                ('can_delete_positions', models.BooleanField(default=False, verbose_name='Can delete Positions')),
                ('has_access_site_statistics', models.BooleanField(default=False, verbose_name='Has access to Site Statistics')),
                ('can_export_statistics', models.BooleanField(default=False, verbose_name='Can export Statistics')),
                ('can_view_detailed_statistics', models.BooleanField(default=False, verbose_name='Can view detailed Statistics')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Access to Cabinet Management',
                'verbose_name_plural': 'Access to Cabinet Management',
            },
        ),
        migrations.CreateModel(
            name='CabinetADConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this AD connection', max_length=255, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('server_url', models.CharField(help_text='LDAP server hostname or IP (e.g. dc.company.com)', max_length=255, verbose_name='Server URL')),
                ('port', models.PositiveIntegerField(default=389, help_text='389 for LDAP, 636 for LDAPS', verbose_name='Port')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Use SSL (LDAPS)')),
                ('bind_dn', models.CharField(help_text='DN of service account for directory search (e.g. CN=svc_ldap,OU=Service,DC=company,DC=com)', max_length=512, verbose_name='Bind DN')),
                ('bind_password', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Bind password')),
                ('base_dn', models.CharField(help_text='Base DN for user search (e.g. DC=company,DC=com)', max_length=512, verbose_name='Base DN')),
                ('user_search_ou', models.CharField(blank=True, help_text='Optional OU under base_dn to restrict user search (e.g. OU=Users)', max_length=512, verbose_name='User search OU')),
                ('user_filter', models.CharField(default='(objectClass=user)', help_text='LDAP filter for user objects (e.g. (objectClass=user))', max_length=255, verbose_name='User object filter')),
                ('attr_username', models.CharField(default='sAMAccountName', help_text='Attribute for login name (sAMAccountName or userPrincipalName)', max_length=64, verbose_name='Username attribute')),
                ('attr_email', models.CharField(default='mail', max_length=64, verbose_name='Email attribute')),
                ('attr_first_name', models.CharField(blank=True, default='givenName', max_length=64, verbose_name='First name attribute')),
                ('attr_last_name', models.CharField(blank=True, default='sn', max_length=64, verbose_name='Last name attribute')),
                ('attr_phone', models.CharField(blank=True, default='telephoneNumber', help_text='AD attribute for phone (e.g. telephoneNumber, mobile)', max_length=64, verbose_name='Phone attribute')),
                ('attr_start_date', models.CharField(blank=True, help_text='AD attribute for start date (e.g. whenCreated, or custom). LDAP generalized time (YYYYMMDDHHMMSS.0Z) or ISO date.', max_length=64, verbose_name='Start date attribute')),
                ('attr_end_date', models.CharField(blank=True, help_text='AD attribute for end date (e.g. accountExpires for expiry, or custom). Use blank to not sync.', max_length=64, verbose_name='End date attribute')),
                ('sync_ad_groups_to_cabinet', models.BooleanField(default=False, help_text="When enabled, on each AD login or refresh users are automatically added to Cabinet groups whose name matches one of their AD Member of groups (within the user's company or global groups).", verbose_name='Sync AD groups to Cabinet groups')),
            ],
            options={
                'verbose_name': 'Cabinet AD Connection',
                'verbose_name_plural': 'Cabinet AD Connections',
            },
        ),
        migrations.CreateModel(
            name='CabinetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Cabinet Group Details',
                'verbose_name_plural': 'Cabinet Group Details',
            },
        ),
        migrations.CreateModel(
            name='CabinetGroupsGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'Cabinet Groups Guide',
                'verbose_name_plural': 'Cabinet Groups Guides',
            },
        ),
        migrations.CreateModel(
            name='CabinetGroupsGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Cabinet Groups Guide Translation',
                'verbose_name_plural': 'Cabinet Groups Guide Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='CabinetPasswordCompanyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_password', models.CharField(max_length=50, verbose_name='Control Word')),
            ],
            options={
                'verbose_name': 'Control Word',
                'verbose_name_plural': 'Control Words',
            },
        ),
        migrations.CreateModel(
            name='CabinetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Cabinet Settings',
                'verbose_name_plural': 'Cabinet Settings',
            },
        ),
        migrations.CreateModel(
            name='CabinetTaskReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=16, verbose_name='Frequency')),
                ('send_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Send time')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, help_text='For weekly schedule: 0 = Monday, 6 = Sunday', null=True, verbose_name='Weekday')),
                ('month_day', models.PositiveSmallIntegerField(blank=True, help_text='For monthly schedule: day of month (1–31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Day of month')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Last sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Cabinet task reminder schedule',
                'verbose_name_plural': 'Cabinet task reminder schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CabinetUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_profile_completed', models.BooleanField(default=False, verbose_name='Profile Completed')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Your Telegram Chat ID from the SecBoard bot (tap Help in the bot to see it).', max_length=64, verbose_name='Telegram Chat ID')),
                ('telegram_link_token', models.CharField(blank=True, help_text='Secret token for Telegram deep-link account linking.', max_length=64, null=True, unique=True, verbose_name='Telegram link token')),
                ('preferred_language', models.CharField(blank=True, help_text='Preferred interface language for this user.', max_length=10, verbose_name='Default language')),
                ('avatar', models.ImageField(blank=True, max_length=255, null=True, upload_to=app_cabinet.models.cabinet_user_avatar_upload_to, verbose_name='Avatar')),
                ('start_date', models.DateTimeField(blank=True, help_text='When the user started their position', null=True, verbose_name='Start Date')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Color')),
                ('end_date', models.DateTimeField(blank=True, help_text='When the user ended their position', null=True, verbose_name='End Date')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='Two-Factor Authentication Enabled')),
                ('two_factor_secret', models.CharField(blank=True, max_length=64, verbose_name='Two-Factor Secret')),
                ('two_factor_temp_secret', models.CharField(blank=True, max_length=64, verbose_name='Two-Factor Temporary Secret')),
                ('two_factor_temp_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Two-Factor Temporary Secret Created At')),
                ('two_factor_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Two-Factor Confirmed At')),
                ('two_factor_backup_codes', models.JSONField(blank=True, default=list, verbose_name='Two-Factor Backup Codes')),
                ('two_factor_last_used', models.DateTimeField(blank=True, null=True, verbose_name='Two-Factor Last Used')),
                ('force_two_factor', models.BooleanField(default=False, verbose_name='Require Two-Factor Authentication')),
                ('is_ad_synced', models.BooleanField(default=False, help_text='User is provisioned from Active Directory; profile fields are updated on each AD login.', verbose_name='Synced from AD')),
                ('ad_extra_attributes', models.JSONField(blank=True, default=dict, help_text='Additional attributes from AD (General, Address, Telephones, etc.) stored at last login.', verbose_name='AD extra attributes')),
            ],
            options={
                'verbose_name': 'Cabinet User',
            },
        ),
        migrations.CreateModel(
            name='CabinetUsersGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'Cabinet Users Guide',
                'verbose_name_plural': 'Cabinet Users Guides',
            },
        ),
        migrations.CreateModel(
            name='CabinetUsersGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Cabinet Users Guide Translation',
                'verbose_name_plural': 'Cabinet Users Guide Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Department name.', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Department description.', verbose_name='Description')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Color')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='OrgStructureGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'Organization Structure Guide',
                'verbose_name_plural': 'Organization Structure Guides',
            },
        ),
        migrations.CreateModel(
            name='OrgStructureGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Organization Structure Guide Translation',
                'verbose_name_plural': 'Organization Structure Guide Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Color')),
                ('allowed_metrics_modules', models.JSONField(blank=True, default=list, help_text='List of module/metric codes this role can see (e.g. site_statistics, incidents).', verbose_name='Allowed metrics and modules')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Platform Role',
                'verbose_name_plural': 'Platform Roles',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformRoleDashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(blank=True, default=dict, help_text='JSON: sections list, each with id, enabled, widgets list. e.g. {"sections": [{"id": "top_panel", "enabled": true, "widgets": ["security_index", ...]}]}', verbose_name='Dashboard config')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Platform Role Dashboard Config',
                'verbose_name_plural': 'Platform Role Dashboard Configs',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Position name.', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Position description.', verbose_name='Description')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view_page', 'View Page'), ('update_profile', 'Update Profile'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('failed_login', 'Failed Login Attempt')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.TextField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-login_time'],
            },
        ),
    ]
