# Generated by Django 5.2.8 on 2026-04-01 08:25

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cabinet', '0001_initial'),
        ('app_conf', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_celery_beat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoptions',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='access_options', to='app_conf.company', verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='accessoptions',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='cabinetadconnection',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_connection', to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='cabinetgroup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='cabinetgroup',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_details', to='auth.group'),
        ),
        migrations.AddField(
            model_name='cabinetgroupsguidetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_groups_guide_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='cabinetgroupsguidetranslation',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_cabinet.cabinetgroupsguide', verbose_name='Guide'),
        ),
        migrations.AddField(
            model_name='cabinetpasswordcompanylink',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='cabinetsettings',
            name='mail_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_conf.mailaccount', verbose_name='Mail Account'),
        ),
        migrations.AddField(
            model_name='cabinetpasswordcompanylink',
            name='cabinet_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_links', to='app_cabinet.cabinetsettings', verbose_name='Cabinet Settings'),
        ),
        migrations.AddField(
            model_name='cabinettaskreminderschedule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_task_reminder_schedules', to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='cabinettaskreminderschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cabinet_task_reminder_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='cabinettaskreminderschedule',
            name='periodic_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask', verbose_name='Periodic task'),
        ),
        migrations.AddField(
            model_name='cabinetuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='cabinetuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='cabinettaskreminderschedule',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='task_reminder_schedules', to='app_cabinet.cabinetuser', verbose_name='Recipients'),
        ),
        migrations.AddField(
            model_name='cabinetusersguidetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_users_guide_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='cabinetusersguidetranslation',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_cabinet.cabinetusersguide', verbose_name='Guide'),
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_cabinet.department', verbose_name='Parent Department'),
        ),
        migrations.AddField(
            model_name='cabinetuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cabinet.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='orgstructureguidetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_structure_guide_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='orgstructureguidetranslation',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_cabinet.orgstructureguide', verbose_name='Guide'),
        ),
        migrations.AddField(
            model_name='platformrole',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='platform_roles', to='app_conf.company', verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='platformrole',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='platform_roles', to='auth.group', verbose_name='Access Groups'),
        ),
        migrations.AddField(
            model_name='cabinetuser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='cabinet_users', to='app_cabinet.platformrole', verbose_name='Platform Roles'),
        ),
        migrations.AddField(
            model_name='platformroledashboardconfig',
            name='platform_role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to='app_cabinet.platformrole', verbose_name='Platform Role'),
        ),
        migrations.AddField(
            model_name='position',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cabinet.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='position',
            name='parent_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_positions', to='app_cabinet.position', verbose_name='Parent Position'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='app_cabinet.position', verbose_name='Parent Position'),
        ),
        migrations.AddField(
            model_name='cabinetuser',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cabinet.position', verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cabinet.usersession'),
        ),
        migrations.AlterUniqueTogether(
            name='accessoptions',
            unique_together={('group',)},
        ),
        migrations.AlterUniqueTogether(
            name='cabinetgroupsguidetranslation',
            unique_together={('guide', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='cabinetpasswordcompanylink',
            unique_together={('cabinet_settings', 'cabinet_password')},
        ),
        migrations.AlterUniqueTogether(
            name='cabinetusersguidetranslation',
            unique_together={('guide', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='orgstructureguidetranslation',
            unique_together={('guide', 'country')},
        ),
    ]
