# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cabinet', '0002_initial'),
        ('app_conf', '0002_add_demo_credentials_to_site_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetADConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this AD connection', max_length=255, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('server_url', models.CharField(help_text='LDAP server hostname or IP (e.g. dc.company.com)', max_length=255, verbose_name='Server URL')),
                ('port', models.PositiveIntegerField(default=389, help_text='389 for LDAP, 636 for LDAPS', verbose_name='Port')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Use SSL (LDAPS)')),
                ('bind_dn', models.CharField(help_text='DN of service account for directory search (e.g. CN=svc_ldap,OU=Service,DC=company,DC=com)', max_length=512, verbose_name='Bind DN')),
                ('bind_password', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Bind password')),
                ('base_dn', models.CharField(help_text='Base DN for user search (e.g. DC=company,DC=com)', max_length=512, verbose_name='Base DN')),
                ('user_search_ou', models.CharField(blank=True, help_text='Optional OU under base_dn to restrict user search (e.g. OU=Users)', max_length=512, verbose_name='User search OU')),
                ('user_filter', models.CharField(default='(objectClass=user)', help_text='LDAP filter for user objects (e.g. (objectClass=user))', max_length=255, verbose_name='User object filter')),
                ('attr_username', models.CharField(default='sAMAccountName', help_text='Attribute for login name (sAMAccountName or userPrincipalName)', max_length=64, verbose_name='Username attribute')),
                ('attr_email', models.CharField(default='mail', max_length=64, verbose_name='Email attribute')),
                ('attr_first_name', models.CharField(blank=True, default='givenName', max_length=64, verbose_name='First name attribute')),
                ('attr_last_name', models.CharField(blank=True, default='sn', max_length=64, verbose_name='Last name attribute')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_connection', to='app_conf.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Cabinet AD Connection',
                'verbose_name_plural': 'Cabinet AD Connections',
            },
        ),
    ]
