# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cabinet', '0003_add_cabinet_ad_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetadconnection',
            name='attr_end_date',
            field=models.CharField(blank=True, help_text='AD attribute for end date (e.g. accountExpires for expiry, or custom). Use blank to not sync.', max_length=64, verbose_name='End date attribute'),
        ),
        migrations.AddField(
            model_name='cabinetadconnection',
            name='attr_phone',
            field=models.CharField(blank=True, default='telephoneNumber', help_text='AD attribute for phone (e.g. telephoneNumber, mobile)', max_length=64, verbose_name='Phone attribute'),
        ),
        migrations.AddField(
            model_name='cabinetadconnection',
            name='attr_start_date',
            field=models.CharField(blank=True, help_text='AD attribute for start date (e.g. whenCreated, or custom). LDAP generalized time (YYYYMMDDHHMMSS.0Z) or ISO date.', max_length=64, verbose_name='Start date attribute'),
        ),
    ]
