# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cabinet', '0004_ad_connection_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetuser',
            name='is_ad_synced',
            field=models.BooleanField(default=False, help_text='User is provisioned from Active Directory; profile fields are updated on each AD login.', verbose_name='Synced from AD'),
        ),
    ]
