# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cabinet', '0005_cabinet_user_is_ad_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetuser',
            name='ad_extra_attributes',
            field=models.JSONField(default=dict, verbose_name='AD extra attributes'),
        ),
    ]
