# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cabinet', '0006_cabinetuser_ad_extra_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetadconnection',
            name='sync_ad_groups_to_cabinet',
            field=models.BooleanField(default=False, help_text="When enabled, on each AD login or refresh users are automatically added to Cabinet groups whose name matches one of their AD Member of groups (within the user's company or global groups).", verbose_name='Sync AD groups to Cabinet groups'),
        ),
        migrations.AlterField(
            model_name='cabinetuser',
            name='ad_extra_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Additional attributes from AD (General, Address, Telephones, etc.) stored at last login.', verbose_name='AD extra attributes'),
        ),
    ]
