# Generated by Django 5.2.8 on 2026-06-10 10:40

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cabinet', '0007_add_sync_ad_groups_to_cabinet'),
        ('app_conf', '0002_add_demo_credentials_to_site_settings'),
        ('auth', '__first__'),
        ('django_celery_beat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetTaskReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=16, verbose_name='Frequency')),
                ('send_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Send time')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, help_text='For weekly schedule: 0 = Monday, 6 = Sunday', null=True, verbose_name='Weekday')),
                ('month_day', models.PositiveSmallIntegerField(blank=True, help_text='For monthly schedule: day of month (1–31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Day of month')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Last sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_task_reminder_schedules', to='app_conf.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cabinet_task_reminder_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask', verbose_name='Periodic task')),
                ('recipients', models.ManyToManyField(blank=True, related_name='task_reminder_schedules', to='app_cabinet.cabinetuser', verbose_name='Recipients')),
            ],
            options={
                'verbose_name': 'Cabinet task reminder schedule',
                'verbose_name_plural': 'Cabinet task reminder schedules',
                'ordering': ['-created_at'],
            },
        ),
    ]
