# Generated by Django 5.2.8 on 2026-06-24 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_compliance', '0001_initial'),
        ('app_conf', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscompliance',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='Companies this group can access. Leave empty for all companies.', related_name='access_compliance', to='app_conf.company', verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='accesscompliance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='accesscontrolmapping',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='Companies this group can access. Leave empty for all companies.', related_name='access_control_mappings', to='app_conf.company', verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='accesscontrolmapping',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='accessinternalcompliance',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='Companies this group can access. Leave empty for all companies.', related_name='access_internal_compliance', to='app_conf.company', verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='accessinternalcompliance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='accesslocalcompliance',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='Companies this group can access. Leave empty for all companies.', related_name='access_local_compliance', to='app_conf.company', verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='accesslocalcompliance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='companytype',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='Companies of this type', related_name='compliance_company_types', to='app_conf.company', verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='complianceauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='complianceframework',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this framework instance applies to (null for templates)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_frameworks', to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='complianceframework',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_frameworks', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='complianceframework',
            name='review_owner',
            field=models.ForeignKey(blank=True, help_text='Person responsible for framework reviews', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_framework_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Review Owner'),
        ),
        migrations.AddField(
            model_name='complianceframework',
            name='template',
            field=models.ForeignKey(blank=True, help_text='The template this framework is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='app_compliance.complianceframework', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='control',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_controls', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='control',
            name='parent_control',
            field=models.ForeignKey(blank=True, help_text='For hierarchical controls (e.g., 1.1.1 is sub-control of 1.1)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_controls', to='app_compliance.control', verbose_name='Parent Control'),
        ),
        migrations.AddField(
            model_name='control',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_controls', to=settings.AUTH_USER_MODEL, verbose_name='Responsible'),
        ),
        migrations.AddField(
            model_name='control',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_controls', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
        migrations.AddField(
            model_name='controlassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AddField(
            model_name='controlassignment',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app_compliance.control', verbose_name='Control'),
        ),
        migrations.AddField(
            model_name='controlassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_assignments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='controlcategory',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app_compliance.complianceframework', verbose_name='Framework'),
        ),
        migrations.AddField(
            model_name='control',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='app_compliance.controlcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='controlmapping',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='controlmapping',
            name='source_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapped_to', to='app_compliance.control', verbose_name='Source Control'),
        ),
        migrations.AddField(
            model_name='controlmapping',
            name='target_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapped_from', to='app_compliance.control', verbose_name='Target Framework Control'),
        ),
        migrations.AddField(
            model_name='controlnote',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app_compliance.control', verbose_name='Control'),
        ),
        migrations.AddField(
            model_name='controlnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='controlnoteattachment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app_compliance.controlnote', verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='app_compliance.control', verbose_name='Control'),
        ),
    ]
