# Generated by Django 5.2.8 on 2026-06-24 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_compliance', '0002_initial'),
        ('app_conf', '0001_initial'),
        ('app_doc', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='register_document',
            field=models.ForeignKey(blank=True, help_text='Link to a document from Document Register', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='framework_control_evidences', to='app_doc.registerdocs', verbose_name='Register Document'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='related_document',
            field=models.ForeignKey(blank=True, help_text='Link to a related document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='framework_control_evidences', to='app_doc.relateddocs', verbose_name='Related Document'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_evidences', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidences', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='evidence_type',
            field=models.ForeignKey(blank=True, help_text='Type of evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='app_compliance.evidencetype', verbose_name='Evidence Type'),
        ),
        migrations.AddField(
            model_name='evidencetypetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_type_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='evidencetypetranslation',
            name='evidence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_compliance.evidencetype', verbose_name='Evidence Type'),
        ),
        migrations.AddField(
            model_name='frameworkcomplianceguidetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_compliance_guide_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='frameworkcomplianceguidetranslation',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_compliance.frameworkcomplianceguide', verbose_name='Guide'),
        ),
        migrations.AddField(
            model_name='control',
            name='domain',
            field=models.ForeignKey(blank=True, help_text='Control domain (e.g., NETWORK_SECURITY, CRYPTOGRAPHIC_PROTECTIONS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls', to='app_compliance.frameworkdomain', verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='frameworkinstancenote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='framework_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='frameworkinstancenote',
            name='framework',
            field=models.ForeignKey(help_text='Framework instance this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app_compliance.complianceframework', verbose_name='Framework'),
        ),
        migrations.AddField(
            model_name='frameworkinstancenoteattachment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app_compliance.frameworkinstancenote', verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='internalcompliancecontrol',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this control applies to (null for template controls)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_compliance_controls', to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='internalcompliancecontrol',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_internal_controls', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='internalcompliancecontrol',
            name='related_framework_control',
            field=models.ForeignKey(blank=True, help_text='Link to related international framework control', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_compliance_mappings', to='app_compliance.control', verbose_name='Related Framework Control'),
        ),
        migrations.AddField(
            model_name='internalcompliancecontrol',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_compliance_controls', to=settings.AUTH_USER_MODEL, verbose_name='Responsible'),
        ),
        migrations.AddField(
            model_name='internalcompliancecontrol',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_internal_controls', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
        migrations.AddField(
            model_name='controlmapping',
            name='target_internal_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='framework_control_mappings', to='app_compliance.internalcompliancecontrol', verbose_name='Target Internal Control'),
        ),
        migrations.AddField(
            model_name='internalcomplianceguidetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_compliance_guide_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='internalcomplianceguidetranslation',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_compliance.internalcomplianceguide', verbose_name='Guide'),
        ),
        migrations.AddField(
            model_name='internalcompliancerequirement',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this requirement instance belongs to (empty for templates)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_compliance_requirements', to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='internalcompliancerequirement',
            name='company_types',
            field=models.ManyToManyField(blank=True, help_text='Company types this requirement applies to', related_name='internal_requirements', to='app_conf.companytype', verbose_name='Company Types'),
        ),
        migrations.AddField(
            model_name='internalcompliancerequirement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_internal_requirements', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='internalcompliancerequirement',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Document from Document Registry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_compliance_requirements', to='app_doc.registerdocs', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='internalcompliancerequirement',
            name='template',
            field=models.ForeignKey(blank=True, help_text='The template this requirement is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='app_compliance.internalcompliancerequirement', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='internalcompliancecontrol',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='app_compliance.internalcompliancerequirement', verbose_name='Requirement'),
        ),
        migrations.AddField(
            model_name='internalcompliancesource',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='Companies this source applies to', related_name='internal_sources', to='app_conf.company', verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='internalcompliancesource',
            name='company_types',
            field=models.ManyToManyField(blank=True, help_text='Types of companies this source applies to', related_name='internal_sources', to='app_compliance.companytype', verbose_name='Company Types'),
        ),
        migrations.AddField(
            model_name='internalcompliancesource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_internal_sources', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='internalcompliancerequirement',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='app_compliance.internalcompliancesource', verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='internalcontrolassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AddField(
            model_name='internalcontrolassignment',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app_compliance.internalcompliancecontrol', verbose_name='Internal Control'),
        ),
        migrations.AddField(
            model_name='internalcontrolassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_control_assignments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='internalcontrolevidence',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='app_compliance.internalcompliancecontrol', verbose_name='Internal Control'),
        ),
        migrations.AddField(
            model_name='internalcontrolevidence',
            name='evidence_type',
            field=models.ForeignKey(blank=True, help_text='Type of evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_control_evidences', to='app_compliance.evidencetype', verbose_name='Evidence Type'),
        ),
        migrations.AddField(
            model_name='internalcontrolevidence',
            name='register_document',
            field=models.ForeignKey(blank=True, help_text='Link to a document from Document Register', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_control_evidences', to='app_doc.registerdocs', verbose_name='Register Document'),
        ),
        migrations.AddField(
            model_name='internalcontrolevidence',
            name='related_document',
            field=models.ForeignKey(blank=True, help_text='Link to a related document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_control_evidences', to='app_doc.relateddocs', verbose_name='Related Document'),
        ),
        migrations.AddField(
            model_name='internalcontrolevidence',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_internal_evidences', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='internalcontrolevidence',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_internal_evidences', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AddField(
            model_name='internalcontrolmapping',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='internalcontrolmapping',
            name='internal_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='app_compliance.internalcompliancecontrol', verbose_name='Internal Control'),
        ),
        migrations.AddField(
            model_name='internalcontrolmapping',
            name='target_framework_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_control_mappings', to='app_compliance.control', verbose_name='Target Framework Control'),
        ),
        migrations.AddField(
            model_name='internalcontrolmapping',
            name='target_internal_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_mappings', to='app_compliance.internalcompliancecontrol', verbose_name='Target Internal Control'),
        ),
        migrations.AddField(
            model_name='internalcontrolnote',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app_compliance.internalcompliancecontrol', verbose_name='Internal Control'),
        ),
        migrations.AddField(
            model_name='internalcontrolnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_control_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='internalcontrolnoteattachment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app_compliance.internalcontrolnote', verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='internalrequirementcategory',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app_compliance.internalcompliancerequirement', verbose_name='Requirement'),
        ),
        migrations.AddField(
            model_name='internalcompliancecontrol',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls', to='app_compliance.internalrequirementcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='internalrequirementnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_requirement_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='internalrequirementnote',
            name='requirement',
            field=models.ForeignKey(help_text='Requirement this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app_compliance.internalcompliancerequirement', verbose_name='Requirement'),
        ),
        migrations.AddField(
            model_name='internalrequirementnoteattachment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app_compliance.internalrequirementnote', verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='localcompliancecontrol',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this control applies to (null for template controls)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_compliance_controls', to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='localcompliancecontrol',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_local_controls', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='localcompliancecontrol',
            name='related_framework_control',
            field=models.ForeignKey(blank=True, help_text='Link to related international framework control', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_compliance_mappings', to='app_compliance.control', verbose_name='Related Framework Control'),
        ),
        migrations.AddField(
            model_name='localcompliancecontrol',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_compliance_controls', to=settings.AUTH_USER_MODEL, verbose_name='Responsible'),
        ),
        migrations.AddField(
            model_name='localcompliancecontrol',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_local_controls', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
        migrations.AddField(
            model_name='internalcontrolmapping',
            name='target_local_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_control_mappings', to='app_compliance.localcompliancecontrol', verbose_name='Target Local Control'),
        ),
        migrations.AddField(
            model_name='controlmapping',
            name='target_local_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='framework_control_mappings', to='app_compliance.localcompliancecontrol', verbose_name='Target Local Control'),
        ),
        migrations.AddField(
            model_name='localcomplianceguidetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_compliance_guide_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='localcomplianceguidetranslation',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_compliance.localcomplianceguide', verbose_name='Guide'),
        ),
        migrations.AddField(
            model_name='localcomplianceregulator',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='Companies regulated by this regulator', related_name='local_regulators', to='app_conf.company', verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='localcomplianceregulator',
            name='company_types',
            field=models.ManyToManyField(blank=True, help_text='Types of companies this regulator oversees (e.g., Banks, Payment Systems)', related_name='local_regulators', to='app_compliance.companytype', verbose_name='Company Types'),
        ),
        migrations.AddField(
            model_name='localcomplianceregulator',
            name='country',
            field=models.ForeignKey(help_text='Country of the regulator', on_delete=django.db.models.deletion.PROTECT, related_name='regulators', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='localcomplianceregulator',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_regulators', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='localcompliancerequirement',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this requirement instance belongs to (empty for templates)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_compliance_requirements', to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='localcompliancerequirement',
            name='company_types',
            field=models.ManyToManyField(blank=True, help_text='Company types this requirement applies to', related_name='local_requirements', to='app_conf.companytype', verbose_name='Company Types'),
        ),
        migrations.AddField(
            model_name='localcompliancerequirement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_local_requirements', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='localcompliancerequirement',
            name='regulator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='app_compliance.localcomplianceregulator', verbose_name='Regulator'),
        ),
        migrations.AddField(
            model_name='localcompliancerequirement',
            name='template',
            field=models.ForeignKey(blank=True, help_text='The template this requirement is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='app_compliance.localcompliancerequirement', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='localcompliancecontrol',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='app_compliance.localcompliancerequirement', verbose_name='Requirement'),
        ),
        migrations.AddField(
            model_name='localcontrolassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AddField(
            model_name='localcontrolassignment',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app_compliance.localcompliancecontrol', verbose_name='Local Control'),
        ),
        migrations.AddField(
            model_name='localcontrolassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_control_assignments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='localcontrolevidence',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='app_compliance.localcompliancecontrol', verbose_name='Local Control'),
        ),
        migrations.AddField(
            model_name='localcontrolevidence',
            name='evidence_type',
            field=models.ForeignKey(blank=True, help_text='Type of evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_control_evidences', to='app_compliance.evidencetype', verbose_name='Evidence Type'),
        ),
        migrations.AddField(
            model_name='localcontrolevidence',
            name='register_document',
            field=models.ForeignKey(blank=True, help_text='Document from main document register used as evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_control_evidences', to='app_doc.registerdocs', verbose_name='Register Document'),
        ),
        migrations.AddField(
            model_name='localcontrolevidence',
            name='related_document',
            field=models.ForeignKey(blank=True, help_text='Related document used as evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_control_evidences', to='app_doc.relateddocs', verbose_name='Related Document'),
        ),
        migrations.AddField(
            model_name='localcontrolevidence',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_local_evidences', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='localcontrolevidence',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_local_evidences', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AddField(
            model_name='localcontrolmapping',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='localcontrolmapping',
            name='local_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='app_compliance.localcompliancecontrol', verbose_name='Local Control'),
        ),
        migrations.AddField(
            model_name='localcontrolmapping',
            name='target_framework_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_control_mappings', to='app_compliance.control', verbose_name='Target Framework Control'),
        ),
        migrations.AddField(
            model_name='localcontrolmapping',
            name='target_internal_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_control_mappings', to='app_compliance.internalcompliancecontrol', verbose_name='Target Internal Control'),
        ),
        migrations.AddField(
            model_name='localcontrolmapping',
            name='target_local_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_mappings', to='app_compliance.localcompliancecontrol', verbose_name='Target Local Control'),
        ),
        migrations.AddField(
            model_name='localcontrolnote',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app_compliance.localcompliancecontrol', verbose_name='Local Control'),
        ),
        migrations.AddField(
            model_name='localcontrolnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_control_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='localcontrolnoteattachment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app_compliance.localcontrolnote', verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='localrequirementcategory',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app_compliance.localcompliancerequirement', verbose_name='Requirement'),
        ),
        migrations.AddField(
            model_name='localcompliancecontrol',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls', to='app_compliance.localrequirementcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='localrequirementnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_requirement_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='localrequirementnote',
            name='requirement',
            field=models.ForeignKey(help_text='Requirement this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app_compliance.localcompliancerequirement', verbose_name='Requirement'),
        ),
        migrations.AddField(
            model_name='localrequirementnoteattachment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app_compliance.localrequirementnote', verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='mandatoryprocess',
            name='access_users',
            field=models.ManyToManyField(blank=True, help_text='Cabinet users that can view this process. If both groups and access users are empty, access is not regulated.', related_name='mandatory_process_access_records', to=settings.AUTH_USER_MODEL, verbose_name='Access Users'),
        ),
        migrations.AddField(
            model_name='mandatoryprocess',
            name='additional_person',
            field=models.ManyToManyField(blank=True, related_name='additional_processes', to=settings.AUTH_USER_MODEL, verbose_name='Additional Person'),
        ),
        migrations.AddField(
            model_name='mandatoryprocess',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='mandatoryprocess',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_processes', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='mandatoryprocess',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that can view and manage this process', to='auth.group', verbose_name='Access Groups'),
        ),
        migrations.AddField(
            model_name='mandatoryprocess',
            name='responsible_person',
            field=models.ManyToManyField(blank=True, related_name='responsible_processes', to=settings.AUTH_USER_MODEL, verbose_name='Responsible Person'),
        ),
        migrations.AddField(
            model_name='mandatoryprocess',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='Document that defines this process', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_doc.registerdocs', verbose_name='Source Document'),
        ),
        migrations.AddField(
            model_name='mandatoryprocess',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_processes', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='localcontrolevidence',
            name='mandatory_process',
            field=models.ForeignKey(blank=True, help_text='Link to a record from Mandatory Processes Registry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_control_evidences', to='app_compliance.mandatoryprocess', verbose_name='Mandatory Process'),
        ),
        migrations.AddField(
            model_name='internalcontrolevidence',
            name='mandatory_process',
            field=models.ForeignKey(blank=True, help_text='Link to a record from Mandatory Processes Registry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_control_evidences', to='app_compliance.mandatoryprocess', verbose_name='Mandatory Process'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='mandatory_process',
            field=models.ForeignKey(blank=True, help_text='Link to a record from Mandatory Processes Registry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='framework_control_evidences', to='app_compliance.mandatoryprocess', verbose_name='Mandatory Process'),
        ),
        migrations.AddField(
            model_name='mandatoryprocessesguidetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatory_processes_guide_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='mandatoryprocessesguidetranslation',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_compliance.mandatoryprocessesguide', verbose_name='Guide'),
        ),
        migrations.AddField(
            model_name='processattachment',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app_compliance.mandatoryprocess', verbose_name='Process'),
        ),
        migrations.AddField(
            model_name='processattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AddField(
            model_name='processevidencefile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_process_evidence_files', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='executed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Executed By'),
        ),
        migrations.AddField(
            model_name='processexecution',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='app_compliance.mandatoryprocess', verbose_name='Process'),
        ),
        migrations.AddField(
            model_name='processevidencefile',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='app_compliance.processexecution', verbose_name='Process Execution'),
        ),
        migrations.AddField(
            model_name='regulatortype',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='Companies regulated by this type of regulator', related_name='regulator_types', to='app_conf.company', verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='localcomplianceregulator',
            name='regulator_type',
            field=models.ForeignKey(help_text='Type of regulator', on_delete=django.db.models.deletion.PROTECT, related_name='regulators', to='app_compliance.regulatortype', verbose_name='Regulator'),
        ),
        migrations.AddField(
            model_name='regulatortypetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulator_type_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='regulatortypetranslation',
            name='regulator_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_compliance.regulatortype', verbose_name='Regulator Type'),
        ),
        migrations.AddField(
            model_name='requirementprioritytranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_priority_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='requirementprioritytranslation',
            name='requirement_priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_compliance.requirementpriority', verbose_name='Requirement Priority'),
        ),
        migrations.AddField(
            model_name='requirementstatustranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_status_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='requirementstatustranslation',
            name='requirement_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_compliance.requirementstatus', verbose_name='Requirement Status'),
        ),
        migrations.AddField(
            model_name='requirementtypetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_type_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='requirementtypetranslation',
            name='requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_compliance.requirementtype', verbose_name='Requirement Type'),
        ),
        migrations.AlterUniqueTogether(
            name='accesscompliance',
            unique_together={('group',)},
        ),
        migrations.AlterUniqueTogether(
            name='accesscontrolmapping',
            unique_together={('group',)},
        ),
        migrations.AlterUniqueTogether(
            name='accessinternalcompliance',
            unique_together={('group',)},
        ),
        migrations.AlterUniqueTogether(
            name='accesslocalcompliance',
            unique_together={('group',)},
        ),
        migrations.AddIndex(
            model_name='companytype',
            index=models.Index(fields=['code'], name='app_complia_code_300846_idx'),
        ),
        migrations.AddIndex(
            model_name='companytype',
            index=models.Index(fields=['is_active'], name='app_complia_is_acti_a524e8_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceauditlog',
            index=models.Index(fields=['-timestamp'], name='app_complia_timesta_f88db4_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceauditlog',
            index=models.Index(fields=['object_type', 'object_id'], name='app_complia_object__cac5dc_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceauditlog',
            index=models.Index(fields=['user', '-timestamp'], name='app_complia_user_id_b1dced_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceframework',
            index=models.Index(fields=['is_template'], name='app_complia_is_temp_0a1764_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceframework',
            index=models.Index(fields=['template'], name='app_complia_templat_18acf6_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceframework',
            index=models.Index(fields=['company'], name='app_complia_company_296eee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='controlassignment',
            unique_together={('control', 'user', 'assignment_type')},
        ),
        migrations.AlterUniqueTogether(
            name='controlcategory',
            unique_together={('framework', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='evidencetypetranslation',
            unique_together={('evidence_type', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='frameworkcomplianceguidetranslation',
            unique_together={('guide', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='control',
            unique_together={('category', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='internalcomplianceguidetranslation',
            unique_together={('guide', 'country')},
        ),
        migrations.AddIndex(
            model_name='internalcompliancesource',
            index=models.Index(fields=['is_active'], name='app_complia_is_acti_67ad31_idx'),
        ),
        migrations.AddIndex(
            model_name='internalcompliancesource',
            index=models.Index(fields=['source_type'], name='app_complia_source__45ae5f_idx'),
        ),
        migrations.AddIndex(
            model_name='internalcompliancerequirement',
            index=models.Index(fields=['source', 'status'], name='app_complia_source__abefb0_idx'),
        ),
        migrations.AddIndex(
            model_name='internalcompliancerequirement',
            index=models.Index(fields=['effective_date'], name='app_complia_effecti_9c2c82_idx'),
        ),
        migrations.AddIndex(
            model_name='internalcompliancerequirement',
            index=models.Index(fields=['deadline_date'], name='app_complia_deadlin_f8378b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='internalcontrolassignment',
            unique_together={('control', 'user', 'assignment_type')},
        ),
        migrations.AlterUniqueTogether(
            name='internalrequirementcategory',
            unique_together={('requirement', 'code')},
        ),
        migrations.AddIndex(
            model_name='internalcompliancecontrol',
            index=models.Index(fields=['company', 'status'], name='app_complia_company_38ec1d_idx'),
        ),
        migrations.AddIndex(
            model_name='internalcompliancecontrol',
            index=models.Index(fields=['responsible'], name='app_complia_respons_132d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='internalcompliancecontrol',
            index=models.Index(fields=['target_completion_date'], name='app_complia_target__33ed93_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='internalcontrolmapping',
            unique_together={('internal_control', 'target_internal_control', 'target_local_control', 'target_framework_control', 'mapping_type')},
        ),
        migrations.AlterUniqueTogether(
            name='controlmapping',
            unique_together={('source_control', 'target_control', 'target_internal_control', 'target_local_control', 'mapping_type')},
        ),
        migrations.AlterUniqueTogether(
            name='localcomplianceguidetranslation',
            unique_together={('guide', 'country')},
        ),
        migrations.AddIndex(
            model_name='localcompliancerequirement',
            index=models.Index(fields=['regulator', 'status'], name='app_complia_regulat_befb15_idx'),
        ),
        migrations.AddIndex(
            model_name='localcompliancerequirement',
            index=models.Index(fields=['effective_date'], name='app_complia_effecti_05056f_idx'),
        ),
        migrations.AddIndex(
            model_name='localcompliancerequirement',
            index=models.Index(fields=['deadline_date'], name='app_complia_deadlin_fedef5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='localcontrolassignment',
            unique_together={('control', 'user', 'assignment_type')},
        ),
        migrations.AlterUniqueTogether(
            name='localcontrolmapping',
            unique_together={('local_control', 'target_local_control', 'target_internal_control', 'target_framework_control', 'mapping_type')},
        ),
        migrations.AlterUniqueTogether(
            name='localrequirementcategory',
            unique_together={('requirement', 'code')},
        ),
        migrations.AddIndex(
            model_name='localcompliancecontrol',
            index=models.Index(fields=['company', 'status'], name='app_complia_company_712266_idx'),
        ),
        migrations.AddIndex(
            model_name='localcompliancecontrol',
            index=models.Index(fields=['responsible'], name='app_complia_respons_4daa63_idx'),
        ),
        migrations.AddIndex(
            model_name='localcompliancecontrol',
            index=models.Index(fields=['target_completion_date'], name='app_complia_target__50a1b4_idx'),
        ),
        migrations.AddIndex(
            model_name='mandatoryprocess',
            index=models.Index(fields=['next_due_date'], name='app_doc_man_next_du_d478ed_idx'),
        ),
        migrations.AddIndex(
            model_name='mandatoryprocess',
            index=models.Index(fields=['frequency'], name='app_doc_man_frequen_a55777_idx'),
        ),
        migrations.AddIndex(
            model_name='mandatoryprocess',
            index=models.Index(fields=['priority'], name='app_doc_man_priorit_7d455f_idx'),
        ),
        migrations.AddIndex(
            model_name='mandatoryprocess',
            index=models.Index(fields=['is_active'], name='app_doc_man_is_acti_4ecd10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mandatoryprocessesguidetranslation',
            unique_together={('guide', 'country')},
        ),
        migrations.AddIndex(
            model_name='processattachment',
            index=models.Index(fields=['process'], name='app_doc_pro_process_885c31_idx'),
        ),
        migrations.AddIndex(
            model_name='processattachment',
            index=models.Index(fields=['uploaded_at'], name='app_doc_pro_uploade_2a6bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='processexecution',
            index=models.Index(fields=['process'], name='app_doc_pro_process_aa86e1_idx'),
        ),
        migrations.AddIndex(
            model_name='processexecution',
            index=models.Index(fields=['execution_date'], name='app_doc_pro_executi_5692a2_idx'),
        ),
        migrations.AddIndex(
            model_name='processexecution',
            index=models.Index(fields=['status'], name='app_doc_pro_status_222979_idx'),
        ),
        migrations.AddIndex(
            model_name='processevidencefile',
            index=models.Index(fields=['execution'], name='app_doc_pro_executi_1406ce_idx'),
        ),
        migrations.AddIndex(
            model_name='processevidencefile',
            index=models.Index(fields=['uploaded_at'], name='app_doc_pro_uploade_b45126_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatortype',
            index=models.Index(fields=['code'], name='app_complia_code_4ec15a_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatortype',
            index=models.Index(fields=['is_active'], name='app_complia_is_acti_84fa9e_idx'),
        ),
        migrations.AddIndex(
            model_name='localcomplianceregulator',
            index=models.Index(fields=['country', 'is_active'], name='app_complia_country_1919c0_idx'),
        ),
        migrations.AddIndex(
            model_name='localcomplianceregulator',
            index=models.Index(fields=['regulator_type'], name='app_complia_regulat_01ccbc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='regulatortypetranslation',
            unique_together={('regulator_type', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='requirementprioritytranslation',
            unique_together={('requirement_priority', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='requirementstatustranslation',
            unique_together={('requirement_status', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='requirementtypetranslation',
            unique_together={('requirement_type', 'country')},
        ),
    ]
