# Generated by Django 5.2.8 on 2026-06-24 09:44

import django.utils.timezone
import encrypted_model_fields.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('current_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Approving Status')),
                ('status_comment', models.TextField(blank=True, verbose_name='Status Comment')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Status Changed At')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AccessConfigIsGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'Access Config IS Guide',
                'verbose_name_plural': 'Access Config IS Guides',
            },
        ),
        migrations.CreateModel(
            name='AccessConfigIsGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Access Config IS Guide Translation',
                'verbose_name_plural': 'Access Config IS Guide Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='AccessFunctionIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Function name, default: English (En). For other languages use Translations inline.', max_length=200, verbose_name='Access Function Name')),
                ('name_local', models.CharField(blank=True, help_text='Function name in local language (use Translations inline for per-country names)', max_length=200, verbose_name='Local Name')),
                ('code', models.CharField(blank=True, help_text='Unique code (auto-generated from name if empty)', max_length=80, verbose_name='Code')),
                ('description', models.TextField(blank=True, help_text='Description, default: English (En). For other languages use Translations inline.', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('environment', models.CharField(choices=[('production', 'Production'), ('test', 'Test'), ('development', 'Development')], default='test', max_length=20, verbose_name='Environment')),
                ('is_object_specific', models.BooleanField(default=False, help_text="If true, this function is only available for specific objects and won't appear in default system functions", verbose_name='Object Specific Function')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Access Function',
                'verbose_name_plural': 'Access Functions',
                'ordering': ['tree_id', 'lft'],
            },
        ),
        migrations.CreateModel(
            name='AccessFunctionISTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(help_text="Function name in country's language", max_length=200, verbose_name='Local Name')),
                ('description', models.TextField(blank=True, help_text="Description in country's language", verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Access Function Translation',
                'verbose_name_plural': 'Access Function Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='AccessISAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access_matrix', models.BooleanField(default=False, verbose_name='Has access to Access Matrix')),
                ('can_edit_matrix', models.BooleanField(default=False, verbose_name='Can edit Access Matrix')),
                ('has_access_records', models.BooleanField(default=False, verbose_name='Has access to Records')),
                ('can_add_access_records', models.BooleanField(default=False, verbose_name='Can add Access Records')),
                ('can_edit_access_records', models.BooleanField(default=False, verbose_name='Can edit Access Records')),
                ('can_delete_access_records', models.BooleanField(default=False, verbose_name='Can delete Access Records')),
                ('has_access_config_is', models.BooleanField(default=False, verbose_name='Has access to Config IS')),
                ('can_add_access_config_is', models.BooleanField(default=False, verbose_name='Can add Access Config IS')),
                ('can_edit_access_config_is', models.BooleanField(default=False, verbose_name='Can edit Access Config IS')),
                ('can_delete_access_config_is', models.BooleanField(default=False, verbose_name='Can delete Access Config IS')),
                ('has_access_manage_ar', models.BooleanField(default=False, verbose_name='Has access to Manage Access Requests')),
                ('can_add_manage_ar', models.BooleanField(default=False, verbose_name='Can add Manage Access Requests')),
                ('can_edit_manage_ar', models.BooleanField(default=False, verbose_name='Can edit Manage Access Requests')),
                ('can_delete_manage_ar', models.BooleanField(default=False, verbose_name='Can delete Manage Access Requests')),
                ('has_access_notification_settings', models.BooleanField(default=False, verbose_name='Has access to Notification Settings')),
                ('can_add_notification_settings', models.BooleanField(default=False, verbose_name='Can add Notification Settings')),
                ('can_edit_notification_settings', models.BooleanField(default=False, verbose_name='Can edit Notification Settings')),
                ('can_delete_notification_settings', models.BooleanField(default=False, verbose_name='Can delete Notification Settings')),
                ('has_access_api', models.BooleanField(default=False, verbose_name='Has access to API')),
                ('can_add_access_api', models.BooleanField(default=False, verbose_name='Can add Access API')),
                ('can_edit_access_api', models.BooleanField(default=False, verbose_name='Can edit Access API')),
                ('can_delete_access_api', models.BooleanField(default=False, verbose_name='Can delete Access API')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Access to ISAM',
                'verbose_name_plural': 'Access to ISAM',
            },
        ),
        migrations.CreateModel(
            name='AccessJustificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('content', models.TextField(verbose_name='Template Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Access Justification Template',
                'verbose_name_plural': 'Access Justification Templates',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccessJustificationTemplateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(blank=True, help_text="Template name in country's language", max_length=255, verbose_name='Local Name')),
                ('content', models.TextField(blank=True, help_text="Template text in country's language", verbose_name='Template Text')),
            ],
            options={
                'verbose_name': 'Access Justification Template Translation',
                'verbose_name_plural': 'Access Justification Template Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='AccessMatrixGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'Access Matrix Guide',
                'verbose_name_plural': 'Access Matrix Guides',
            },
        ),
        migrations.CreateModel(
            name='AccessMatrixGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Access Matrix Guide Translation',
                'verbose_name_plural': 'Access Matrix Guide Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='AccessNotificationGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'Access Notification Guide',
                'verbose_name_plural': 'Access Notification Guides',
            },
        ),
        migrations.CreateModel(
            name='AccessNotificationGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Access Notification Guide Translation',
                'verbose_name_plural': 'Access Notification Guide Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='AccessObjectFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'Object Function',
                'verbose_name_plural': 'Object Functions',
                'ordering': ['access_object', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AccessObjectIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Object name, default: English (En). For other languages use Translations inline.', max_length=200, verbose_name='Access Object Name')),
                ('name_local', models.CharField(blank=True, help_text='Object name in local language (use Translations inline for per-country names)', max_length=200, verbose_name='Local Name')),
                ('code', models.CharField(blank=True, help_text='Unique code (auto-generated from name if empty)', max_length=80, verbose_name='Code')),
                ('description', models.TextField(blank=True, help_text='Description, default: English (En). For other languages use Translations inline.', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('environment', models.CharField(choices=[('production', 'Production'), ('test', 'Test'), ('development', 'Development')], default='test', max_length=20, verbose_name='Environment')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Access Object',
                'verbose_name_plural': 'Access Objects',
                'ordering': ['tree_id', 'lft'],
            },
        ),
        migrations.CreateModel(
            name='AccessObjectISTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(help_text="Object name in country's language", max_length=200, verbose_name='Local Name')),
                ('description', models.TextField(blank=True, help_text="Description in country's language", verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Access Object Translation',
                'verbose_name_plural': 'Access Object Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='AccessRecordsGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'Access Records Guide',
                'verbose_name_plural': 'Access Records Guides',
            },
        ),
        migrations.CreateModel(
            name='AccessRecordsGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Access Records Guide Translation',
                'verbose_name_plural': 'Access Records Guide Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('grant', 'Grant Access'), ('revoke', 'Revoke Access')], default='grant', max_length=20, verbose_name='Request Type')),
                ('environment', models.CharField(choices=[('production', 'Production'), ('test', 'Test'), ('development', 'Development')], default='test', max_length=20, verbose_name='Environment')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('justification', models.TextField(verbose_name='Justification')),
                ('requirements', models.TextField(blank=True, verbose_name='Additional Requirements')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Admin Comment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Request Status')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Cancellation Reason')),
                ('admin_status', models.CharField(choices=[('pending', 'Pending'), ('granted', 'Access Granted'), ('denied', 'Access Denied'), ('in_progress', 'In Progress')], default='pending', max_length=20, verbose_name='Administrative Status')),
                ('admin_status_comment', models.TextField(blank=True, verbose_name='Administrative Status Comment')),
                ('admin_status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Admin Status Changed At')),
                ('third_party_first_name', models.CharField(blank=True, max_length=100, verbose_name='Third Party First Name')),
                ('third_party_last_name', models.CharField(blank=True, max_length=100, verbose_name='Third Party Last Name')),
                ('third_party_email', models.EmailField(blank=True, max_length=254, verbose_name='Third Party Email')),
                ('third_party_phone', models.CharField(blank=True, max_length=20, verbose_name='Third Party Phone')),
                ('third_party_organization', models.CharField(blank=True, max_length=200, verbose_name='Third Party Organization')),
                ('third_party_description', models.TextField(blank=True, verbose_name='Third Party Description')),
                ('third_party_count', models.PositiveIntegerField(default=0, help_text='Number of third party users', verbose_name='Third Party Count')),
                ('third_party_users_data', models.JSONField(blank=True, help_text='JSON data containing all third party users information', null=True, verbose_name='Third Party Users Data')),
                ('revoked_grant_access_record_ids', models.JSONField(blank=True, help_text='List of specific Grant Access Record IDs that are being revoked (format: ["70.194.1", "70.194.2"])', null=True, verbose_name='Revoked Grant Access Record IDs')),
                ('requested_for_count', models.PositiveIntegerField(default=1, help_text='Number of cabinet users requested for', verbose_name='Requested For Count')),
                ('requested_for_users_data', models.JSONField(blank=True, help_text='JSON data containing all cabinet users information for whom access is requested', null=True, verbose_name='Requested For Users Data')),
                ('requested_access_record_roles', models.JSONField(blank=True, help_text='Selected Object Role per access record when submitting grant request: [{"access_record_id": id, "role_id": id}, ...]', null=True, verbose_name='Requested Access Record Roles')),
            ],
            options={
                'verbose_name': 'Access Request',
                'verbose_name_plural': 'Access Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessRequestAdminStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending', 'Pending'), ('granted', 'Access Granted'), ('denied', 'Access Denied'), ('in_progress', 'In Progress')], max_length=20, verbose_name='Old Status')),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('granted', 'Access Granted'), ('denied', 'Access Denied'), ('in_progress', 'In Progress')], max_length=20, verbose_name='New Status')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
            ],
            options={
                'verbose_name': 'Access Request Admin Status History',
                'verbose_name_plural': 'Access Request Admin Status History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessRequestApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='Order')),
                ('current_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Approving Status')),
                ('status_comment', models.TextField(blank=True, verbose_name='Status Comment')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Status Changed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Access Request Approver',
                'verbose_name_plural': 'Access Request Approvers',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AccessRequestApproverStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Old Status')),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='New Status')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('approver_name', models.CharField(blank=True, max_length=255)),
                ('approver_email', models.EmailField(blank=True, max_length=254)),
                ('order_at_change', models.IntegerField(default=1)),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
            ],
            options={
                'verbose_name': 'Access Request Approver Status History',
                'verbose_name_plural': 'Access Request Approver Status History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='access_requests/attachments/%Y/%m/%d/', verbose_name='File')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('file_size', models.PositiveIntegerField(verbose_name='File Size (bytes)')),
                ('content_type', models.CharField(max_length=100, verbose_name='Content Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
            ],
            options={
                'verbose_name': 'Access Request Attachment',
                'verbose_name_plural': 'Access Request Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessRequestSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_id', models.CharField(help_text='Unique identifier for this access record sequence', max_length=50, unique=True, verbose_name='Sequence ID')),
                ('sequence_status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20, verbose_name='Sequence Status')),
                ('order_number', models.PositiveIntegerField(help_text='Order number within the grant request (1, 2, 3, etc.)', verbose_name='Order Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked At')),
            ],
            options={
                'verbose_name': 'Access Request Sequence',
                'verbose_name_plural': 'Access Request Sequences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Right name, default: English (En). For other languages use Translations inline.', max_length=200, verbose_name='Access Right Name')),
                ('name_local', models.CharField(blank=True, help_text='Right name in local language (use Translations inline for per-country names)', max_length=200, verbose_name='Local Name')),
                ('code', models.CharField(blank=True, help_text='Unique code (auto-generated from name if empty)', max_length=80, verbose_name='Code')),
                ('description', models.TextField(blank=True, help_text='Description, default: English (En). For other languages use Translations inline.', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('environment', models.CharField(choices=[('production', 'Production'), ('test', 'Test'), ('development', 'Development')], default='test', max_length=20, verbose_name='Environment')),
                ('is_object_specific', models.BooleanField(default=False, help_text="If true, this access right is only available for specific objects and won't appear in default system access rights", verbose_name='Object Specific Access Right')),
            ],
            options={
                'verbose_name': 'Access Right',
                'verbose_name_plural': 'Access Rights',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccessRightTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(help_text="Right name in country's language", max_length=200, verbose_name='Local Name')),
                ('description', models.TextField(blank=True, help_text="Description in country's language", verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Access Right Translation',
                'verbose_name_plural': 'Access Right Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='AccessRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Role name (default: English). For other languages add translations in admin (Translations inline) or in the application create/edit modals.', max_length=200, verbose_name='Role Name')),
                ('name_local', models.CharField(blank=True, help_text='Role name in local language (use Translations inline for per-country names)', max_length=200, verbose_name='Local Name')),
                ('code', models.CharField(blank=True, help_text='Unique code per system/environment (auto-generated from name if empty)', max_length=80, verbose_name='Code')),
                ('description', models.TextField(blank=True, help_text='Description (default: English). For other languages add translations in admin or in the application modals.', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('environment', models.CharField(choices=[('production', 'Production'), ('test', 'Test'), ('development', 'Development')], default='test', max_length=20, verbose_name='Environment')),
                ('is_object_specific', models.BooleanField(default=False, help_text="If true, this role is only available for specific objects and won't appear in default system roles", verbose_name='Object Specific Role')),
            ],
            options={
                'verbose_name': 'Access Role',
                'verbose_name_plural': 'Access Roles',
                'ordering': ['order', 'name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AccessRolesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(help_text="Role name in country's language", max_length=200, verbose_name='Local Name')),
                ('description', models.TextField(blank=True, help_text="Description in country's language", verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Access Role Translation',
                'verbose_name_plural': 'Access Role Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='AccessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('environment', models.CharField(choices=[('production', 'Production'), ('test', 'Test'), ('development', 'Development')], default='test', max_length=20, verbose_name='Environment')),
                ('is_object_specific', models.BooleanField(default=False, help_text="If true, this status is only available for specific objects and won't appear in default system statuses", verbose_name='Object Specific Status')),
            ],
            options={
                'verbose_name': 'Access Status',
                'verbose_name_plural': 'Access Statuses',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Credential Name')),
                ('url', models.URLField(max_length=255, verbose_name='API URL')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Password')),
                ('environment', models.CharField(choices=[('production', 'Production'), ('test', 'Test'), ('development', 'Development')], default='test', max_length=20, verbose_name='Environment')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Credential')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'API Credential',
                'verbose_name_plural': 'API Credentials',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApiSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(help_text='Unique identifier for this synchronization', max_length=50, unique=True, verbose_name='Sync ID')),
                ('is_scheduled', models.BooleanField(default=False, help_text='Whether this sync was scheduled or manual', verbose_name='Is Scheduled')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('error', 'Error'), ('stopped', 'Stopped')], default='running', max_length=20, verbose_name='Status')),
                ('current_step', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Step')),
                ('completed_steps', models.IntegerField(default=0, verbose_name='Completed Steps')),
                ('total_steps', models.IntegerField(default=0, verbose_name='Total Steps')),
                ('percent_complete', models.IntegerField(default=0, verbose_name='Percent Complete')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Extra Data')),
            ],
            options={
                'verbose_name': 'API Sync Status',
                'verbose_name_plural': 'API Sync Statuses',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='User ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('hash', models.CharField(max_length=255, unique=True, verbose_name='Hash')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'API User',
                'verbose_name_plural': 'API Users',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiUserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45)),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'API User Login History',
                'verbose_name_plural': 'API User Login Histories',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='ApiUserMerchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Merchant Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'API User Merchant',
                'verbose_name_plural': 'API User Merchants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApiUserMerchantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=255, verbose_name='Merchant Name')),
            ],
            options={
                'verbose_name': 'API User Merchant Link',
                'verbose_name_plural': 'API User Merchant Links',
                'ordering': ['merchant_name'],
            },
        ),
        migrations.CreateModel(
            name='ApiUserPermissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('added_permissions', models.JSONField(blank=True, default=dict, verbose_name='Added Permissions')),
                ('removed_permissions', models.JSONField(blank=True, default=dict, verbose_name='Removed Permissions')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Raw API Response')),
            ],
            options={
                'verbose_name': 'API User Permission History',
                'verbose_name_plural': 'API User Permission History',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='ApiUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(unique=True, verbose_name='Role ID')),
                ('name', models.CharField(max_length=100, verbose_name='Role Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'API User Role',
                'verbose_name_plural': 'API User Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApiUserRoleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'API User Role Mapping',
                'verbose_name_plural': 'API User Role Mappings',
            },
        ),
        migrations.CreateModel(
            name='ApiUserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('temporary_unavailable', 'Temporarily Unavailable'), ('unknown', 'Unknown')], default='unknown', max_length=50, verbose_name='Status')),
                ('raw_status', models.CharField(blank=True, max_length=100, verbose_name='Raw Status Value')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='Last Checked')),
            ],
            options={
                'verbose_name': 'API User Status',
                'verbose_name_plural': 'API User Statuses',
            },
        ),
        migrations.CreateModel(
            name='ApproverStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Old Status')),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='New Status')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
            ],
            options={
                'verbose_name': 'Approver Status History',
                'verbose_name_plural': 'Approver Status History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Color')),
                ('environment', models.CharField(choices=[('production', 'Production'), ('test', 'Test'), ('development', 'Development')], default='test', max_length=20, verbose_name='Environment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Approving Person',
                'verbose_name_plural': 'Approving Persons',
                'ordering': ['asset', 'order'],
            },
        ),
        migrations.CreateModel(
            name='EmailNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this notification configuration', max_length=200, unique=True, verbose_name='Configuration Name')),
                ('notification_type', models.CharField(choices=[('grant', 'Grant Access Request'), ('revoke', 'Revoke Access Request')], default='grant', help_text='Applies to grant or revoke access requests (matches request type)', max_length=20, verbose_name='Notification Type')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable email notifications', verbose_name='Enable Email Notifications')),
                ('send_on_request_created', models.BooleanField(default=True, help_text='Send notification when a new access request is created', verbose_name='Send on Request Created')),
                ('send_on_status_changed', models.BooleanField(default=True, help_text='Send notification when request status changes', verbose_name='Send on Status Changed')),
                ('send_on_admin_status_changed', models.BooleanField(default=True, help_text='Send notification when admin status changes', verbose_name='Send on Admin Status Changed')),
                ('notify_owners', models.BooleanField(default=True, help_text='Send notifications to system owners', verbose_name='Notify Owners')),
                ('notify_administrators', models.BooleanField(default=True, help_text='Send notifications to system administrators', verbose_name='Notify Administrators')),
                ('notify_requested_for', models.BooleanField(default=False, help_text='Send notifications to the user for whom access is requested', verbose_name='Notify Requested For')),
                ('notify_requested_by', models.BooleanField(default=True, help_text='Send notifications to the user who created the request', verbose_name='Notify Requested By')),
                ('notify_approving_persons', models.BooleanField(default=True, help_text='Send notifications to approving persons', verbose_name='Notify Approving Persons')),
                ('notify_third_party', models.BooleanField(default=False, help_text='Send notifications to third party email if provided', verbose_name='Notify Third Party')),
                ('include_third_party_info_in_emails', models.BooleanField(default=True, help_text='Include third party information in email templates', verbose_name='Include Third Party Info in Emails')),
                ('additional_recipients', models.TextField(blank=True, help_text='Additional email addresses separated by commas', verbose_name='Additional Recipients')),
                ('use_custom_templates', models.BooleanField(default=False, help_text='Use custom email templates instead of default ones', verbose_name='Use Custom Templates')),
                ('request_created_subject_template', models.CharField(blank=True, help_text='Custom subject template for request created notifications. Use variables like {company_name}, {system_name}, etc.', max_length=500, verbose_name='Request Created Subject Template')),
                ('request_created_html_template', models.TextField(blank=True, help_text='Custom HTML template for request created notifications', verbose_name='Request Created HTML Template')),
                ('request_created_text_template', models.TextField(blank=True, help_text='Custom text template for request created notifications', verbose_name='Request Created Text Template')),
                ('status_changed_subject_template', models.CharField(blank=True, help_text='Custom subject template for status changed notifications', max_length=500, verbose_name='Status Changed Subject Template')),
                ('status_changed_html_template', models.TextField(blank=True, help_text='Custom HTML template for status changed notifications', verbose_name='Status Changed HTML Template')),
                ('status_changed_text_template', models.TextField(blank=True, help_text='Custom text template for status changed notifications', verbose_name='Status Changed Text Template')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Configuration priority. Lower numbers have higher priority.', verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'Email Notification Configuration',
                'verbose_name_plural': 'Email Notification Configurations',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailNotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('access_request_created', 'Access Request Created'), ('access_request_status_changed', 'Access Request Status Changed'), ('admin_status_changed', 'Admin Status Changed'), ('access_granted', 'Access Granted'), ('access_denied', 'Access Denied'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('access_status_changed', 'Access Status Changed')], max_length=50, verbose_name='Notification Type')),
                ('subject', models.CharField(max_length=500, verbose_name='Email Subject')),
                ('recipients', models.JSONField(help_text='List of email addresses that received this notification', verbose_name='Recipients')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Recipients Count')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Retry Count')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Max Retries')),
                ('template_data', models.JSONField(blank=True, default=dict, help_text='Additional data used for email template rendering', verbose_name='Template Data')),
            ],
            options={
                'verbose_name': 'Email Notification History',
                'verbose_name_plural': 'Email Notification History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManageAccessRequestsGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'Manage Access Requests Guide',
                'verbose_name_plural': 'Manage Access Requests Guides',
            },
        ),
        migrations.CreateModel(
            name='ManageAccessRequestsGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Manage Access Requests Guide Translation',
                'verbose_name_plural': 'Manage Access Requests Guide Translations',
                'ordering': ['country__name'],
            },
        ),
        migrations.CreateModel(
            name='ObjectAccessRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'Object Access Right',
                'verbose_name_plural': 'Object Access Rights',
                'ordering': ['access_object', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ObjectFunctionRightMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'Object Function Right Mapping',
                'verbose_name_plural': 'Object Function Right Mappings',
                'ordering': ['access_object', 'function', 'access_right'],
            },
        ),
        migrations.CreateModel(
            name='ObjectRoleFunctionRightMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Object Role Function Right Mapping',
                'verbose_name_plural': 'Object Role Function Right Mappings',
                'ordering': ['access_object', 'role', 'function', 'access_right'],
            },
        ),
        migrations.CreateModel(
            name='ObjectRoleFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'Object Role Function',
                'verbose_name_plural': 'Object Role Functions',
                'ordering': ['object_role', 'function'],
            },
        ),
        migrations.CreateModel(
            name='ObjectRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'Object Role',
                'verbose_name_plural': 'Object Roles',
                'ordering': ['access_object', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RoleFunctionRightMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Role Function Right Mapping',
                'verbose_name_plural': 'Role Function Right Mappings',
                'ordering': ['role', 'function', 'access_right'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Schedule Name')),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=10, verbose_name='Frequency')),
                ('hourly_cycle', models.IntegerField(choices=[(1, 'Every hour'), (2, 'Every 2 hours'), (3, 'Every 3 hours'), (4, 'Every 4 hours'), (6, 'Every 6 hours'), (8, 'Every 8 hours'), (12, 'Every 12 hours')], default=1, help_text='How many hours between each sync when using hourly frequency', verbose_name='Hourly Cycle')),
                ('scheduled_time', models.DateTimeField(verbose_name='Scheduled Time')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Last Run')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Next Run')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('celery_task_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celery Task ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Scheduled Sync',
                'verbose_name_plural': 'Scheduled Syncs',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='SystemAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('production', 'Production'), ('test', 'Test'), ('development', 'Development')], default='test', max_length=20, verbose_name='Environment')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Access Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Access End Date')),
                ('last_review', models.DateTimeField(blank=True, null=True, verbose_name='Last Review Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Record Active')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('third_parties', models.BooleanField(default=False, help_text='Access for third parties (customers, technical support, merchants, etc.)', verbose_name='Third Parties Access')),
            ],
            options={
                'verbose_name': 'System Access',
                'verbose_name_plural': 'System Access Records',
                'ordering': ['-modified_at'],
                'permissions': [('can_review_access', 'Can review access records'), ('can_grant_access', 'Can grant system access'), ('can_revoke_access', 'Can revoke system access')],
            },
        ),
        migrations.CreateModel(
            name='SystemAccessStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_reason', models.TextField(blank=True, verbose_name='Change Reason')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
            ],
            options={
                'verbose_name': 'Access Record Status History',
                'verbose_name_plural': 'Access Record Status History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Organization Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'Third Party Organization',
                'verbose_name_plural': 'Third Party Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(help_text='Email must be unique among all third party users', max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('organization_name', models.CharField(blank=True, help_text='Legacy field for backward compatibility', max_length=200, verbose_name='Organization Name (Legacy)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Third Party User',
                'verbose_name_plural': 'Third Party Users',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='UserAccessRequestGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', tinymce.models.HTMLField(blank=True, help_text='Default guide content (rich text). Use as source for AI translations.', verbose_name='Base content')),
            ],
            options={
                'verbose_name': 'User Access Request Guide',
                'verbose_name_plural': 'User Access Request Guides',
            },
        ),
        migrations.CreateModel(
            name='UserAccessRequestGuideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Guide content in this country's language.", verbose_name='Content')),
            ],
            options={
                'verbose_name': 'User Access Request Guide Translation',
                'verbose_name_plural': 'User Access Request Guide Translations',
                'ordering': ['country__name'],
            },
        ),
    ]
