# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_access', '0001_initial'),
        ('app_cabinet', '0001_initial'),
        ('auth', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessapprover',
            name='cabinet_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cabinet.cabinetuser'),
        ),
        migrations.AddField(
            model_name='accessapprover',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Status Changed By'),
        ),
    ]
