# Generated by Django 5.2.8 on 2026-06-24 09:44

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_access', '0002_initial'),
        ('app_asset', '0001_initial'),
        ('app_cabinet', '0001_initial'),
        ('app_conf', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessconfigisguidetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_config_is_guide_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='accessconfigisguidetranslation',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_access.accessconfigisguide', verbose_name='Guide'),
        ),
        migrations.AddField(
            model_name='accessfunctionis',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_functions', to='app_asset.informationasset', verbose_name='Information System'),
        ),
        migrations.AddField(
            model_name='accessfunctionis',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_access.accessfunctionis', verbose_name='Parent Function'),
        ),
        migrations.AddField(
            model_name='accessfunctionistranslation',
            name='access_function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_access.accessfunctionis', verbose_name='Access Function'),
        ),
        migrations.AddField(
            model_name='accessfunctionistranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_function_is_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='accessisam',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='access_isam', to='app_conf.company', verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='accessisam',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='accessjustificationtemplate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_justification_templates', to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='accessjustificationtemplatetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_justification_template_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='accessjustificationtemplatetranslation',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_access.accessjustificationtemplate', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='accessmatrixguidetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_matrix_guide_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='accessmatrixguidetranslation',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_access.accessmatrixguide', verbose_name='Guide'),
        ),
        migrations.AddField(
            model_name='accessnotificationguidetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_notification_guide_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='accessnotificationguidetranslation',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_access.accessnotificationguide', verbose_name='Guide'),
        ),
        migrations.AddField(
            model_name='accessobjectfunction',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_assignments', to='app_access.accessfunctionis', verbose_name='Access Function'),
        ),
        migrations.AddField(
            model_name='accessobjectis',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_objects', to='app_asset.informationasset', verbose_name='Information System'),
        ),
        migrations.AddField(
            model_name='accessobjectis',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_access.accessobjectis', verbose_name='Parent Object'),
        ),
        migrations.AddField(
            model_name='accessobjectfunction',
            name='access_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_functions', to='app_access.accessobjectis', verbose_name='Access Object'),
        ),
        migrations.AddField(
            model_name='accessfunctionis',
            name='created_for_object',
            field=models.ForeignKey(blank=True, help_text='The object this custom function was created for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_functions', to='app_access.accessobjectis', verbose_name='Created For Object'),
        ),
        migrations.AddField(
            model_name='accessobjectistranslation',
            name='access_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_access.accessobjectis', verbose_name='Access Object'),
        ),
        migrations.AddField(
            model_name='accessobjectistranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_object_is_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='accessrecordsguidetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_records_guide_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='accessrecordsguidetranslation',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_access.accessrecordsguide', verbose_name='Guide'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='admin_status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_status_requests_changed', to=settings.AUTH_USER_MODEL, verbose_name='Admin Status Changed By'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_requests', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled By'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests_by', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='requested_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests_for', to=settings.AUTH_USER_MODEL, verbose_name='Requested For'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_asset.informationasset', verbose_name='Information System'),
        ),
        migrations.AddField(
            model_name='accessrequestadminstatushistory',
            name='access_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_status_history', to='app_access.accessrequest', verbose_name='Access Request'),
        ),
        migrations.AddField(
            model_name='accessrequestadminstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_status_changes_history', to=settings.AUTH_USER_MODEL, verbose_name='Changed By'),
        ),
        migrations.AddField(
            model_name='accessrequestapprover',
            name='access_approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_access.accessapprover', verbose_name='Access Approver'),
        ),
        migrations.AddField(
            model_name='accessrequestapprover',
            name='access_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_approvers', to='app_access.accessrequest', verbose_name='Access Request'),
        ),
        migrations.AddField(
            model_name='accessrequestapprover',
            name='cabinet_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cabinet.cabinetuser', verbose_name='Cabinet User'),
        ),
        migrations.AddField(
            model_name='accessrequestapprover',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_request_approver_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Status Changed By'),
        ),
        migrations.AddField(
            model_name='accessrequestapproverstatushistory',
            name='access_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver_status_history', to='app_access.accessrequest', verbose_name='Access Request'),
        ),
        migrations.AddField(
            model_name='accessrequestapproverstatushistory',
            name='approver_cabinet_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cabinet.cabinetuser', verbose_name='Approver Cabinet User'),
        ),
        migrations.AddField(
            model_name='accessrequestapproverstatushistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Changed By'),
        ),
        migrations.AddField(
            model_name='accessrequestapproverstatushistory',
            name='request_approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_history', to='app_access.accessrequestapprover', verbose_name='Request Approver'),
        ),
        migrations.AddField(
            model_name='accessrequestattachment',
            name='access_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app_access.accessrequest', verbose_name='Access Request'),
        ),
        migrations.AddField(
            model_name='accessrequestattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AddField(
            model_name='accessrequestsequence',
            name='grant_request',
            field=models.ForeignKey(help_text='The grant request that created this access record', on_delete=django.db.models.deletion.CASCADE, related_name='access_sequences', to='app_access.accessrequest', verbose_name='Grant Request'),
        ),
        migrations.AddField(
            model_name='accessrequestsequence',
            name='revoke_request',
            field=models.ForeignKey(blank=True, help_text='The revoke request that cancelled this access record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_sequences', to='app_access.accessrequest', verbose_name='Revoke Request'),
        ),
        migrations.AddField(
            model_name='accessright',
            name='created_for_object',
            field=models.ForeignKey(blank=True, help_text='The specific object this access right was created for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_access_rights', to='app_access.accessobjectis', verbose_name='Created For Object'),
        ),
        migrations.AddField(
            model_name='accessright',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rights', to='app_asset.informationasset', verbose_name='Information System'),
        ),
        migrations.AddField(
            model_name='accessfunctionis',
            name='access_rights',
            field=models.ManyToManyField(blank=True, related_name='functions', to='app_access.accessright', verbose_name='Access Rights'),
        ),
        migrations.AddField(
            model_name='accessrighttranslation',
            name='access_right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_access.accessright', verbose_name='Access Right'),
        ),
        migrations.AddField(
            model_name='accessrighttranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_right_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='accessroles',
            name='created_for_object',
            field=models.ForeignKey(blank=True, help_text='The specific object this role was created for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='app_access.accessobjectis', verbose_name='Created For Object'),
        ),
        migrations.AddField(
            model_name='accessroles',
            name='functions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='app_access.accessfunctionis', verbose_name='Functions'),
        ),
        migrations.AddField(
            model_name='accessroles',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_roles', to='app_asset.informationasset', verbose_name='Information System'),
        ),
        migrations.AddField(
            model_name='accessrolestranslation',
            name='access_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_access.accessroles', verbose_name='Access Role'),
        ),
        migrations.AddField(
            model_name='accessrolestranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_role_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='accessstatus',
            name='created_for_object',
            field=models.ForeignKey(blank=True, help_text='The specific object this status was created for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_statuses', to='app_access.accessobjectis', verbose_name='Created For Object'),
        ),
        migrations.AddField(
            model_name='accessstatus',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_status', to='app_asset.informationasset', verbose_name='Information System'),
        ),
        migrations.AddField(
            model_name='apicredential',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_credentials', to='app_conf.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='apicredential',
            name='information_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_credentials', to='app_asset.informationasset', verbose_name='Information System'),
        ),
        migrations.AddField(
            model_name='apicredential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_credentials', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='apisyncstatus',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_statuses', to='app_access.apicredential', verbose_name='API Credential'),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='api_credential',
            field=models.ForeignKey(blank=True, help_text='Credential used for the last successful sync of this user; used to drop users removed from that API.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_users', to='app_access.apicredential', verbose_name='Source API credential'),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='sync',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='app_access.apisyncstatus', verbose_name='Sync ID'),
        ),
        migrations.AddField(
            model_name='apiuserloginhistory',
            name='sync',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_histories', to='app_access.apisyncstatus', verbose_name='Sync ID'),
        ),
        migrations.AddField(
            model_name='apiuserloginhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='app_access.apiuser'),
        ),
        migrations.AddField(
            model_name='apiusermerchant',
            name='sync',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='app_access.apisyncstatus', verbose_name='Sync ID'),
        ),
        migrations.AddField(
            model_name='apiusermerchantlink',
            name='sync',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_links', to='app_access.apisyncstatus', verbose_name='Sync ID'),
        ),
        migrations.AddField(
            model_name='apiusermerchantlink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_links', to='app_access.apiuser', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='apiuserpermissionhistory',
            name='sync',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_histories', to='app_access.apisyncstatus', verbose_name='Sync ID'),
        ),
        migrations.AddField(
            model_name='apiuserpermissionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_history', to='app_access.apiuser', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='apiuserrole',
            name='sync',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='app_access.apisyncstatus', verbose_name='Sync ID'),
        ),
        migrations.AddField(
            model_name='apiuserrolemapping',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_mappings', to='app_access.apiusermerchant', verbose_name='Merchant'),
        ),
        migrations.AddField(
            model_name='apiuserrolemapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_mappings', to='app_access.apiuserrole', verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='apiuserrolemapping',
            name='sync',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_mappings', to='app_access.apisyncstatus', verbose_name='Sync ID'),
        ),
        migrations.AddField(
            model_name='apiuserrolemapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_mappings', to='app_access.apiuser', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='apiuserstatus',
            name='sync',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_statuses', to='app_access.apisyncstatus', verbose_name='Sync ID'),
        ),
        migrations.AddField(
            model_name='apiuserstatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_info', to='app_access.apiuser', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='approverstatushistory',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='app_access.accessapprover', verbose_name='Approver'),
        ),
        migrations.AddField(
            model_name='approverstatushistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Changed By'),
        ),
        migrations.AddField(
            model_name='approvingperson',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approving_persons', to='app_asset.informationasset'),
        ),
        migrations.AddField(
            model_name='approvingperson',
            name='cabinet_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approving_assets', to='app_cabinet.cabinetuser'),
        ),
        migrations.AddField(
            model_name='emailnotificationconfig',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='Limit this configuration to specific companies. If empty, applies to all companies.', to='app_conf.company', verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='emailnotificationconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_configs', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='emailnotificationconfig',
            name='mail_account',
            field=models.ForeignKey(blank=True, help_text='Specific mail account to use for sending notifications. If not set, default will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_conf.mailaccount', verbose_name='Mail Account'),
        ),
        migrations.AddField(
            model_name='emailnotificationconfig',
            name='mail_server',
            field=models.ForeignKey(blank=True, help_text='Specific mail server to use for sending notifications. If not set, default will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_conf.mailserver', verbose_name='Mail Server'),
        ),
        migrations.AddField(
            model_name='emailnotificationconfig',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_email_configs', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='emailnotificationconfig',
            name='systems',
            field=models.ManyToManyField(blank=True, help_text='Limit this configuration to specific systems. If empty, applies to all systems.', to='app_asset.informationasset', verbose_name='Systems'),
        ),
        migrations.AddField(
            model_name='emailnotificationhistory',
            name='access_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to='app_access.accessrequest', verbose_name='Access Request'),
        ),
        migrations.AddField(
            model_name='emailnotificationhistory',
            name='mail_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_conf.mailaccount', verbose_name='Mail Account Used'),
        ),
        migrations.AddField(
            model_name='emailnotificationhistory',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Triggered By'),
        ),
        migrations.AddField(
            model_name='manageaccessrequestsguidetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manage_access_requests_guide_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='manageaccessrequestsguidetranslation',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_access.manageaccessrequestsguide', verbose_name='Guide'),
        ),
        migrations.AddField(
            model_name='objectaccessrights',
            name='access_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_access_rights', to='app_access.accessobjectis', verbose_name='Access Object'),
        ),
        migrations.AddField(
            model_name='objectaccessrights',
            name='access_right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_assignments', to='app_access.accessright', verbose_name='Access Right'),
        ),
        migrations.AddField(
            model_name='objectfunctionrightmapping',
            name='access_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_right_mappings', to='app_access.accessobjectis', verbose_name='Access Object'),
        ),
        migrations.AddField(
            model_name='objectfunctionrightmapping',
            name='access_right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_function_mappings', to='app_access.accessright', verbose_name='Access Right'),
        ),
        migrations.AddField(
            model_name='objectfunctionrightmapping',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_object_mappings', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='objectfunctionrightmapping',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_right_mappings', to='app_access.accessfunctionis', verbose_name='Function'),
        ),
        migrations.AddField(
            model_name='objectfunctionrightmapping',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_object_mappings', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='objectrolefunctionrightmapping',
            name='access_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_function_right_mappings', to='app_access.accessobjectis', verbose_name='Access Object'),
        ),
        migrations.AddField(
            model_name='objectrolefunctionrightmapping',
            name='access_right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_role_function_mappings', to='app_access.accessright', verbose_name='Access Right'),
        ),
        migrations.AddField(
            model_name='objectrolefunctionrightmapping',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_role_right_mappings', to='app_access.accessfunctionis', verbose_name='Function'),
        ),
        migrations.AddField(
            model_name='objectrolefunctionrightmapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_function_right_mappings', to='app_access.accessroles', verbose_name='Access Role'),
        ),
        migrations.AddField(
            model_name='objectrolefunctions',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_role_assignments', to='app_access.accessfunctionis', verbose_name='Access Function'),
        ),
        migrations.AddField(
            model_name='objectroles',
            name='access_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_roles', to='app_access.accessobjectis', verbose_name='Access Object'),
        ),
        migrations.AddField(
            model_name='objectroles',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_assignments', to='app_access.accessroles', verbose_name='Access Role'),
        ),
        migrations.AddField(
            model_name='objectrolefunctions',
            name='object_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_functions', to='app_access.objectroles', verbose_name='Object Role'),
        ),
        migrations.AddField(
            model_name='rolefunctionrightmapping',
            name='access_right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_function_mappings', to='app_access.accessright', verbose_name='Access Right'),
        ),
        migrations.AddField(
            model_name='rolefunctionrightmapping',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_right_mappings', to='app_access.accessfunctionis', verbose_name='Function'),
        ),
        migrations.AddField(
            model_name='rolefunctionrightmapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_right_mappings', to='app_access.accessroles', verbose_name='Access Role'),
        ),
        migrations.AddField(
            model_name='scheduledsync',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_syncs', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='scheduledsync',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_syncs', to='app_access.apicredential', verbose_name='API Credential'),
        ),
        migrations.AddField(
            model_name='scheduledsync',
            name='periodic_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask', verbose_name='Periodic Task'),
        ),
        migrations.AddField(
            model_name='systemaccess',
            name='access_groups',
            field=models.ManyToManyField(related_name='system_access_granted', to='auth.group', verbose_name='Access Groups'),
        ),
        migrations.AddField(
            model_name='systemaccess',
            name='access_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to='app_access.accessobjectis', verbose_name='Object'),
        ),
        migrations.AddField(
            model_name='systemaccess',
            name='access_right',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_accesses', to='app_access.accessright', verbose_name='Access Right'),
        ),
        migrations.AddField(
            model_name='systemaccess',
            name='access_users',
            field=models.ManyToManyField(related_name='system_access_granted', to=settings.AUTH_USER_MODEL, verbose_name='Access Users'),
        ),
        migrations.AddField(
            model_name='systemaccess',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to='app_asset.informationasset', verbose_name='Information System'),
        ),
        migrations.AddField(
            model_name='systemaccess',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_access', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='systemaccess',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_access', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='systemaccess',
            name='request_groups',
            field=models.ManyToManyField(blank=True, related_name='system_access_requests', to='auth.group', verbose_name='Request Groups'),
        ),
        migrations.AddField(
            model_name='systemaccess',
            name='request_users',
            field=models.ManyToManyField(blank=True, related_name='system_access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Request Users'),
        ),
        migrations.AddField(
            model_name='systemaccess',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='systemaccess',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='system_accesses', to='app_access.accessroles', verbose_name='Roles'),
        ),
        migrations.AddField(
            model_name='systemaccess',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_accesses', to='app_access.accessstatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='accessrequestsequence',
            name='access_record',
            field=models.ForeignKey(help_text='The access record in this sequence', on_delete=django.db.models.deletion.CASCADE, related_name='access_sequences', to='app_access.systemaccess', verbose_name='Access Record'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='access_records',
            field=models.ManyToManyField(blank=True, related_name='access_requests', to='app_access.systemaccess', verbose_name='Access Records'),
        ),
        migrations.AddField(
            model_name='accessapprover',
            name='access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='app_access.systemaccess'),
        ),
        migrations.AddField(
            model_name='systemaccessstatushistory',
            name='access_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='app_access.systemaccess', verbose_name='Access Record'),
        ),
        migrations.AddField(
            model_name='systemaccessstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_record_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed By'),
        ),
        migrations.AddField(
            model_name='systemaccessstatushistory',
            name='new_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_status_history', to='app_access.accessstatus', verbose_name='New Status'),
        ),
        migrations.AddField(
            model_name='systemaccessstatushistory',
            name='old_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_status_history', to='app_access.accessstatus', verbose_name='Old Status'),
        ),
        migrations.AddField(
            model_name='systemaccessstatushistory',
            name='revoke_request',
            field=models.ForeignKey(blank=True, help_text='The revoke request that caused this status change (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_access_records', to='app_access.accessrequest', verbose_name='Revoke Request'),
        ),
        migrations.AddField(
            model_name='thirdpartyorganization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_third_party_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='thirdpartyuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_third_party_users', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='thirdpartyuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_party_users', to='app_access.thirdpartyorganization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='third_party_users',
            field=models.ManyToManyField(blank=True, help_text='Third party users associated with this access request', related_name='access_requests', to='app_access.thirdpartyuser', verbose_name='Third Party Users'),
        ),
        migrations.AddField(
            model_name='useraccessrequestguidetranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access_request_guide_translations', to='app_conf.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='useraccessrequestguidetranslation',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_access.useraccessrequestguide', verbose_name='Guide'),
        ),
        migrations.AlterUniqueTogether(
            name='accessconfigisguidetranslation',
            unique_together={('guide', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='accessfunctionistranslation',
            unique_together={('access_function', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='accessisam',
            unique_together={('group',)},
        ),
        migrations.AlterUniqueTogether(
            name='accessjustificationtemplatetranslation',
            unique_together={('template', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='accessmatrixguidetranslation',
            unique_together={('guide', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='accessnotificationguidetranslation',
            unique_together={('guide', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='accessobjectis',
            unique_together={('asset', 'name', 'environment')},
        ),
        migrations.AddConstraint(
            model_name='accessobjectfunction',
            constraint=models.UniqueConstraint(fields=('access_object', 'function'), name='unique_object_function'),
        ),
        migrations.AlterUniqueTogether(
            name='accessobjectistranslation',
            unique_together={('access_object', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='accessrecordsguidetranslation',
            unique_together={('guide', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='accessrequestapprover',
            unique_together={('access_request', 'cabinet_user')},
        ),
        migrations.AlterUniqueTogether(
            name='accessfunctionis',
            unique_together={('asset', 'code', 'environment')},
        ),
        migrations.AlterUniqueTogether(
            name='accessrighttranslation',
            unique_together={('access_right', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='accessroles',
            unique_together={('system', 'code', 'environment')},
        ),
        migrations.AlterUniqueTogether(
            name='accessrolestranslation',
            unique_together={('access_role', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='apicredential',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='apiusermerchantlink',
            unique_together={('user', 'merchant_name')},
        ),
        migrations.AlterUniqueTogether(
            name='apiuserrolemapping',
            unique_together={('user', 'merchant', 'role')},
        ),
        migrations.AddConstraint(
            model_name='approvingperson',
            constraint=models.UniqueConstraint(fields=('asset', 'cabinet_user', 'order', 'environment'), name='unique_asset_user_order_environment'),
        ),
        migrations.AddIndex(
            model_name='emailnotificationhistory',
            index=models.Index(fields=['notification_type'], name='app_access__notific_5e5740_idx'),
        ),
        migrations.AddIndex(
            model_name='emailnotificationhistory',
            index=models.Index(fields=['status'], name='app_access__status_d781a8_idx'),
        ),
        migrations.AddIndex(
            model_name='emailnotificationhistory',
            index=models.Index(fields=['access_request'], name='app_access__access__6343e9_idx'),
        ),
        migrations.AddIndex(
            model_name='emailnotificationhistory',
            index=models.Index(fields=['created_at'], name='app_access__created_6fd7c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='manageaccessrequestsguidetranslation',
            unique_together={('guide', 'country')},
        ),
        migrations.AddConstraint(
            model_name='objectaccessrights',
            constraint=models.UniqueConstraint(fields=('access_object', 'access_right'), name='unique_object_access_right'),
        ),
        migrations.AddConstraint(
            model_name='objectfunctionrightmapping',
            constraint=models.UniqueConstraint(fields=('access_object', 'function', 'access_right'), name='unique_object_function_right'),
        ),
        migrations.AddConstraint(
            model_name='objectrolefunctionrightmapping',
            constraint=models.UniqueConstraint(fields=('access_object', 'role', 'function', 'access_right'), name='unique_object_role_function_right'),
        ),
        migrations.AddConstraint(
            model_name='objectroles',
            constraint=models.UniqueConstraint(fields=('access_object', 'role'), name='unique_object_role'),
        ),
        migrations.AddConstraint(
            model_name='objectrolefunctions',
            constraint=models.UniqueConstraint(fields=('object_role', 'function'), name='unique_object_role_function'),
        ),
        migrations.AddConstraint(
            model_name='rolefunctionrightmapping',
            constraint=models.UniqueConstraint(fields=('role', 'function', 'access_right'), name='unique_role_function_right'),
        ),
        migrations.AddIndex(
            model_name='systemaccess',
            index=models.Index(fields=['status'], name='app_access__status__90aaea_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaccess',
            index=models.Index(fields=['access_right'], name='app_access__access__d6284d_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaccess',
            index=models.Index(fields=['last_review'], name='app_access__last_re_9a7424_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequestsequence',
            index=models.Index(fields=['sequence_id'], name='app_access__sequenc_ce9fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequestsequence',
            index=models.Index(fields=['grant_request'], name='app_access__grant_r_0cd914_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequestsequence',
            index=models.Index(fields=['revoke_request'], name='app_access__revoke__63fe82_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequestsequence',
            index=models.Index(fields=['sequence_status'], name='app_access__sequenc_7576a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accessapprover',
            unique_together={('access', 'cabinet_user')},
        ),
        migrations.AddIndex(
            model_name='thirdpartyuser',
            index=models.Index(fields=['email'], name='app_access__email_648c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='thirdpartyuser',
            index=models.Index(fields=['created_at'], name='app_access__created_a6fbca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useraccessrequestguidetranslation',
            unique_together={('guide', 'country')},
        ),
    ]
