# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_access', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRoleFunctionRightMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('access_right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_role_function_mappings', to='app_access.accessright', verbose_name='Access Right')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_right_mappings', to='app_access.accessfunctionis', verbose_name='Function')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_right_mappings', to='app_access.accessroles', verbose_name='Role')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_system_role_mappings', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_system_role_mappings', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'System Role Function Right Mapping',
                'verbose_name_plural': 'System Role Function Right Mappings',
                'ordering': ['role', 'function', 'access_right'],
            },
        ),
        migrations.AddConstraint(
            model_name='systemrolefunctionrightmapping',
            constraint=models.UniqueConstraint(fields=('role', 'function', 'access_right'), name='unique_system_role_function_right'),
        ),
    ]
