# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_access', '0004_add_role_function_right_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectfunctionrightmapping',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_function_right_mappings', to='app_access.accessroles', verbose_name='Access Role'),
        ),
        migrations.RemoveConstraint(
            model_name='objectfunctionrightmapping',
            name='unique_object_function_right',
        ),
        migrations.AddConstraint(
            model_name='objectfunctionrightmapping',
            constraint=models.UniqueConstraint(fields=('access_object', 'role', 'function', 'access_right'), name='unique_object_role_function_right'),
        ),
    ]
