# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_access', '0004_add_role_function_right_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectRoleFunctionRightMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('access_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_function_right_mappings', to='app_access.accessobjectis', verbose_name='Access Object')),
                ('access_right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_role_function_mappings', to='app_access.accessright', verbose_name='Access Right')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_role_right_mappings', to='app_access.accessfunctionis', verbose_name='Function')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_function_right_mappings', to='app_access.accessroles', verbose_name='Access Role')),
            ],
            options={
                'verbose_name': 'Object Role Function Right Mapping',
                'verbose_name_plural': 'Object Role Function Right Mappings',
                'ordering': ['access_object', 'role', 'function', 'access_right'],
            },
        ),
        migrations.AddConstraint(
            model_name='objectrolefunctionrightmapping',
            constraint=models.UniqueConstraint(fields=('access_object', 'role', 'function', 'access_right'), name='unique_object_role_function_right'),
        ),
    ]
