# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_access', '0005_add_object_role_function_right_mapping'),
        ('app_access', '0005_add_role_to_object_function_right_mapping'),
    ]

    operations = [
    ]
