# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_access', '0005_scheduledsync_periodic_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='requested_access_record_roles',
            field=models.JSONField(blank=True, help_text='Selected Object Role per access record when submitting grant request: [{"access_record_id": id, "role_id": id}, ...]', null=True, verbose_name='Requested Access Record Roles'),
        ),
    ]
