# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_access', '0006_merge_20260224_1926'),
        ('auth', '__first__'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='objectfunctionrightmapping',
            name='unique_object_role_function_right',
        ),
        migrations.RemoveField(
            model_name='objectfunctionrightmapping',
            name='role',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='requested_access_record_roles',
            field=models.JSONField(blank=True, help_text='Selected Object Role per access record when submitting grant request: [{"access_record_id": id, "role_id": id}, ...]', null=True, verbose_name='Requested Access Record Roles'),
        ),
        migrations.AddConstraint(
            model_name='objectfunctionrightmapping',
            constraint=models.UniqueConstraint(fields=('access_object', 'function', 'access_right'), name='unique_object_function_right'),
        ),
    ]
