# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_access', '0006_accessrequest_requested_access_record_roles'),
        ('app_access', '0007_add_requested_access_record_roles'),
    ]

    operations = [
    ]
