# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_access', '0008_merge_20260326_1012'),
        ('app_conf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessJustificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('content', models.TextField(verbose_name='Template Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_justification_templates', to='app_conf.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Access Justification Template',
                'verbose_name_plural': 'Access Justification Templates',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccessJustificationTemplateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(blank=True, help_text="Template name in country's language", max_length=255, verbose_name='Local Name')),
                ('content', models.TextField(blank=True, help_text="Template text in country's language", verbose_name='Template Text')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_justification_template_translations', to='app_conf.country', verbose_name='Country')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_access.accessjustificationtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Access Justification Template Translation',
                'verbose_name_plural': 'Access Justification Template Translations',
                'ordering': ['country__name'],
                'unique_together': {('template', 'country')},
            },
        ),
    ]
