# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_access', '0009_access_justification_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='api_credential',
            field=models.ForeignKey(blank=True, help_text='Credential used for the last successful sync of this user; used to drop users removed from that API.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_users', to='app_access.apicredential', verbose_name='Source API credential'),
        ),
    ]
