# Generated by Django 5.2.8 on 2026-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_access', '0010_apiuser_api_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotificationconfig',
            name='notification_type',
            field=models.CharField(choices=[('grant', 'Grant Access Request'), ('revoke', 'Revoke Access Request')], default='grant', help_text='Applies to grant or revoke access requests (matches request type)', max_length=20, verbose_name='Notification Type'),
        ),
    ]
