# Generated by Django 5.2.8 on 2026-06-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0025_external_media_cia'),
        ('app_risk', '0004_external_media_vulnerability'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktreatment',
            name='external_media_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_treatments', to='app_asset.externalmediaregister'),
        ),
        migrations.AddField(
            model_name='risktreatment',
            name='software_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_treatments', to='app_asset.softwareregister'),
        ),
        migrations.AlterField(
            model_name='risktreatment',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_treatments', to='app_asset.informationasset'),
        ),
    ]
